using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x0200011A RID: 282
	internal enum IIDENTITYAUTHORITY_DOES_DEFINITION_MATCH_REFERENCE_FLAGS
	{
		// Token: 0x04000511 RID: 1297
		IIDENTITYAUTHORITY_DOES_DEFINITION_MATCH_REFERENCE_FLAG_EXACT_MATCH_REQUIRED = 1
	}
}
