using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x02000118 RID: 280
	internal enum IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x0400050D RID: 1293
		IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
