namespace triFixAlmSndCyl
{
	// Token: 0x0200000E RID: 14
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmAlarmSndCfg : global::System.Windows.Forms.Form
	{
		// Token: 0x0600004F RID: 79 RVA: 0x00006B30 File Offset: 0x00004F30
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x06000050 RID: 80 RVA: 0x00006B50 File Offset: 0x00004F50
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::triFixAlmSndCyl.frmAlarmSndCfg));
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new global::System.Windows.Forms.DataGridViewCellStyle();
			global::System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new global::System.Windows.Forms.DataGridViewCellStyle();
			this.tabEnvironment = new global::System.Windows.Forms.TabControl();
			this.tabTAG = new global::System.Windows.Forms.TabPage();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.btnRemove = new global::System.Windows.Forms.Button();
			this.btnAdd = new global::System.Windows.Forms.Button();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this.gpAction = new global::System.Windows.Forms.GroupBox();
			this.gpSound = new global::System.Windows.Forms.GroupBox();
			this.Label3 = new global::System.Windows.Forms.Label();
			this.ndSecond = new global::System.Windows.Forms.NumericUpDown();
			this.txtWavName = new global::System.Windows.Forms.TextBox();
			this.btnFile = new global::System.Windows.Forms.Button();
			this.gpOutSource = new global::System.Windows.Forms.GroupBox();
			this.Label11 = new global::System.Windows.Forms.Label();
			this.Label8 = new global::System.Windows.Forms.Label();
			this.txtValue = new global::System.Windows.Forms.TextBox();
			this.txtSource = new global::System.Windows.Forms.TextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.ndLevel = new global::System.Windows.Forms.NumericUpDown();
			this.gpPicture = new global::System.Windows.Forms.GroupBox();
			this.txtPicName = new global::System.Windows.Forms.TextBox();
			this.btnPic = new global::System.Windows.Forms.Button();
			this.gpTagSource = new global::System.Windows.Forms.GroupBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.Label5 = new global::System.Windows.Forms.Label();
			this.cobPriority = new global::System.Windows.Forms.ComboBox();
			this.cobType = new global::System.Windows.Forms.ComboBox();
			this.lblType = new global::System.Windows.Forms.Label();
			this.cobArea = new global::System.Windows.Forms.ComboBox();
			this.lblArea = new global::System.Windows.Forms.Label();
			this.txtTagFilter = new global::System.Windows.Forms.TextBox();
			this.Label2 = new global::System.Windows.Forms.Label();
			this.cobNode = new global::System.Windows.Forms.ComboBox();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.lblTagList = new global::System.Windows.Forms.Label();
			this.txtNTF = new global::System.Windows.Forms.TextBox();
			this.btnEnterMode = new global::System.Windows.Forms.Button();
			this.lblDate = new global::System.Windows.Forms.Label();
			this.btnUpdate = new global::System.Windows.Forms.Button();
			this.comNTF = new global::System.Windows.Forms.ListBox();
			this.DataGrid1 = new global::System.Windows.Forms.DataGridView();
			this.ContextMenuStrip_Grid = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.miModifyAll = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miModify = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripMenuItem1 = new global::System.Windows.Forms.ToolStripSeparator();
			this.miDelAll = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miDel = new global::System.Windows.Forms.ToolStripMenuItem();
			this._dsCFG = new global::System.Data.DataSet();
			this.DataTable1 = new global::System.Data.DataTable();
			this.DataColumn1 = new global::System.Data.DataColumn();
			this.DataColumn2 = new global::System.Data.DataColumn();
			this.DataColumn3 = new global::System.Data.DataColumn();
			this.DataColumn4 = new global::System.Data.DataColumn();
			this.DataColumn5 = new global::System.Data.DataColumn();
			this.DataColumn6 = new global::System.Data.DataColumn();
			this.DataColumn7 = new global::System.Data.DataColumn();
			this.DataColumn8 = new global::System.Data.DataColumn();
			this.DataColumn9 = new global::System.Data.DataColumn();
			this.DataColumn10 = new global::System.Data.DataColumn();
			this.gpFilter = new global::System.Windows.Forms.GroupBox();
			this.txtContent = new global::System.Windows.Forms.TextBox();
			this.cobOper = new global::System.Windows.Forms.ComboBox();
			this.cobColumn = new global::System.Windows.Forms.ComboBox();
			this.btnApply = new global::System.Windows.Forms.Button();
			this.lblRecordFiltered = new global::System.Windows.Forms.Label();
			this.tabParameter = new global::System.Windows.Forms.TabPage();
			this.btnCancle = new global::System.Windows.Forms.Button();
			this.btnOK = new global::System.Windows.Forms.Button();
			this.GroupBox8 = new global::System.Windows.Forms.GroupBox();
			this.txtCfg = new global::System.Windows.Forms.TextBox();
			this.GroupBox7 = new global::System.Windows.Forms.GroupBox();
			this.ckDisBar = new global::System.Windows.Forms.CheckBox();
			this.ckBackGround = new global::System.Windows.Forms.CheckBox();
			this.GroupBox6 = new global::System.Windows.Forms.GroupBox();
			this.ndScanTime = new global::System.Windows.Forms.NumericUpDown();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.Label6 = new global::System.Windows.Forms.Label();
			this.Label7 = new global::System.Windows.Forms.Label();
			this.ndSoundTime = new global::System.Windows.Forms.NumericUpDown();
			this.Timer1 = new global::System.Windows.Forms.Timer(this.components);
			this.dlgOpen = new global::System.Windows.Forms.OpenFileDialog();
			this.tmrStatus = new global::System.Windows.Forms.Timer(this.components);
			this.dlgSave = new global::System.Windows.Forms.SaveFileDialog();
			this.panelTime = new global::System.Windows.Forms.StatusBarPanel();
			this.panelStatus = new global::System.Windows.Forms.StatusBarPanel();
			this.panelFileName = new global::System.Windows.Forms.StatusBarPanel();
			this.kvStatusBar = new global::System.Windows.Forms.StatusBar();
			this.MainMenu1 = new global::System.Windows.Forms.MenuStrip();
			this.miFile = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miNew = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miOpen = new global::System.Windows.Forms.ToolStripMenuItem();
			this.toolStripSeparator = new global::System.Windows.Forms.ToolStripSeparator();
			this.miSave = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miSaveAs = new global::System.Windows.Forms.ToolStripMenuItem();
			this.toolStripSeparator1 = new global::System.Windows.Forms.ToolStripSeparator();
			this.miRecent = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miRecent1 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miRecent2 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miRecent3 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miRecent4 = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripMenuItem2 = new global::System.Windows.Forms.ToolStripSeparator();
			this.miDelCache = new global::System.Windows.Forms.ToolStripMenuItem();
			this.toolStripSeparator2 = new global::System.Windows.Forms.ToolStripSeparator();
			this.miReloadDB = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miRun = new global::System.Windows.Forms.ToolStripMenuItem();
			this.NodeDataGridViewTextBoxColumn = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.TagDataGridViewTextBoxColumn = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.clField = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.clWave = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.clnOpenWave = new global::System.Windows.Forms.DataGridViewButtonColumn();
			this.clPriority = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.clBlockType = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.clLength = new global::System.Windows.Forms.DataGridViewComboBoxColumn();
			this.clPicture = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.clnOpenPic = new global::System.Windows.Forms.DataGridViewButtonColumn();
			this.clOutSource = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.clOutValue = new global::System.Windows.Forms.DataGridViewTextBoxColumn();
			this.tabEnvironment.SuspendLayout();
			this.tabTAG.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			this.gpAction.SuspendLayout();
			this.gpSound.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.ndSecond).BeginInit();
			this.gpOutSource.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.ndLevel).BeginInit();
			this.gpPicture.SuspendLayout();
			this.gpTagSource.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGrid1).BeginInit();
			this.ContextMenuStrip_Grid.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this._dsCFG).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataTable1).BeginInit();
			this.gpFilter.SuspendLayout();
			this.tabParameter.SuspendLayout();
			this.GroupBox8.SuspendLayout();
			this.GroupBox7.SuspendLayout();
			this.GroupBox6.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.ndScanTime).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.ndSoundTime).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.panelTime).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.panelStatus).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.panelFileName).BeginInit();
			this.MainMenu1.SuspendLayout();
			this.SuspendLayout();
			this.tabEnvironment.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.tabEnvironment.Controls.Add(this.tabTAG);
			this.tabEnvironment.Controls.Add(this.tabParameter);
			this.tabEnvironment.Font = new global::System.Drawing.Font("微軟正黑體", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control tabEnvironment = this.tabEnvironment;
			global::System.Drawing.Point point = new global::System.Drawing.Point(6, 27);
			tabEnvironment.Location = point;
			this.tabEnvironment.Name = "tabEnvironment";
			this.tabEnvironment.SelectedIndex = 0;
			global::System.Windows.Forms.Control tabEnvironment2 = this.tabEnvironment;
			global::System.Drawing.Size size = new global::System.Drawing.Size(687, 557);
			tabEnvironment2.Size = size;
			this.tabEnvironment.TabIndex = 0;
			this.tabTAG.BackColor = global::System.Drawing.SystemColors.Control;
			this.tabTAG.Controls.Add(this.GroupBox1);
			this.tabTAG.Controls.Add(this.GroupBox4);
			this.tabTAG.Controls.Add(this.DataGrid1);
			this.tabTAG.Controls.Add(this.gpFilter);
			this.tabTAG.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.TabPage tabTAG = this.tabTAG;
			point = new global::System.Drawing.Point(4, 24);
			tabTAG.Location = point;
			this.tabTAG.Name = "tabTAG";
			global::System.Windows.Forms.Control tabTAG2 = this.tabTAG;
			global::System.Windows.Forms.Padding padding = new global::System.Windows.Forms.Padding(3);
			tabTAG2.Padding = padding;
			global::System.Windows.Forms.Control tabTAG3 = this.tabTAG;
			size = new global::System.Drawing.Size(679, 529);
			tabTAG3.Size = size;
			this.tabTAG.TabIndex = 0;
			this.tabTAG.Text = "Tag定義";
			this.GroupBox1.Controls.Add(this.btnRemove);
			this.GroupBox1.Controls.Add(this.btnAdd);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			point = new global::System.Drawing.Point(10, 352);
			groupBox.Location = point;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new global::System.Drawing.Size(155, 45);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 237;
			this.GroupBox1.TabStop = false;
			this.btnRemove.AutoSize = true;
			this.btnRemove.Font = new global::System.Drawing.Font("微軟正黑體", 9f);
			global::System.Windows.Forms.Control btnRemove = this.btnRemove;
			point = new global::System.Drawing.Point(82, 14);
			btnRemove.Location = point;
			this.btnRemove.Name = "btnRemove";
			global::System.Windows.Forms.Control btnRemove2 = this.btnRemove;
			size = new global::System.Drawing.Size(56, 26);
			btnRemove2.Size = size;
			this.btnRemove.TabIndex = 238;
			this.btnRemove.Text = "移除";
			this.btnAdd.AutoSize = true;
			this.btnAdd.Font = new global::System.Drawing.Font("微軟正黑體", 9f);
			global::System.Windows.Forms.Control btnAdd = this.btnAdd;
			point = new global::System.Drawing.Point(17, 14);
			btnAdd.Location = point;
			this.btnAdd.Name = "btnAdd";
			global::System.Windows.Forms.Control btnAdd2 = this.btnAdd;
			size = new global::System.Drawing.Size(56, 26);
			btnAdd2.Size = size;
			this.btnAdd.TabIndex = 237;
			this.btnAdd.Text = "新增";
			this.GroupBox4.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.GroupBox4.Controls.Add(this.gpAction);
			this.GroupBox4.Controls.Add(this.gpTagSource);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox4;
			point = new global::System.Drawing.Point(10, 7);
			groupBox3.Location = point;
			this.GroupBox4.Name = "GroupBox4";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox4;
			size = new global::System.Drawing.Size(659, 336);
			groupBox4.Size = size;
			this.GroupBox4.TabIndex = 234;
			this.GroupBox4.TabStop = false;
			this.gpAction.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.gpAction.Controls.Add(this.gpSound);
			this.gpAction.Controls.Add(this.gpOutSource);
			this.gpAction.Controls.Add(this.Label4);
			this.gpAction.Controls.Add(this.ndLevel);
			this.gpAction.Controls.Add(this.gpPicture);
			this.gpAction.Font = new global::System.Drawing.Font("微軟正黑體", 9f);
			global::System.Windows.Forms.Control gpAction = this.gpAction;
			point = new global::System.Drawing.Point(294, 18);
			gpAction.Location = point;
			this.gpAction.Name = "gpAction";
			global::System.Windows.Forms.Control gpAction2 = this.gpAction;
			size = new global::System.Drawing.Size(358, 308);
			gpAction2.Size = size;
			this.gpAction.TabIndex = 228;
			this.gpAction.TabStop = false;
			this.gpAction.Text = "動作";
			this.gpSound.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.gpSound.Controls.Add(this.Label3);
			this.gpSound.Controls.Add(this.ndSecond);
			this.gpSound.Controls.Add(this.txtWavName);
			this.gpSound.Controls.Add(this.btnFile);
			global::System.Windows.Forms.Control gpSound = this.gpSound;
			point = new global::System.Drawing.Point(6, 20);
			gpSound.Location = point;
			this.gpSound.Name = "gpSound";
			global::System.Windows.Forms.Control gpSound2 = this.gpSound;
			size = new global::System.Drawing.Size(338, 76);
			gpSound2.Size = size;
			this.gpSound.TabIndex = 225;
			this.gpSound.TabStop = false;
			this.gpSound.Text = "聲音";
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("微軟正黑體", 9f);
			global::System.Windows.Forms.Control label = this.Label3;
			point = new global::System.Drawing.Point(6, 52);
			label.Location = point;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label2 = this.Label3;
			size = new global::System.Drawing.Size(56, 16);
			label2.Size = size;
			this.Label3.TabIndex = 227;
			this.Label3.Text = "聲音秒數";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.ndSecond.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control ndSecond = this.ndSecond;
			point = new global::System.Drawing.Point(63, 50);
			ndSecond.Location = point;
			global::System.Windows.Forms.NumericUpDown ndSecond2 = this.ndSecond;
			decimal num = new decimal(new int[] { 30, 0, 0, 0 });
			ndSecond2.Maximum = num;
			this.ndSecond.Name = "ndSecond";
			global::System.Windows.Forms.Control ndSecond3 = this.ndSecond;
			size = new global::System.Drawing.Size(32, 20);
			ndSecond3.Size = size;
			this.ndSecond.TabIndex = 226;
			this.ndSecond.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.txtWavName.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.txtWavName.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtWavName = this.txtWavName;
			point = new global::System.Drawing.Point(35, 19);
			txtWavName.Location = point;
			this.txtWavName.Name = "txtWavName";
			global::System.Windows.Forms.Control txtWavName2 = this.txtWavName;
			size = new global::System.Drawing.Size(291, 20);
			txtWavName2.Size = size;
			this.txtWavName.TabIndex = 213;
			this.btnFile.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnFile.Image");
			global::System.Windows.Forms.Control btnFile = this.btnFile;
			point = new global::System.Drawing.Point(6, 19);
			btnFile.Location = point;
			this.btnFile.Name = "btnFile";
			global::System.Windows.Forms.Control btnFile2 = this.btnFile;
			size = new global::System.Drawing.Size(28, 20);
			btnFile2.Size = size;
			this.btnFile.TabIndex = 214;
			this.gpOutSource.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.gpOutSource.Controls.Add(this.Label11);
			this.gpOutSource.Controls.Add(this.Label8);
			this.gpOutSource.Controls.Add(this.txtValue);
			this.gpOutSource.Controls.Add(this.txtSource);
			global::System.Windows.Forms.Control gpOutSource = this.gpOutSource;
			point = new global::System.Drawing.Point(6, 160);
			gpOutSource.Location = point;
			this.gpOutSource.Name = "gpOutSource";
			global::System.Windows.Forms.Control gpOutSource2 = this.gpOutSource;
			size = new global::System.Drawing.Size(338, 74);
			gpOutSource2.Size = size;
			this.gpOutSource.TabIndex = 227;
			this.gpOutSource.TabStop = false;
			this.gpOutSource.Tag = "暫時保留";
			this.gpOutSource.Text = "輸出";
			this.gpOutSource.Visible = false;
			this.Label11.Font = new global::System.Drawing.Font("微軟正黑體", 9f);
			global::System.Windows.Forms.Control label3 = this.Label11;
			point = new global::System.Drawing.Point(2, 49);
			label3.Location = point;
			this.Label11.Name = "Label11";
			global::System.Windows.Forms.Control label4 = this.Label11;
			size = new global::System.Drawing.Size(70, 16);
			label4.Size = size;
			this.Label11.TabIndex = 229;
			this.Label11.Text = "值";
			this.Label11.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label8.Font = new global::System.Drawing.Font("微軟正黑體", 9f);
			global::System.Windows.Forms.Control label5 = this.Label8;
			point = new global::System.Drawing.Point(2, 22);
			label5.Location = point;
			this.Label8.Name = "Label8";
			global::System.Windows.Forms.Control label6 = this.Label8;
			size = new global::System.Drawing.Size(70, 16);
			label6.Size = size;
			this.Label8.TabIndex = 228;
			this.Label8.Text = "資料來源";
			this.Label8.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.txtValue.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.txtValue.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtValue = this.txtValue;
			point = new global::System.Drawing.Point(78, 47);
			txtValue.Location = point;
			this.txtValue.Name = "txtValue";
			global::System.Windows.Forms.Control txtValue2 = this.txtValue;
			size = new global::System.Drawing.Size(248, 20);
			txtValue2.Size = size;
			this.txtValue.TabIndex = 214;
			this.txtSource.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.txtSource.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtSource = this.txtSource;
			point = new global::System.Drawing.Point(78, 19);
			txtSource.Location = point;
			this.txtSource.Name = "txtSource";
			global::System.Windows.Forms.Control txtSource2 = this.txtSource;
			size = new global::System.Drawing.Size(248, 20);
			txtSource2.Size = size;
			this.txtSource.TabIndex = 213;
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("微軟正黑體", 9f);
			global::System.Windows.Forms.Control label7 = this.Label4;
			point = new global::System.Drawing.Point(9, 255);
			label7.Location = point;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label8 = this.Label4;
			size = new global::System.Drawing.Size(80, 16);
			label8.Size = size;
			this.Label4.TabIndex = 210;
			this.Label4.Text = "優先順序等級";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.ndLevel.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control ndLevel = this.ndLevel;
			point = new global::System.Drawing.Point(91, 252);
			ndLevel.Location = point;
			global::System.Windows.Forms.NumericUpDown ndLevel2 = this.ndLevel;
			num = new decimal(new int[] { 2, 0, 0, 0 });
			ndLevel2.Maximum = num;
			this.ndLevel.Name = "ndLevel";
			global::System.Windows.Forms.Control ndLevel3 = this.ndLevel;
			size = new global::System.Drawing.Size(32, 20);
			ndLevel3.Size = size;
			this.ndLevel.TabIndex = 208;
			this.ndLevel.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			global::System.Windows.Forms.NumericUpDown ndLevel4 = this.ndLevel;
			num = new decimal(new int[] { 2, 0, 0, 0 });
			ndLevel4.Value = num;
			this.gpPicture.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.gpPicture.Controls.Add(this.txtPicName);
			this.gpPicture.Controls.Add(this.btnPic);
			global::System.Windows.Forms.Control gpPicture = this.gpPicture;
			point = new global::System.Drawing.Point(6, 102);
			gpPicture.Location = point;
			this.gpPicture.Name = "gpPicture";
			global::System.Windows.Forms.Control gpPicture2 = this.gpPicture;
			size = new global::System.Drawing.Size(338, 52);
			gpPicture2.Size = size;
			this.gpPicture.TabIndex = 226;
			this.gpPicture.TabStop = false;
			this.gpPicture.Text = "開啟圖片";
			this.txtPicName.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.txtPicName.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtPicName = this.txtPicName;
			point = new global::System.Drawing.Point(35, 25);
			txtPicName.Location = point;
			this.txtPicName.Name = "txtPicName";
			global::System.Windows.Forms.Control txtPicName2 = this.txtPicName;
			size = new global::System.Drawing.Size(291, 20);
			txtPicName2.Size = size;
			this.txtPicName.TabIndex = 213;
			this.btnPic.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("btnPic.Image");
			global::System.Windows.Forms.Control btnPic = this.btnPic;
			point = new global::System.Drawing.Point(6, 25);
			btnPic.Location = point;
			this.btnPic.Name = "btnPic";
			global::System.Windows.Forms.Control btnPic2 = this.btnPic;
			size = new global::System.Drawing.Size(28, 20);
			btnPic2.Size = size;
			this.btnPic.TabIndex = 214;
			this.gpTagSource.Controls.Add(this.GroupBox2);
			this.gpTagSource.Controls.Add(this.lblTagList);
			this.gpTagSource.Controls.Add(this.txtNTF);
			this.gpTagSource.Controls.Add(this.btnEnterMode);
			this.gpTagSource.Controls.Add(this.lblDate);
			this.gpTagSource.Controls.Add(this.btnUpdate);
			this.gpTagSource.Controls.Add(this.comNTF);
			global::System.Windows.Forms.Control gpTagSource = this.gpTagSource;
			point = new global::System.Drawing.Point(8, 9);
			gpTagSource.Location = point;
			this.gpTagSource.Name = "gpTagSource";
			global::System.Windows.Forms.Control gpTagSource2 = this.gpTagSource;
			size = new global::System.Drawing.Size(270, 318);
			gpTagSource2.Size = size;
			this.gpTagSource.TabIndex = 223;
			this.gpTagSource.TabStop = false;
			this.GroupBox2.Controls.Add(this.Label5);
			this.GroupBox2.Controls.Add(this.cobPriority);
			this.GroupBox2.Controls.Add(this.cobType);
			this.GroupBox2.Controls.Add(this.lblType);
			this.GroupBox2.Controls.Add(this.cobArea);
			this.GroupBox2.Controls.Add(this.lblArea);
			this.GroupBox2.Controls.Add(this.txtTagFilter);
			this.GroupBox2.Controls.Add(this.Label2);
			this.GroupBox2.Controls.Add(this.cobNode);
			this.GroupBox2.Controls.Add(this.Label1);
			this.GroupBox2.Font = new global::System.Drawing.Font("微軟正黑體", 8.25f);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox2;
			point = new global::System.Drawing.Point(6, 11);
			groupBox5.Location = point;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox2;
			size = new global::System.Drawing.Size(258, 134);
			groupBox6.Size = size;
			this.GroupBox2.TabIndex = 217;
			this.GroupBox2.TabStop = false;
			this.GroupBox2.Text = "篩選條件";
			this.Label5.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left;
			this.Label5.Font = new global::System.Drawing.Font("微軟正黑體", 9f);
			global::System.Windows.Forms.Control label9 = this.Label5;
			point = new global::System.Drawing.Point(28, 106);
			label9.Location = point;
			this.Label5.Name = "Label5";
			global::System.Windows.Forms.Control label10 = this.Label5;
			size = new global::System.Drawing.Size(70, 16);
			label10.Size = size;
			this.Label5.TabIndex = 227;
			this.Label5.Text = "警報等級";
			this.Label5.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.cobPriority.Anchor = global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left;
			this.cobPriority.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cobPriority.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.cobPriority.Items.AddRange(new object[] { "NOPRI", "CRITICAL", "HIHI", "HIGH", "MEDIUM", "LOW", "LOLO", "INFO" });
			global::System.Windows.Forms.Control cobPriority = this.cobPriority;
			point = new global::System.Drawing.Point(105, 103);
			cobPriority.Location = point;
			this.cobPriority.Name = "cobPriority";
			global::System.Windows.Forms.Control cobPriority2 = this.cobPriority;
			size = new global::System.Drawing.Size(147, 22);
			cobPriority2.Size = size;
			this.cobPriority.TabIndex = 226;
			this.cobPriority.Tag = "0";
			this.cobType.Enabled = false;
			this.cobType.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.cobType.Items.AddRange(new object[] { "AA", "AI", "AIS", "DA", "DI" });
			global::System.Windows.Forms.Control cobType = this.cobType;
			point = new global::System.Drawing.Point(8, 72);
			cobType.Location = point;
			this.cobType.Name = "cobType";
			global::System.Windows.Forms.Control cobType2 = this.cobType;
			size = new global::System.Drawing.Size(92, 22);
			cobType2.Size = size;
			this.cobType.TabIndex = 59;
			this.cobType.Tag = "0";
			this.lblType.AutoSize = true;
			this.lblType.Font = new global::System.Drawing.Font("微軟正黑體", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 136);
			global::System.Windows.Forms.Control lblType = this.lblType;
			point = new global::System.Drawing.Point(8, 57);
			lblType.Location = point;
			this.lblType.Name = "lblType";
			global::System.Windows.Forms.Control lblType2 = this.lblType;
			size = new global::System.Drawing.Size(61, 16);
			lblType2.Size = size;
			this.lblType.TabIndex = 58;
			this.lblType.Text = "Tag Type";
			this.lblType.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.cobArea.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cobArea.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.cobArea.Items.AddRange(new object[] { "警報區域", "Tag" });
			global::System.Windows.Forms.Control cobArea = this.cobArea;
			point = new global::System.Drawing.Point(108, 29);
			cobArea.Location = point;
			this.cobArea.Name = "cobArea";
			global::System.Windows.Forms.Control cobArea2 = this.cobArea;
			size = new global::System.Drawing.Size(144, 22);
			cobArea2.Size = size;
			this.cobArea.TabIndex = 57;
			this.cobArea.Tag = "0";
			this.lblArea.AutoSize = true;
			this.lblArea.Font = new global::System.Drawing.Font("微軟正黑體", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 136);
			global::System.Windows.Forms.Control lblArea = this.lblArea;
			point = new global::System.Drawing.Point(110, 14);
			lblArea.Location = point;
			this.lblArea.Name = "lblArea";
			global::System.Windows.Forms.Control lblArea2 = this.lblArea;
			size = new global::System.Drawing.Size(80, 16);
			lblArea2.Size = size;
			this.lblArea.TabIndex = 56;
			this.lblArea.Text = "觸發來源類別";
			this.lblArea.TextAlign = global::System.Drawing.ContentAlignment.BottomLeft;
			this.txtTagFilter.Font = new global::System.Drawing.Font("Arial", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtTagFilter = this.txtTagFilter;
			point = new global::System.Drawing.Point(105, 73);
			txtTagFilter.Location = point;
			this.txtTagFilter.Name = "txtTagFilter";
			global::System.Windows.Forms.Control txtTagFilter2 = this.txtTagFilter;
			size = new global::System.Drawing.Size(147, 21);
			txtTagFilter2.Size = size;
			this.txtTagFilter.TabIndex = 55;
			this.Label2.AutoSize = true;
			this.Label2.Font = new global::System.Drawing.Font("微軟正黑體", 9f);
			global::System.Windows.Forms.Control label11 = this.Label2;
			point = new global::System.Drawing.Point(105, 57);
			label11.Location = point;
			this.Label2.Name = "Label2";
			global::System.Windows.Forms.Control label12 = this.Label2;
			size = new global::System.Drawing.Size(141, 16);
			label12.Size = size;
			this.Label2.TabIndex = 54;
			this.Label2.Text = "TagName (可使用*字元)";
			this.Label2.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.cobNode.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cobNode.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control cobNode = this.cobNode;
			point = new global::System.Drawing.Point(8, 29);
			cobNode.Location = point;
			this.cobNode.Name = "cobNode";
			global::System.Windows.Forms.Control cobNode2 = this.cobNode;
			size = new global::System.Drawing.Size(92, 22);
			cobNode2.Size = size;
			this.cobNode.TabIndex = 53;
			this.cobNode.Tag = "0";
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("微軟正黑體", 8.25f);
			global::System.Windows.Forms.Control label13 = this.Label1;
			point = new global::System.Drawing.Point(8, 14);
			label13.Location = point;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label14 = this.Label1;
			size = new global::System.Drawing.Size(70, 15);
			label14.Size = size;
			this.Label1.TabIndex = 52;
			this.Label1.Text = "Node Name";
			this.Label1.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.lblTagList.Font = new global::System.Drawing.Font("微軟正黑體", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 136);
			global::System.Windows.Forms.Control lblTagList = this.lblTagList;
			point = new global::System.Drawing.Point(5, 154);
			lblTagList.Location = point;
			this.lblTagList.Name = "lblTagList";
			global::System.Windows.Forms.Control lblTagList2 = this.lblTagList;
			size = new global::System.Drawing.Size(142, 16);
			lblTagList2.Size = size;
			this.lblTagList.TabIndex = 216;
			this.lblTagList.Text = "警報區域";
			this.lblTagList.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.txtNTF.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtNTF = this.txtNTF;
			point = new global::System.Drawing.Point(6, 172);
			txtNTF.Location = point;
			this.txtNTF.MaxLength = 39;
			this.txtNTF.Name = "txtNTF";
			global::System.Windows.Forms.Control txtNTF2 = this.txtNTF;
			size = new global::System.Drawing.Size(258, 20);
			txtNTF2.Size = size;
			this.txtNTF.TabIndex = 222;
			this.txtNTF.Text = "TagName";
			this.txtNTF.Visible = false;
			this.btnEnterMode.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnEnterMode.Font = new global::System.Drawing.Font("微軟正黑體", 8.25f);
			this.btnEnterMode.ForeColor = global::System.Drawing.Color.Black;
			global::System.Windows.Forms.Control btnEnterMode = this.btnEnterMode;
			point = new global::System.Drawing.Point(162, 154);
			btnEnterMode.Location = point;
			this.btnEnterMode.Name = "btnEnterMode";
			global::System.Windows.Forms.Control btnEnterMode2 = this.btnEnterMode;
			size = new global::System.Drawing.Size(102, 20);
			btnEnterMode2.Size = size;
			this.btnEnterMode.TabIndex = 221;
			this.btnEnterMode.Tag = "手動輸入或選取下列清單";
			this.btnEnterMode.Text = "改用手動輸入";
			this.btnEnterMode.UseVisualStyleBackColor = false;
			this.lblDate.Font = new global::System.Drawing.Font("新細明體", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 136);
			this.lblDate.ForeColor = global::System.Drawing.SystemColors.ControlDark;
			global::System.Windows.Forms.Control lblDate = this.lblDate;
			point = new global::System.Drawing.Point(92, 299);
			lblDate.Location = point;
			this.lblDate.Name = "lblDate";
			global::System.Windows.Forms.Control lblDate2 = this.lblDate;
			size = new global::System.Drawing.Size(170, 12);
			lblDate2.Size = size;
			this.lblDate.TabIndex = 219;
			this.lblDate.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.btnUpdate.BackColor = global::System.Drawing.SystemColors.Control;
			this.btnUpdate.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.btnUpdate.ForeColor = global::System.Drawing.Color.RosyBrown;
			global::System.Windows.Forms.Control btnUpdate = this.btnUpdate;
			point = new global::System.Drawing.Point(2, 295);
			btnUpdate.Location = point;
			this.btnUpdate.Name = "btnUpdate";
			global::System.Windows.Forms.Control btnUpdate2 = this.btnUpdate;
			size = new global::System.Drawing.Size(82, 20);
			btnUpdate2.Size = size;
			this.btnUpdate.TabIndex = 218;
			this.btnUpdate.Text = "更新Tag快取";
			this.btnUpdate.UseVisualStyleBackColor = false;
			this.comNTF.Font = new global::System.Drawing.Font("MS Gothic", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.comNTF.ItemHeight = 12;
			global::System.Windows.Forms.Control comNTF = this.comNTF;
			point = new global::System.Drawing.Point(5, 172);
			comNTF.Location = point;
			this.comNTF.Name = "comNTF";
			this.comNTF.SelectionMode = global::System.Windows.Forms.SelectionMode.MultiExtended;
			global::System.Windows.Forms.Control comNTF2 = this.comNTF;
			size = new global::System.Drawing.Size(259, 124);
			comNTF2.Size = size;
			this.comNTF.TabIndex = 220;
			this.DataGrid1.AllowUserToAddRows = false;
			this.DataGrid1.AllowUserToResizeRows = false;
			dataGridViewCellStyle.BackColor = global::System.Drawing.Color.Honeydew;
			dataGridViewCellStyle.ForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle.SelectionBackColor = global::System.Drawing.Color.MistyRose;
			dataGridViewCellStyle.SelectionForeColor = global::System.Drawing.Color.Black;
			this.DataGrid1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle;
			this.DataGrid1.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.DataGrid1.AutoGenerateColumns = false;
			dataGridViewCellStyle2.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
			dataGridViewCellStyle2.BackColor = global::System.Drawing.SystemColors.Control;
			dataGridViewCellStyle2.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle2.ForeColor = global::System.Drawing.SystemColors.WindowText;
			dataGridViewCellStyle2.SelectionBackColor = global::System.Drawing.SystemColors.Highlight;
			dataGridViewCellStyle2.SelectionForeColor = global::System.Drawing.SystemColors.HighlightText;
			dataGridViewCellStyle2.WrapMode = global::System.Windows.Forms.DataGridViewTriState.True;
			this.DataGrid1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
			this.DataGrid1.ColumnHeadersHeight = 22;
			this.DataGrid1.ColumnHeadersHeightSizeMode = global::System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
			this.DataGrid1.Columns.AddRange(new global::System.Windows.Forms.DataGridViewColumn[]
			{
				this.NodeDataGridViewTextBoxColumn, this.TagDataGridViewTextBoxColumn, this.clField, this.clWave, this.clnOpenWave, this.clPriority, this.clBlockType, this.clLength, this.clPicture, this.clnOpenPic,
				this.clOutSource, this.clOutValue
			});
			this.DataGrid1.ContextMenuStrip = this.ContextMenuStrip_Grid;
			this.DataGrid1.DataMember = "Config";
			this.DataGrid1.DataSource = this._dsCFG;
			dataGridViewCellStyle3.Alignment = global::System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
			dataGridViewCellStyle3.BackColor = global::System.Drawing.SystemColors.Window;
			dataGridViewCellStyle3.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			dataGridViewCellStyle3.ForeColor = global::System.Drawing.Color.Blue;
			dataGridViewCellStyle3.SelectionBackColor = global::System.Drawing.Color.MistyRose;
			dataGridViewCellStyle3.SelectionForeColor = global::System.Drawing.Color.Black;
			dataGridViewCellStyle3.WrapMode = global::System.Windows.Forms.DataGridViewTriState.False;
			this.DataGrid1.DefaultCellStyle = dataGridViewCellStyle3;
			global::System.Windows.Forms.Control dataGrid = this.DataGrid1;
			point = new global::System.Drawing.Point(10, 403);
			dataGrid.Location = point;
			this.DataGrid1.Name = "DataGrid1";
			this.DataGrid1.RowHeadersWidth = 20;
			this.DataGrid1.RowHeadersWidthSizeMode = global::System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
			this.DataGrid1.RowTemplate.Height = 20;
			global::System.Windows.Forms.Control dataGrid2 = this.DataGrid1;
			size = new global::System.Drawing.Size(652, 120);
			dataGrid2.Size = size;
			this.DataGrid1.TabIndex = 235;
			this.ContextMenuStrip_Grid.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.miModifyAll, this.miModify, this.ToolStripMenuItem1, this.miDelAll, this.miDel });
			this.ContextMenuStrip_Grid.Name = "ContextMenuStrip_Grid";
			this.ContextMenuStrip_Grid.ShowImageMargin = false;
			this.ContextMenuStrip_Grid.ShowItemToolTips = false;
			global::System.Windows.Forms.Control contextMenuStrip_Grid = this.ContextMenuStrip_Grid;
			size = new global::System.Drawing.Size(117, 98);
			contextMenuStrip_Grid.Size = size;
			this.miModifyAll.Name = "miModifyAll";
			global::System.Windows.Forms.ToolStripItem miModifyAll = this.miModifyAll;
			size = new global::System.Drawing.Size(116, 22);
			miModifyAll.Size = size;
			this.miModifyAll.Text = "修改全部";
			this.miModify.Name = "miModify";
			global::System.Windows.Forms.ToolStripItem miModify = this.miModify;
			size = new global::System.Drawing.Size(116, 22);
			miModify.Size = size;
			this.miModify.Text = "修改選取tag";
			this.ToolStripMenuItem1.Name = "ToolStripMenuItem1";
			global::System.Windows.Forms.ToolStripItem toolStripMenuItem = this.ToolStripMenuItem1;
			size = new global::System.Drawing.Size(113, 6);
			toolStripMenuItem.Size = size;
			this.miDelAll.Name = "miDelAll";
			global::System.Windows.Forms.ToolStripItem miDelAll = this.miDelAll;
			size = new global::System.Drawing.Size(116, 22);
			miDelAll.Size = size;
			this.miDelAll.Text = "刪除全部";
			this.miDel.Name = "miDel";
			global::System.Windows.Forms.ToolStripItem miDel = this.miDel;
			size = new global::System.Drawing.Size(116, 22);
			miDel.Size = size;
			this.miDel.Text = "刪除選取tag";
			this._dsCFG.DataSetName = "DataSet1";
			this._dsCFG.Tables.AddRange(new global::System.Data.DataTable[] { this.DataTable1 });
			this.DataTable1.Columns.AddRange(new global::System.Data.DataColumn[] { this.DataColumn1, this.DataColumn2, this.DataColumn3, this.DataColumn4, this.DataColumn5, this.DataColumn6, this.DataColumn7, this.DataColumn8, this.DataColumn9, this.DataColumn10 });
			this.DataTable1.Constraints.AddRange(new global::System.Data.Constraint[]
			{
				new global::System.Data.UniqueConstraint("Constraint1", new string[] { "Field", "Node", "Tag" }, false)
			});
			this.DataTable1.TableName = "Config";
			this.DataColumn1.AllowDBNull = false;
			this.DataColumn1.Caption = "Node";
			this.DataColumn1.ColumnName = "Node";
			this.DataColumn1.MaxLength = 8;
			this.DataColumn2.AllowDBNull = false;
			this.DataColumn2.Caption = "Tag";
			this.DataColumn2.ColumnName = "Tag";
			this.DataColumn2.MaxLength = 30;
			this.DataColumn3.AllowDBNull = false;
			this.DataColumn3.Caption = "Wave檔名";
			this.DataColumn3.ColumnName = "Wave";
			this.DataColumn3.MaxLength = 255;
			this.DataColumn4.AllowDBNull = false;
			this.DataColumn4.Caption = "優先順序";
			this.DataColumn4.ColumnName = "Priority";
			this.DataColumn4.DefaultValue = "2";
			this.DataColumn4.MaxLength = 1;
			this.DataColumn5.AllowDBNull = false;
			this.DataColumn5.Caption = "BlockType";
			this.DataColumn5.ColumnName = "BlockType";
			this.DataColumn5.DataType = typeof(short);
			this.DataColumn5.DefaultValue = 0;
			this.DataColumn6.Caption = "Length";
			this.DataColumn6.ColumnName = "Length";
			this.DataColumn6.DefaultValue = "0";
			this.DataColumn6.MaxLength = 2;
			this.DataColumn7.Caption = "Field";
			this.DataColumn7.ColumnName = "Field";
			this.DataColumn7.DefaultValue = "";
			this.DataColumn7.MaxLength = 32;
			this.DataColumn8.Caption = "iFix Picture";
			this.DataColumn8.ColumnName = "Picture";
			this.DataColumn8.DefaultValue = "";
			this.DataColumn9.Caption = "Output Source";
			this.DataColumn9.ColumnName = "OutSource";
			this.DataColumn9.DefaultValue = "";
			this.DataColumn10.Caption = "Output Value";
			this.DataColumn10.ColumnName = "OutValue";
			this.DataColumn10.DefaultValue = "";
			this.gpFilter.Controls.Add(this.txtContent);
			this.gpFilter.Controls.Add(this.cobOper);
			this.gpFilter.Controls.Add(this.cobColumn);
			this.gpFilter.Controls.Add(this.btnApply);
			this.gpFilter.Controls.Add(this.lblRecordFiltered);
			this.gpFilter.Font = new global::System.Drawing.Font("微軟正黑體", 9f);
			global::System.Windows.Forms.Control gpFilter = this.gpFilter;
			point = new global::System.Drawing.Point(191, 351);
			gpFilter.Location = point;
			this.gpFilter.Name = "gpFilter";
			global::System.Windows.Forms.Control gpFilter2 = this.gpFilter;
			size = new global::System.Drawing.Size(496, 46);
			gpFilter2.Size = size;
			this.gpFilter.TabIndex = 236;
			this.gpFilter.TabStop = false;
			this.gpFilter.Text = " 資料顯示篩選";
			this.txtContent.Font = new global::System.Drawing.Font("Arial", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtContent = this.txtContent;
			point = new global::System.Drawing.Point(146, 18);
			txtContent.Location = point;
			this.txtContent.Name = "txtContent";
			global::System.Windows.Forms.Control txtContent2 = this.txtContent;
			size = new global::System.Drawing.Size(144, 21);
			txtContent2.Size = size;
			this.txtContent.TabIndex = 57;
			this.cobOper.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cobOper.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.cobOper.Items.AddRange(new object[] { "LIKE", "=", "<>" });
			global::System.Windows.Forms.Control cobOper = this.cobOper;
			point = new global::System.Drawing.Point(96, 18);
			cobOper.Location = point;
			this.cobOper.Name = "cobOper";
			global::System.Windows.Forms.Control cobOper2 = this.cobOper;
			size = new global::System.Drawing.Size(48, 22);
			cobOper2.Size = size;
			this.cobOper.TabIndex = 56;
			this.cobColumn.DropDownStyle = global::System.Windows.Forms.ComboBoxStyle.DropDownList;
			this.cobColumn.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.cobColumn.Items.AddRange(new object[] { "Node", "Tag", "Wave", "優先順序" });
			global::System.Windows.Forms.Control cobColumn = this.cobColumn;
			point = new global::System.Drawing.Point(6, 18);
			cobColumn.Location = point;
			this.cobColumn.Name = "cobColumn";
			global::System.Windows.Forms.Control cobColumn2 = this.cobColumn;
			size = new global::System.Drawing.Size(88, 22);
			cobColumn2.Size = size;
			this.cobColumn.TabIndex = 55;
			this.btnApply.AutoSize = true;
			global::System.Windows.Forms.Control btnApply = this.btnApply;
			point = new global::System.Drawing.Point(292, 15);
			btnApply.Location = point;
			this.btnApply.Name = "btnApply";
			global::System.Windows.Forms.Control btnApply2 = this.btnApply;
			size = new global::System.Drawing.Size(44, 26);
			btnApply2.Size = size;
			this.btnApply.TabIndex = 57;
			this.btnApply.Text = "套用";
			this.lblRecordFiltered.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Right;
			this.lblRecordFiltered.AutoSize = true;
			this.lblRecordFiltered.Font = new global::System.Drawing.Font("微軟正黑體", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 136);
			this.lblRecordFiltered.ForeColor = global::System.Drawing.Color.LightSlateGray;
			global::System.Windows.Forms.Control lblRecordFiltered = this.lblRecordFiltered;
			point = new global::System.Drawing.Point(317, 21);
			lblRecordFiltered.Location = point;
			this.lblRecordFiltered.Name = "lblRecordFiltered";
			global::System.Windows.Forms.Control lblRecordFiltered2 = this.lblRecordFiltered;
			size = new global::System.Drawing.Size(124, 15);
			lblRecordFiltered2.Size = size;
			this.lblRecordFiltered.TabIndex = 59;
			this.lblRecordFiltered.Text = "總共0筆, 篩選後剩下0筆";
			this.lblRecordFiltered.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.tabParameter.BackColor = global::System.Drawing.SystemColors.Control;
			this.tabParameter.Controls.Add(this.btnCancle);
			this.tabParameter.Controls.Add(this.btnOK);
			this.tabParameter.Controls.Add(this.GroupBox8);
			this.tabParameter.Controls.Add(this.GroupBox7);
			this.tabParameter.Controls.Add(this.GroupBox6);
			global::System.Windows.Forms.TabPage tabParameter = this.tabParameter;
			point = new global::System.Drawing.Point(4, 24);
			tabParameter.Location = point;
			this.tabParameter.Name = "tabParameter";
			global::System.Windows.Forms.Control tabParameter2 = this.tabParameter;
			padding = new global::System.Windows.Forms.Padding(3);
			tabParameter2.Padding = padding;
			global::System.Windows.Forms.Control tabParameter3 = this.tabParameter;
			size = new global::System.Drawing.Size(679, 529);
			tabParameter3.Size = size;
			this.tabParameter.TabIndex = 1;
			this.tabParameter.Text = "環境參數";
			global::System.Windows.Forms.Control btnCancle = this.btnCancle;
			point = new global::System.Drawing.Point(639, 388);
			btnCancle.Location = point;
			this.btnCancle.Name = "btnCancle";
			global::System.Windows.Forms.Control btnCancle2 = this.btnCancle;
			size = new global::System.Drawing.Size(75, 23);
			btnCancle2.Size = size;
			this.btnCancle.TabIndex = 238;
			this.btnCancle.Text = "取消";
			this.btnCancle.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control btnOK = this.btnOK;
			point = new global::System.Drawing.Point(558, 388);
			btnOK.Location = point;
			this.btnOK.Name = "btnOK";
			global::System.Windows.Forms.Control btnOK2 = this.btnOK;
			size = new global::System.Drawing.Size(75, 23);
			btnOK2.Size = size;
			this.btnOK.TabIndex = 237;
			this.btnOK.Text = "確定";
			this.btnOK.UseVisualStyleBackColor = true;
			this.GroupBox8.Controls.Add(this.txtCfg);
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox8;
			point = new global::System.Drawing.Point(17, 15);
			groupBox7.Location = point;
			this.GroupBox8.Name = "GroupBox8";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox8;
			size = new global::System.Drawing.Size(697, 54);
			groupBox8.Size = size;
			this.GroupBox8.TabIndex = 236;
			this.GroupBox8.TabStop = false;
			this.GroupBox8.Text = "執行時採用的組態檔名 :";
			this.txtCfg.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtCfg = this.txtCfg;
			point = new global::System.Drawing.Point(6, 19);
			txtCfg.Location = point;
			this.txtCfg.Name = "txtCfg";
			this.txtCfg.ReadOnly = true;
			global::System.Windows.Forms.Control txtCfg2 = this.txtCfg;
			size = new global::System.Drawing.Size(675, 20);
			txtCfg2.Size = size;
			this.txtCfg.TabIndex = 233;
			this.GroupBox7.Controls.Add(this.ckDisBar);
			this.GroupBox7.Controls.Add(this.ckBackGround);
			global::System.Windows.Forms.Control groupBox9 = this.GroupBox7;
			point = new global::System.Drawing.Point(222, 75);
			groupBox9.Location = point;
			this.GroupBox7.Name = "GroupBox7";
			global::System.Windows.Forms.Control groupBox10 = this.GroupBox7;
			size = new global::System.Drawing.Size(198, 83);
			groupBox10.Size = size;
			this.GroupBox7.TabIndex = 235;
			this.GroupBox7.TabStop = false;
			this.GroupBox7.Text = "執行模式下參數";
			this.ckDisBar.AutoSize = true;
			global::System.Windows.Forms.Control ckDisBar = this.ckDisBar;
			point = new global::System.Drawing.Point(11, 47);
			ckDisBar.Location = point;
			this.ckDisBar.Name = "ckDisBar";
			global::System.Windows.Forms.Control ckDisBar2 = this.ckDisBar;
			size = new global::System.Drawing.Size(186, 19);
			ckDisBar2.Size = size;
			this.ckDisBar.TabIndex = 1;
			this.ckDisBar.Text = "Disable Tilte Bar and Menu Bar";
			this.ckDisBar.UseVisualStyleBackColor = true;
			this.ckBackGround.AutoSize = true;
			global::System.Windows.Forms.Control ckBackGround = this.ckBackGround;
			point = new global::System.Drawing.Point(11, 23);
			ckBackGround.Location = point;
			this.ckBackGround.Name = "ckBackGround";
			global::System.Windows.Forms.Control ckBackGround2 = this.ckBackGround;
			size = new global::System.Drawing.Size(130, 19);
			ckBackGround2.Size = size;
			this.ckBackGround.TabIndex = 0;
			this.ckBackGround.Text = "Run AS Background";
			this.ckBackGround.UseVisualStyleBackColor = true;
			this.GroupBox6.AutoSize = true;
			this.GroupBox6.Controls.Add(this.ndScanTime);
			this.GroupBox6.Controls.Add(this.Label9);
			this.GroupBox6.Controls.Add(this.Label10);
			this.GroupBox6.Controls.Add(this.Label6);
			this.GroupBox6.Controls.Add(this.Label7);
			this.GroupBox6.Controls.Add(this.ndSoundTime);
			global::System.Windows.Forms.Control groupBox11 = this.GroupBox6;
			point = new global::System.Drawing.Point(17, 75);
			groupBox11.Location = point;
			this.GroupBox6.Name = "GroupBox6";
			global::System.Windows.Forms.Control groupBox12 = this.GroupBox6;
			size = new global::System.Drawing.Size(199, 85);
			groupBox12.Size = size;
			this.GroupBox6.TabIndex = 231;
			this.GroupBox6.TabStop = false;
			this.GroupBox6.Text = "時間設定";
			this.ndScanTime.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control ndScanTime = this.ndScanTime;
			point = new global::System.Drawing.Point(69, 43);
			ndScanTime.Location = point;
			global::System.Windows.Forms.NumericUpDown ndScanTime2 = this.ndScanTime;
			num = new decimal(new int[] { 5000, 0, 0, 0 });
			ndScanTime2.Maximum = num;
			global::System.Windows.Forms.NumericUpDown ndScanTime3 = this.ndScanTime;
			num = new decimal(new int[] { 300, 0, 0, 0 });
			ndScanTime3.Minimum = num;
			this.ndScanTime.Name = "ndScanTime";
			global::System.Windows.Forms.Control ndScanTime4 = this.ndScanTime;
			size = new global::System.Drawing.Size(81, 20);
			ndScanTime4.Size = size;
			this.ndScanTime.TabIndex = 66;
			this.ndScanTime.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			global::System.Windows.Forms.NumericUpDown ndScanTime5 = this.ndScanTime;
			num = new decimal(new int[] { 500, 0, 0, 0 });
			ndScanTime5.Value = num;
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label15 = this.Label9;
			point = new global::System.Drawing.Point(8, 47);
			label15.Location = point;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label16 = this.Label9;
			size = new global::System.Drawing.Size(55, 14);
			label16.Size = size;
			this.Label9.TabIndex = 65;
			this.Label9.Text = "掃描時間";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label17 = this.Label10;
			point = new global::System.Drawing.Point(150, 47);
			label17.Location = point;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label18 = this.Label10;
			size = new global::System.Drawing.Size(31, 14);
			label18.Size = size;
			this.Label10.TabIndex = 64;
			this.Label10.Text = "豪秒";
			this.Label6.AutoSize = true;
			this.Label6.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label19 = this.Label6;
			point = new global::System.Drawing.Point(8, 22);
			label19.Location = point;
			this.Label6.Name = "Label6";
			global::System.Windows.Forms.Control label20 = this.Label6;
			size = new global::System.Drawing.Size(79, 14);
			label20.Size = size;
			this.Label6.TabIndex = 62;
			this.Label6.Text = "播音間隔時間";
			this.Label6.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label7.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label21 = this.Label7;
			point = new global::System.Drawing.Point(150, 21);
			label21.Location = point;
			this.Label7.Name = "Label7";
			global::System.Windows.Forms.Control label22 = this.Label7;
			size = new global::System.Drawing.Size(14, 18);
			label22.Size = size;
			this.Label7.TabIndex = 61;
			this.Label7.Text = "秒";
			this.ndSoundTime.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control ndSoundTime = this.ndSoundTime;
			point = new global::System.Drawing.Point(90, 19);
			ndSoundTime.Location = point;
			global::System.Windows.Forms.NumericUpDown ndSoundTime2 = this.ndSoundTime;
			num = new decimal(new int[] { 30, 0, 0, 0 });
			ndSoundTime2.Maximum = num;
			global::System.Windows.Forms.NumericUpDown ndSoundTime3 = this.ndSoundTime;
			num = new decimal(new int[] { 1, 0, 0, 0 });
			ndSoundTime3.Minimum = num;
			this.ndSoundTime.Name = "ndSoundTime";
			global::System.Windows.Forms.Control ndSoundTime4 = this.ndSoundTime;
			size = new global::System.Drawing.Size(60, 20);
			ndSoundTime4.Size = size;
			this.ndSoundTime.TabIndex = 60;
			this.ndSoundTime.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			global::System.Windows.Forms.NumericUpDown ndSoundTime5 = this.ndSoundTime;
			num = new decimal(new int[] { 5, 0, 0, 0 });
			ndSoundTime5.Value = num;
			this.Timer1.Enabled = true;
			this.Timer1.Interval = 500;
			this.tmrStatus.Enabled = true;
			this.tmrStatus.Interval = 300;
			this.dlgSave.FileName = "doc1";
			this.panelTime.AutoSize = global::System.Windows.Forms.StatusBarPanelAutoSize.Contents;
			this.panelTime.Name = "panelTime";
			this.panelTime.Text = "14:02:30";
			this.panelTime.Width = 63;
			this.panelStatus.Name = "panelStatus";
			this.panelStatus.Width = 150;
			this.panelFileName.AutoSize = global::System.Windows.Forms.StatusBarPanelAutoSize.Spring;
			this.panelFileName.Name = "panelFileName";
			this.panelFileName.Width = 470;
			this.kvStatusBar.Font = new global::System.Drawing.Font("微軟正黑體", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 136);
			global::System.Windows.Forms.Control kvStatusBar = this.kvStatusBar;
			point = new global::System.Drawing.Point(0, 610);
			kvStatusBar.Location = point;
			this.kvStatusBar.Name = "kvStatusBar";
			this.kvStatusBar.Panels.AddRange(new global::System.Windows.Forms.StatusBarPanel[] { this.panelFileName, this.panelStatus, this.panelTime });
			this.kvStatusBar.ShowPanels = true;
			global::System.Windows.Forms.Control kvStatusBar2 = this.kvStatusBar;
			size = new global::System.Drawing.Size(700, 24);
			kvStatusBar2.Size = size;
			this.kvStatusBar.TabIndex = 57;
			this.kvStatusBar.Text = "此為狀態列(StatusBar), 不使用狀態列面版(SatausBarPanel)的樣子.";
			this.MainMenu1.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.miFile, this.miRun });
			global::System.Windows.Forms.Control mainMenu = this.MainMenu1;
			point = new global::System.Drawing.Point(0, 0);
			mainMenu.Location = point;
			this.MainMenu1.Name = "MainMenu1";
			global::System.Windows.Forms.Control mainMenu2 = this.MainMenu1;
			size = new global::System.Drawing.Size(700, 24);
			mainMenu2.Size = size;
			this.MainMenu1.TabIndex = 58;
			this.MainMenu1.Text = "MenuStrip1";
			this.miFile.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[]
			{
				this.miNew, this.miOpen, this.toolStripSeparator, this.miSave, this.miSaveAs, this.toolStripSeparator1, this.miRecent, this.ToolStripMenuItem2, this.miDelCache, this.toolStripSeparator2,
				this.miReloadDB
			});
			this.miFile.Name = "miFile";
			global::System.Windows.Forms.ToolStripItem miFile = this.miFile;
			size = new global::System.Drawing.Size(57, 20);
			miFile.Size = size;
			this.miFile.Text = "檔案(&F)";
			this.miNew.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("miNew.Image");
			this.miNew.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.miNew.Name = "miNew";
			this.miNew.ShortcutKeys = (global::System.Windows.Forms.Keys)131150;
			global::System.Windows.Forms.ToolStripItem miNew = this.miNew;
			size = new global::System.Drawing.Size(185, 22);
			miNew.Size = size;
			this.miNew.Text = "開新檔案(&N)";
			this.miOpen.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("miOpen.Image");
			this.miOpen.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.miOpen.Name = "miOpen";
			this.miOpen.ShortcutKeys = (global::System.Windows.Forms.Keys)131151;
			global::System.Windows.Forms.ToolStripItem miOpen = this.miOpen;
			size = new global::System.Drawing.Size(185, 22);
			miOpen.Size = size;
			this.miOpen.Text = "開啟舊檔(&O)";
			this.toolStripSeparator.Name = "toolStripSeparator";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator = this.toolStripSeparator;
			size = new global::System.Drawing.Size(182, 6);
			toolStripSeparator.Size = size;
			this.miSave.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("miSave.Image");
			this.miSave.ImageTransparentColor = global::System.Drawing.Color.Magenta;
			this.miSave.Name = "miSave";
			this.miSave.ShortcutKeys = (global::System.Windows.Forms.Keys)131155;
			global::System.Windows.Forms.ToolStripItem miSave = this.miSave;
			size = new global::System.Drawing.Size(185, 22);
			miSave.Size = size;
			this.miSave.Text = "存檔(&S)";
			this.miSaveAs.Name = "miSaveAs";
			global::System.Windows.Forms.ToolStripItem miSaveAs = this.miSaveAs;
			size = new global::System.Drawing.Size(185, 22);
			miSaveAs.Size = size;
			this.miSaveAs.Text = "另存新檔(&A)";
			this.toolStripSeparator1.Name = "toolStripSeparator1";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator2 = this.toolStripSeparator1;
			size = new global::System.Drawing.Size(182, 6);
			toolStripSeparator2.Size = size;
			this.miRecent.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.miRecent1, this.miRecent2, this.miRecent3, this.miRecent4 });
			this.miRecent.Name = "miRecent";
			global::System.Windows.Forms.ToolStripItem miRecent = this.miRecent;
			size = new global::System.Drawing.Size(185, 22);
			miRecent.Size = size;
			this.miRecent.Text = "最近使用的檔案";
			this.miRecent1.Name = "miRecent1";
			global::System.Windows.Forms.ToolStripItem miRecent2 = this.miRecent1;
			size = new global::System.Drawing.Size(77, 22);
			miRecent2.Size = size;
			this.miRecent1.Text = ".";
			this.miRecent2.Name = "miRecent2";
			global::System.Windows.Forms.ToolStripItem miRecent3 = this.miRecent2;
			size = new global::System.Drawing.Size(77, 22);
			miRecent3.Size = size;
			this.miRecent2.Text = ".";
			this.miRecent3.Name = "miRecent3";
			global::System.Windows.Forms.ToolStripItem miRecent4 = this.miRecent3;
			size = new global::System.Drawing.Size(77, 22);
			miRecent4.Size = size;
			this.miRecent3.Text = ".";
			this.miRecent4.Name = "miRecent4";
			global::System.Windows.Forms.ToolStripItem miRecent5 = this.miRecent4;
			size = new global::System.Drawing.Size(77, 22);
			miRecent5.Size = size;
			this.miRecent4.Text = ".";
			this.ToolStripMenuItem2.Name = "ToolStripMenuItem2";
			global::System.Windows.Forms.ToolStripItem toolStripMenuItem2 = this.ToolStripMenuItem2;
			size = new global::System.Drawing.Size(182, 6);
			toolStripMenuItem2.Size = size;
			this.miDelCache.Name = "miDelCache";
			global::System.Windows.Forms.ToolStripItem miDelCache = this.miDelCache;
			size = new global::System.Drawing.Size(185, 22);
			miDelCache.Size = size;
			this.miDelCache.Text = "刪除Cache檔案";
			this.toolStripSeparator2.Name = "toolStripSeparator2";
			global::System.Windows.Forms.ToolStripItem toolStripSeparator3 = this.toolStripSeparator2;
			size = new global::System.Drawing.Size(182, 6);
			toolStripSeparator3.Size = size;
			this.miReloadDB.Name = "miReloadDB";
			global::System.Windows.Forms.ToolStripItem miReloadDB = this.miReloadDB;
			size = new global::System.Drawing.Size(185, 22);
			miReloadDB.Size = size;
			this.miReloadDB.Text = "Reload資料庫";
			this.miRun.Name = "miRun";
			global::System.Windows.Forms.ToolStripItem miRun = this.miRun;
			size = new global::System.Drawing.Size(95, 20);
			miRun.Size = size;
			this.miRun.Text = "切換至執行(&R)";
			this.NodeDataGridViewTextBoxColumn.DataPropertyName = "Node";
			this.NodeDataGridViewTextBoxColumn.HeaderText = "Node";
			this.NodeDataGridViewTextBoxColumn.MaxInputLength = 8;
			this.NodeDataGridViewTextBoxColumn.Name = "NodeDataGridViewTextBoxColumn";
			this.NodeDataGridViewTextBoxColumn.Width = 70;
			this.TagDataGridViewTextBoxColumn.DataPropertyName = "Tag";
			this.TagDataGridViewTextBoxColumn.HeaderText = "Tag";
			this.TagDataGridViewTextBoxColumn.MaxInputLength = 30;
			this.TagDataGridViewTextBoxColumn.Name = "TagDataGridViewTextBoxColumn";
			this.TagDataGridViewTextBoxColumn.Width = 120;
			this.clField.DataPropertyName = "Field";
			this.clField.HeaderText = "Field";
			this.clField.Name = "clField";
			this.clField.ReadOnly = true;
			this.clField.Resizable = global::System.Windows.Forms.DataGridViewTriState.True;
			this.clField.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
			this.clField.Width = 75;
			this.clWave.DataPropertyName = "Wave";
			this.clWave.HeaderText = "Wave";
			this.clWave.Name = "clWave";
			this.clWave.Width = 120;
			this.clnOpenWave.HeaderText = "";
			this.clnOpenWave.Name = "clnOpenWave";
			this.clnOpenWave.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.clnOpenWave.Text = "...";
			this.clnOpenWave.ToolTipText = "開檔";
			this.clnOpenWave.UseColumnTextForButtonValue = true;
			this.clnOpenWave.Width = 20;
			this.clPriority.DataPropertyName = "Priority";
			this.clPriority.HeaderText = "Pri";
			this.clPriority.Items.AddRange(new object[] { "0", "1", "2" });
			this.clPriority.Name = "clPriority";
			this.clPriority.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
			this.clPriority.Width = 40;
			this.clBlockType.DataPropertyName = "BlockType";
			this.clBlockType.HeaderText = "BlockType";
			this.clBlockType.Name = "clBlockType";
			this.clBlockType.ReadOnly = true;
			this.clBlockType.Visible = false;
			this.clLength.DataPropertyName = "Length";
			this.clLength.HeaderText = "Sec";
			this.clLength.Items.AddRange(new object[]
			{
				"0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
				"10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
				"20", "21", "22", "23", "24", "25", "26", "27", "28", "29",
				"30"
			});
			this.clLength.Name = "clLength";
			this.clLength.Resizable = global::System.Windows.Forms.DataGridViewTriState.True;
			this.clLength.SortMode = global::System.Windows.Forms.DataGridViewColumnSortMode.Automatic;
			this.clLength.Width = 40;
			this.clPicture.DataPropertyName = "Picture";
			this.clPicture.HeaderText = "Picture";
			this.clPicture.Name = "clPicture";
			this.clPicture.Width = 120;
			this.clnOpenPic.HeaderText = "";
			this.clnOpenPic.Name = "clnOpenPic";
			this.clnOpenPic.Resizable = global::System.Windows.Forms.DataGridViewTriState.False;
			this.clnOpenPic.Text = "...";
			this.clnOpenPic.ToolTipText = "開檔";
			this.clnOpenPic.UseColumnTextForButtonValue = true;
			this.clnOpenPic.Width = 20;
			this.clOutSource.DataPropertyName = "OutSource";
			this.clOutSource.HeaderText = "OutSource";
			this.clOutSource.MaxInputLength = 256;
			this.clOutSource.Name = "clOutSource";
			this.clOutSource.Visible = false;
			this.clOutSource.Width = 150;
			this.clOutValue.DataPropertyName = "OutValue";
			this.clOutValue.HeaderText = "Value";
			this.clOutValue.MaxInputLength = 32;
			this.clOutValue.Name = "clOutValue";
			this.clOutValue.Visible = false;
			this.clOutValue.Width = 40;
			global::System.Drawing.SizeF sizeF = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = sizeF;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(700, 634);
			this.ClientSize = size;
			this.ControlBox = false;
			this.Controls.Add(this.MainMenu1);
			this.Controls.Add(this.kvStatusBar);
			this.Controls.Add(this.tabEnvironment);
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.MainMenuStrip = this.MainMenu1;
			this.MaximizeBox = false;
			size = new global::System.Drawing.Size(1280, 1024);
			this.MaximumSize = size;
			size = new global::System.Drawing.Size(650, 650);
			this.MinimumSize = size;
			this.Name = "frmAlarmSndCfg";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "iFix 警報輪迴播音系統(Configure)";
			this.tabEnvironment.ResumeLayout(false);
			this.tabTAG.ResumeLayout(false);
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox4.ResumeLayout(false);
			this.gpAction.ResumeLayout(false);
			this.gpAction.PerformLayout();
			this.gpSound.ResumeLayout(false);
			this.gpSound.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.ndSecond).EndInit();
			this.gpOutSource.ResumeLayout(false);
			this.gpOutSource.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.ndLevel).EndInit();
			this.gpPicture.ResumeLayout(false);
			this.gpPicture.PerformLayout();
			this.gpTagSource.ResumeLayout(false);
			this.gpTagSource.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.DataGrid1).EndInit();
			this.ContextMenuStrip_Grid.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this._dsCFG).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataTable1).EndInit();
			this.gpFilter.ResumeLayout(false);
			this.gpFilter.PerformLayout();
			this.tabParameter.ResumeLayout(false);
			this.tabParameter.PerformLayout();
			this.GroupBox8.ResumeLayout(false);
			this.GroupBox8.PerformLayout();
			this.GroupBox7.ResumeLayout(false);
			this.GroupBox7.PerformLayout();
			this.GroupBox6.ResumeLayout(false);
			this.GroupBox6.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.ndScanTime).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.ndSoundTime).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.panelTime).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.panelStatus).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.panelFileName).EndInit();
			this.MainMenu1.ResumeLayout(false);
			this.MainMenu1.PerformLayout();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x0400002B RID: 43
		private global::System.ComponentModel.IContainer components;
	}
}
