namespace triFixAlmSndCyl
{
	// Token: 0x0200000F RID: 15
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class frmAlmSndRun : global::System.Windows.Forms.Form
	{
		// Token: 0x0600016A RID: 362 RVA: 0x0000F950 File Offset: 0x0000DD50
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x0600016B RID: 363 RVA: 0x0000F970 File Offset: 0x0000DD70
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::triFixAlmSndCyl.frmAlmSndRun));
			this.Label3 = new global::System.Windows.Forms.Label();
			this.Label1 = new global::System.Windows.Forms.Label();
			this.txtSoundTime = new global::System.Windows.Forms.TextBox();
			this.txtScanTime = new global::System.Windows.Forms.TextBox();
			this.Label9 = new global::System.Windows.Forms.Label();
			this.Label10 = new global::System.Windows.Forms.Label();
			this.lstQueue = new global::System.Windows.Forms.ListBox();
			this.Monitor = new global::System.Windows.Forms.ListBox();
			this.ContextMenuStrip_Event = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.tsmiShowEvent = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tsmiShowError = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripMenuItem1 = new global::System.Windows.Forms.ToolStripSeparator();
			this.tsmiClearEvent = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ckMute = new global::System.Windows.Forms.CheckBox();
			this.txtOverRun = new global::System.Windows.Forms.TextBox();
			this.Label4 = new global::System.Windows.Forms.Label();
			this.GroupBox1 = new global::System.Windows.Forms.GroupBox();
			this.GroupBox2 = new global::System.Windows.Forms.GroupBox();
			this.ckQueue = new global::System.Windows.Forms.CheckBox();
			this.GroupBox3 = new global::System.Windows.Forms.GroupBox();
			this.TreeView1 = new global::System.Windows.Forms.TreeView();
			this.ContextMenuStrip_Tree = new global::System.Windows.Forms.ContextMenuStrip(this.components);
			this.cmsCollapseAll = new global::System.Windows.Forms.ToolStripMenuItem();
			this.cmdCollapseType = new global::System.Windows.Forms.ToolStripMenuItem();
			this.ToolStripMenuItem2 = new global::System.Windows.Forms.ToolStripSeparator();
			this.cmsExpandAll = new global::System.Windows.Forms.ToolStripMenuItem();
			this.cmsExpandNode = new global::System.Windows.Forms.ToolStripMenuItem();
			this.GroupBox4 = new global::System.Windows.Forms.GroupBox();
			this._dsEDARunTime = new global::System.Data.DataSet();
			this.DataTable1 = new global::System.Data.DataTable();
			this.DataColumn1 = new global::System.Data.DataColumn();
			this.DataColumn2 = new global::System.Data.DataColumn();
			this.DataColumn3 = new global::System.Data.DataColumn();
			this.DataColumn4 = new global::System.Data.DataColumn();
			this.DataColumn5 = new global::System.Data.DataColumn();
			this.DataColumn6 = new global::System.Data.DataColumn();
			this.DataColumn7 = new global::System.Data.DataColumn();
			this.tmrRun = new global::System.Windows.Forms.Timer(this.components);
			this.tmrPlaySound = new global::System.Windows.Forms.Timer(this.components);
			this.ToolTip1 = new global::System.Windows.Forms.ToolTip(this.components);
			this.MenuStrip1 = new global::System.Windows.Forms.MenuStrip();
			this.miConfig = new global::System.Windows.Forms.ToolStripMenuItem();
			this.說明ToolStripMenuItem = new global::System.Windows.Forms.ToolStripMenuItem();
			this.miAbout = new global::System.Windows.Forms.ToolStripMenuItem();
			this.tmrSendMessage = new global::System.Windows.Forms.Timer(this.components);
			this.SplitContainer1 = new global::System.Windows.Forms.SplitContainer();
			this.SplitContainer2 = new global::System.Windows.Forms.SplitContainer();
			this.NotifyIcon1 = new global::System.Windows.Forms.NotifyIcon(this.components);
			this.DataColumn8 = new global::System.Data.DataColumn();
			this.DataColumn9 = new global::System.Data.DataColumn();
			this.DataColumn10 = new global::System.Data.DataColumn();
			this.DataColumn11 = new global::System.Data.DataColumn();
			this.DataColumn12 = new global::System.Data.DataColumn();
			this.DataColumn13 = new global::System.Data.DataColumn();
			this.ContextMenuStrip_Event.SuspendLayout();
			this.GroupBox1.SuspendLayout();
			this.GroupBox2.SuspendLayout();
			this.GroupBox3.SuspendLayout();
			this.ContextMenuStrip_Tree.SuspendLayout();
			this.GroupBox4.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this._dsEDARunTime).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataTable1).BeginInit();
			this.MenuStrip1.SuspendLayout();
			this.SplitContainer1.Panel1.SuspendLayout();
			this.SplitContainer1.Panel2.SuspendLayout();
			this.SplitContainer1.SuspendLayout();
			this.SplitContainer2.Panel1.SuspendLayout();
			this.SplitContainer2.Panel2.SuspendLayout();
			this.SplitContainer2.SuspendLayout();
			this.SuspendLayout();
			this.Label3.AutoSize = true;
			this.Label3.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label = this.Label3;
			global::System.Drawing.Point point = new global::System.Drawing.Point(12, 42);
			label.Location = point;
			this.Label3.Name = "Label3";
			global::System.Windows.Forms.Control label2 = this.Label3;
			global::System.Drawing.Size size = new global::System.Drawing.Size(79, 14);
			label2.Size = size;
			this.Label3.TabIndex = 62;
			this.Label3.Text = "播音間隔時間";
			this.Label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label1.AutoSize = true;
			this.Label1.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label3 = this.Label1;
			point = new global::System.Drawing.Point(156, 42);
			label3.Location = point;
			this.Label1.Name = "Label1";
			global::System.Windows.Forms.Control label4 = this.Label1;
			size = new global::System.Drawing.Size(19, 14);
			label4.Size = size;
			this.Label1.TabIndex = 61;
			this.Label1.Text = "秒";
			this.txtSoundTime.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtSoundTime = this.txtSoundTime;
			point = new global::System.Drawing.Point(94, 39);
			txtSoundTime.Location = point;
			this.txtSoundTime.Name = "txtSoundTime";
			this.txtSoundTime.ReadOnly = true;
			global::System.Windows.Forms.Control txtSoundTime2 = this.txtSoundTime;
			size = new global::System.Drawing.Size(62, 20);
			txtSoundTime2.Size = size;
			this.txtSoundTime.TabIndex = 63;
			this.txtSoundTime.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.txtScanTime.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtScanTime = this.txtScanTime;
			point = new global::System.Drawing.Point(75, 64);
			txtScanTime.Location = point;
			this.txtScanTime.Name = "txtScanTime";
			this.txtScanTime.ReadOnly = true;
			global::System.Windows.Forms.Control txtScanTime2 = this.txtScanTime;
			size = new global::System.Drawing.Size(81, 20);
			txtScanTime2.Size = size;
			this.txtScanTime.TabIndex = 239;
			this.txtScanTime.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.Label9.AutoSize = true;
			this.Label9.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label5 = this.Label9;
			point = new global::System.Drawing.Point(14, 67);
			label5.Location = point;
			this.Label9.Name = "Label9";
			global::System.Windows.Forms.Control label6 = this.Label9;
			size = new global::System.Drawing.Size(55, 14);
			label6.Size = size;
			this.Label9.TabIndex = 238;
			this.Label9.Text = "掃描時間";
			this.Label9.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.Label10.AutoSize = true;
			this.Label10.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label7 = this.Label10;
			point = new global::System.Drawing.Point(156, 67);
			label7.Location = point;
			this.Label10.Name = "Label10";
			global::System.Windows.Forms.Control label8 = this.Label10;
			size = new global::System.Drawing.Size(31, 14);
			label8.Size = size;
			this.Label10.TabIndex = 237;
			this.Label10.Text = "豪秒";
			this.lstQueue.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.lstQueue.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.lstQueue.HorizontalScrollbar = true;
			this.lstQueue.ItemHeight = 14;
			global::System.Windows.Forms.Control lstQueue = this.lstQueue;
			point = new global::System.Drawing.Point(10, 19);
			lstQueue.Location = point;
			this.lstQueue.Name = "lstQueue";
			global::System.Windows.Forms.Control lstQueue2 = this.lstQueue;
			size = new global::System.Drawing.Size(168, 158);
			lstQueue2.Size = size;
			this.lstQueue.TabIndex = 240;
			this.Monitor.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.Monitor.BackColor = global::System.Drawing.Color.Black;
			this.Monitor.ContextMenuStrip = this.ContextMenuStrip_Event;
			this.Monitor.Font = new global::System.Drawing.Font("MS Reference Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.Monitor.ForeColor = global::System.Drawing.Color.White;
			this.Monitor.HorizontalScrollbar = true;
			this.Monitor.ItemHeight = 15;
			global::System.Windows.Forms.Control monitor = this.Monitor;
			point = new global::System.Drawing.Point(6, 16);
			monitor.Location = point;
			this.Monitor.Name = "Monitor";
			global::System.Windows.Forms.Control monitor2 = this.Monitor;
			size = new global::System.Drawing.Size(475, 94);
			monitor2.Size = size;
			this.Monitor.TabIndex = 241;
			this.ToolTip1.SetToolTip(this.Monitor, "按下滑鼠右鍵切換顯示");
			this.ContextMenuStrip_Event.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.tsmiShowEvent, this.tsmiShowError, this.ToolStripMenuItem1, this.tsmiClearEvent });
			this.ContextMenuStrip_Event.Name = "ContextMenuStrip_Event";
			this.ContextMenuStrip_Event.ShowCheckMargin = true;
			this.ContextMenuStrip_Event.ShowImageMargin = false;
			this.ContextMenuStrip_Event.ShowItemToolTips = false;
			global::System.Windows.Forms.Control contextMenuStrip_Event = this.ContextMenuStrip_Event;
			size = new global::System.Drawing.Size(123, 76);
			contextMenuStrip_Event.Size = size;
			this.tsmiShowEvent.Name = "tsmiShowEvent";
			global::System.Windows.Forms.ToolStripItem tsmiShowEvent = this.tsmiShowEvent;
			size = new global::System.Drawing.Size(122, 22);
			tsmiShowEvent.Size = size;
			this.tsmiShowEvent.Text = "監視事件";
			this.tsmiShowError.Name = "tsmiShowError";
			global::System.Windows.Forms.ToolStripItem tsmiShowError = this.tsmiShowError;
			size = new global::System.Drawing.Size(122, 22);
			tsmiShowError.Size = size;
			this.tsmiShowError.Text = "監視錯誤";
			this.tsmiShowError.Visible = false;
			this.ToolStripMenuItem1.Name = "ToolStripMenuItem1";
			global::System.Windows.Forms.ToolStripItem toolStripMenuItem = this.ToolStripMenuItem1;
			size = new global::System.Drawing.Size(119, 6);
			toolStripMenuItem.Size = size;
			this.tsmiClearEvent.Name = "tsmiClearEvent";
			global::System.Windows.Forms.ToolStripItem tsmiClearEvent = this.tsmiClearEvent;
			size = new global::System.Drawing.Size(122, 22);
			tsmiClearEvent.Size = size;
			this.tsmiClearEvent.Text = "清除記錄";
			this.ckMute.AutoSize = true;
			global::System.Windows.Forms.Control ckMute = this.ckMute;
			point = new global::System.Drawing.Point(14, 17);
			ckMute.Location = point;
			this.ckMute.Name = "ckMute";
			global::System.Windows.Forms.Control ckMute2 = this.ckMute;
			size = new global::System.Drawing.Size(125, 16);
			ckMute2.Size = size;
			this.ckMute.TabIndex = 243;
			this.ckMute.Text = "靜音(Ctrl+S / Ctrl+P)";
			this.ckMute.UseVisualStyleBackColor = true;
			this.txtOverRun.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control txtOverRun = this.txtOverRun;
			point = new global::System.Drawing.Point(64, 90);
			txtOverRun.Location = point;
			this.txtOverRun.Name = "txtOverRun";
			this.txtOverRun.ReadOnly = true;
			global::System.Windows.Forms.Control txtOverRun2 = this.txtOverRun;
			size = new global::System.Drawing.Size(111, 20);
			txtOverRun2.Size = size;
			this.txtOverRun.TabIndex = 246;
			this.txtOverRun.Text = "0";
			this.txtOverRun.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Right;
			this.Label4.AutoSize = true;
			this.Label4.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label9 = this.Label4;
			point = new global::System.Drawing.Point(14, 93);
			label9.Location = point;
			this.Label4.Name = "Label4";
			global::System.Windows.Forms.Control label10 = this.Label4;
			size = new global::System.Drawing.Size(50, 14);
			label10.Size = size;
			this.Label4.TabIndex = 245;
			this.Label4.Text = "OverRun";
			this.Label4.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.GroupBox1.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.GroupBox1.Controls.Add(this.txtOverRun);
			this.GroupBox1.Controls.Add(this.ckMute);
			this.GroupBox1.Controls.Add(this.Label1);
			this.GroupBox1.Controls.Add(this.Label4);
			this.GroupBox1.Controls.Add(this.Label3);
			this.GroupBox1.Controls.Add(this.txtSoundTime);
			this.GroupBox1.Controls.Add(this.Label10);
			this.GroupBox1.Controls.Add(this.Label9);
			this.GroupBox1.Controls.Add(this.txtScanTime);
			global::System.Windows.Forms.Control groupBox = this.GroupBox1;
			point = new global::System.Drawing.Point(8, 3);
			groupBox.Location = point;
			this.GroupBox1.Name = "GroupBox1";
			global::System.Windows.Forms.Control groupBox2 = this.GroupBox1;
			size = new global::System.Drawing.Size(186, 118);
			groupBox2.Size = size;
			this.GroupBox1.TabIndex = 247;
			this.GroupBox1.TabStop = false;
			this.GroupBox1.Text = "參數";
			this.GroupBox2.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.GroupBox2.Controls.Add(this.ckQueue);
			this.GroupBox2.Controls.Add(this.lstQueue);
			global::System.Windows.Forms.Control groupBox3 = this.GroupBox2;
			point = new global::System.Drawing.Point(8, 127);
			groupBox3.Location = point;
			this.GroupBox2.Name = "GroupBox2";
			global::System.Windows.Forms.Control groupBox4 = this.GroupBox2;
			size = new global::System.Drawing.Size(186, 203);
			groupBox4.Size = size;
			this.GroupBox2.TabIndex = 248;
			this.GroupBox2.TabStop = false;
			this.ckQueue.AutoSize = true;
			global::System.Windows.Forms.Control ckQueue = this.ckQueue;
			point = new global::System.Drawing.Point(10, 0);
			ckQueue.Location = point;
			this.ckQueue.Name = "ckQueue";
			global::System.Windows.Forms.Control ckQueue2 = this.ckQueue;
			size = new global::System.Drawing.Size(96, 16);
			ckQueue2.Size = size;
			this.ckQueue.TabIndex = 251;
			this.ckQueue.Text = "顯示播音佇列";
			this.ckQueue.UseVisualStyleBackColor = true;
			this.GroupBox3.Controls.Add(this.TreeView1);
			this.GroupBox3.Dock = global::System.Windows.Forms.DockStyle.Fill;
			this.GroupBox3.Font = new global::System.Drawing.Font("Arial", 8.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control groupBox5 = this.GroupBox3;
			point = new global::System.Drawing.Point(0, 0);
			groupBox5.Location = point;
			this.GroupBox3.Name = "GroupBox3";
			global::System.Windows.Forms.Control groupBox6 = this.GroupBox3;
			size = new global::System.Drawing.Size(300, 335);
			groupBox6.Size = size;
			this.GroupBox3.TabIndex = 249;
			this.GroupBox3.TabStop = false;
			this.GroupBox3.Text = "Tag List";
			this.TreeView1.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.TreeView1.ContextMenuStrip = this.ContextMenuStrip_Tree;
			this.TreeView1.ForeColor = global::System.Drawing.Color.Gray;
			global::System.Windows.Forms.Control treeView = this.TreeView1;
			point = new global::System.Drawing.Point(6, 17);
			treeView.Location = point;
			global::System.Windows.Forms.Control treeView2 = this.TreeView1;
			size = new global::System.Drawing.Size(283, 276);
			treeView2.MinimumSize = size;
			this.TreeView1.Name = "TreeView1";
			this.TreeView1.ShowNodeToolTips = true;
			global::System.Windows.Forms.Control treeView3 = this.TreeView1;
			size = new global::System.Drawing.Size(288, 307);
			treeView3.Size = size;
			this.TreeView1.TabIndex = 0;
			this.ContextMenuStrip_Tree.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.cmsCollapseAll, this.cmdCollapseType, this.ToolStripMenuItem2, this.cmsExpandAll, this.cmsExpandNode });
			this.ContextMenuStrip_Tree.Name = "ContextMenuStrip_Tree";
			global::System.Windows.Forms.Control contextMenuStrip_Tree = this.ContextMenuStrip_Tree;
			size = new global::System.Drawing.Size(144, 98);
			contextMenuStrip_Tree.Size = size;
			this.cmsCollapseAll.Name = "cmsCollapseAll";
			global::System.Windows.Forms.ToolStripItem cmsCollapseAll = this.cmsCollapseAll;
			size = new global::System.Drawing.Size(143, 22);
			cmsCollapseAll.Size = size;
			this.cmsCollapseAll.Text = "全部摺疊";
			this.cmdCollapseType.Name = "cmdCollapseType";
			global::System.Windows.Forms.ToolStripItem cmdCollapseType = this.cmdCollapseType;
			size = new global::System.Drawing.Size(143, 22);
			cmdCollapseType.Size = size;
			this.cmdCollapseType.Text = "摺疊至Type";
			this.ToolStripMenuItem2.Name = "ToolStripMenuItem2";
			global::System.Windows.Forms.ToolStripItem toolStripMenuItem2 = this.ToolStripMenuItem2;
			size = new global::System.Drawing.Size(140, 6);
			toolStripMenuItem2.Size = size;
			this.cmsExpandAll.Name = "cmsExpandAll";
			global::System.Windows.Forms.ToolStripItem cmsExpandAll = this.cmsExpandAll;
			size = new global::System.Drawing.Size(143, 22);
			cmsExpandAll.Size = size;
			this.cmsExpandAll.Text = "全部展開";
			this.cmsExpandNode.Name = "cmsExpandNode";
			global::System.Windows.Forms.ToolStripItem cmsExpandNode = this.cmsExpandNode;
			size = new global::System.Drawing.Size(143, 22);
			cmsExpandNode.Size = size;
			this.cmsExpandNode.Text = "展開至Node";
			this.GroupBox4.Anchor = global::System.Windows.Forms.AnchorStyles.Top | global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Left | global::System.Windows.Forms.AnchorStyles.Right;
			this.GroupBox4.Controls.Add(this.Monitor);
			global::System.Windows.Forms.Control groupBox7 = this.GroupBox4;
			point = new global::System.Drawing.Point(10, 3);
			groupBox7.Location = point;
			this.GroupBox4.Name = "GroupBox4";
			global::System.Windows.Forms.Control groupBox8 = this.GroupBox4;
			size = new global::System.Drawing.Size(489, 119);
			groupBox8.Size = size;
			this.GroupBox4.TabIndex = 250;
			this.GroupBox4.TabStop = false;
			this.GroupBox4.Text = "事件顯示";
			this._dsEDARunTime.DataSetName = "DataSet1";
			this._dsEDARunTime.Tables.AddRange(new global::System.Data.DataTable[] { this.DataTable1 });
			this.DataTable1.Columns.AddRange(new global::System.Data.DataColumn[]
			{
				this.DataColumn1, this.DataColumn2, this.DataColumn3, this.DataColumn4, this.DataColumn5, this.DataColumn6, this.DataColumn7, this.DataColumn8, this.DataColumn9, this.DataColumn10,
				this.DataColumn11, this.DataColumn12, this.DataColumn13
			});
			this.DataTable1.Constraints.AddRange(new global::System.Data.Constraint[]
			{
				new global::System.Data.UniqueConstraint("Constraint1", new string[] { "Field", "Node", "Tag" }, false)
			});
			this.DataTable1.TableName = "Config";
			this.DataColumn1.AllowDBNull = false;
			this.DataColumn1.Caption = "Node";
			this.DataColumn1.ColumnName = "Node";
			this.DataColumn1.MaxLength = 8;
			this.DataColumn2.AllowDBNull = false;
			this.DataColumn2.Caption = "Tag";
			this.DataColumn2.ColumnName = "Tag";
			this.DataColumn2.MaxLength = 30;
			this.DataColumn3.AllowDBNull = false;
			this.DataColumn3.Caption = "Wave檔名";
			this.DataColumn3.ColumnName = "Wave";
			this.DataColumn3.MaxLength = 255;
			this.DataColumn4.AllowDBNull = false;
			this.DataColumn4.Caption = "優先順序";
			this.DataColumn4.ColumnName = "Priority";
			this.DataColumn4.DefaultValue = "2";
			this.DataColumn4.MaxLength = 1;
			this.DataColumn5.AllowDBNull = false;
			this.DataColumn5.Caption = "BlockType";
			this.DataColumn5.ColumnName = "BlockType";
			this.DataColumn5.DataType = typeof(short);
			this.DataColumn5.DefaultValue = 0;
			this.DataColumn6.Caption = "秒數";
			this.DataColumn6.ColumnName = "Length";
			this.DataColumn6.DefaultValue = "0";
			this.DataColumn6.MaxLength = 2;
			this.DataColumn7.Caption = "Field";
			this.DataColumn7.ColumnName = "Field";
			this.DataColumn7.DefaultValue = "\"\"";
			this.DataColumn7.MaxLength = 32;
			this.tmrRun.Interval = 500;
			this.MenuStrip1.Items.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.miConfig, this.說明ToolStripMenuItem });
			global::System.Windows.Forms.Control menuStrip = this.MenuStrip1;
			point = new global::System.Drawing.Point(0, 0);
			menuStrip.Location = point;
			this.MenuStrip1.Name = "MenuStrip1";
			global::System.Windows.Forms.Control menuStrip2 = this.MenuStrip1;
			size = new global::System.Drawing.Size(503, 24);
			menuStrip2.Size = size;
			this.MenuStrip1.TabIndex = 251;
			this.MenuStrip1.Text = "MenuStrip1";
			this.miConfig.Name = "miConfig";
			global::System.Windows.Forms.ToolStripItem miConfig = this.miConfig;
			size = new global::System.Drawing.Size(79, 20);
			miConfig.Size = size;
			this.miConfig.Text = "切換至編輯";
			this.說明ToolStripMenuItem.DropDownItems.AddRange(new global::System.Windows.Forms.ToolStripItem[] { this.miAbout });
			this.說明ToolStripMenuItem.Name = "說明ToolStripMenuItem";
			global::System.Windows.Forms.ToolStripItem 說明ToolStripMenuItem = this.說明ToolStripMenuItem;
			size = new global::System.Drawing.Size(43, 20);
			說明ToolStripMenuItem.Size = size;
			this.說明ToolStripMenuItem.Text = "說明";
			this.miAbout.Name = "miAbout";
			global::System.Windows.Forms.ToolStripItem miAbout = this.miAbout;
			size = new global::System.Drawing.Size(242, 22);
			miAbout.Size = size;
			this.miAbout.Text = "關於 iFix警報輪迴播音系統 版本";
			this.SplitContainer1.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control splitContainer = this.SplitContainer1;
			point = new global::System.Drawing.Point(0, 24);
			splitContainer.Location = point;
			this.SplitContainer1.Name = "SplitContainer1";
			this.SplitContainer1.Orientation = global::System.Windows.Forms.Orientation.Horizontal;
			this.SplitContainer1.Panel1.Controls.Add(this.SplitContainer2);
			this.SplitContainer1.Panel2.Controls.Add(this.GroupBox4);
			global::System.Windows.Forms.Control splitContainer2 = this.SplitContainer1;
			size = new global::System.Drawing.Size(503, 464);
			splitContainer2.Size = size;
			this.SplitContainer1.SplitterDistance = 337;
			this.SplitContainer1.SplitterWidth = 2;
			this.SplitContainer1.TabIndex = 252;
			this.SplitContainer2.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.SplitContainer2.Dock = global::System.Windows.Forms.DockStyle.Fill;
			global::System.Windows.Forms.Control splitContainer3 = this.SplitContainer2;
			point = new global::System.Drawing.Point(0, 0);
			splitContainer3.Location = point;
			this.SplitContainer2.Name = "SplitContainer2";
			this.SplitContainer2.Panel1.Controls.Add(this.GroupBox3);
			this.SplitContainer2.Panel2.Controls.Add(this.GroupBox1);
			this.SplitContainer2.Panel2.Controls.Add(this.GroupBox2);
			global::System.Windows.Forms.Control splitContainer4 = this.SplitContainer2;
			size = new global::System.Drawing.Size(503, 337);
			splitContainer4.Size = size;
			this.SplitContainer2.SplitterDistance = 302;
			this.SplitContainer2.SplitterWidth = 2;
			this.SplitContainer2.TabIndex = 0;
			this.NotifyIcon1.BalloonTipIcon = global::System.Windows.Forms.ToolTipIcon.Info;
			this.NotifyIcon1.BalloonTipText = "Fix Alarm Sound";
			this.NotifyIcon1.BalloonTipTitle = "Fix Alarm Sound";
			this.NotifyIcon1.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("NotifyIcon1.Icon");
			this.NotifyIcon1.Text = "Fix Alarm Sound";
			this.DataColumn8.Caption = "Picture";
			this.DataColumn8.ColumnName = "picture";
			this.DataColumn8.DefaultValue = "";
			this.DataColumn9.Caption = "OutSource";
			this.DataColumn9.ColumnName = "OutSource";
			this.DataColumn9.DefaultValue = "";
			this.DataColumn10.Caption = "OutValue";
			this.DataColumn10.ColumnName = "OutValue";
			this.DataColumn10.DefaultValue = "";
			this.DataColumn11.AllowDBNull = false;
			this.DataColumn11.Caption = "LastAlmCount";
			this.DataColumn11.ColumnName = "LastAlmCount";
			this.DataColumn11.DataType = typeof(float);
			this.DataColumn11.DefaultValue = "0";
			this.DataColumn12.AllowDBNull = false;
			this.DataColumn12.Caption = "Played";
			this.DataColumn12.ColumnName = "Played";
			this.DataColumn12.DataType = typeof(bool);
			this.DataColumn12.DefaultValue = false;
			this.DataColumn13.AllowDBNull = false;
			this.DataColumn13.Caption = "PlayCnt";
			this.DataColumn13.ColumnName = "PlayCnt";
			this.DataColumn13.DataType = typeof(float);
			this.DataColumn13.DefaultValue = 0f;
			global::System.Drawing.SizeF sizeF = new global::System.Drawing.SizeF(6f, 12f);
			this.AutoScaleDimensions = sizeF;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			size = new global::System.Drawing.Size(503, 488);
			this.ClientSize = size;
			this.Controls.Add(this.SplitContainer1);
			this.Controls.Add(this.MenuStrip1);
			this.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			this.KeyPreview = true;
			this.MaximizeBox = false;
			size = new global::System.Drawing.Size(519, 526);
			this.MinimumSize = size;
			this.Name = "frmAlmSndRun";
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "iFix警報輪迴播音系統(Run)";
			this.ContextMenuStrip_Event.ResumeLayout(false);
			this.GroupBox1.ResumeLayout(false);
			this.GroupBox1.PerformLayout();
			this.GroupBox2.ResumeLayout(false);
			this.GroupBox2.PerformLayout();
			this.GroupBox3.ResumeLayout(false);
			this.ContextMenuStrip_Tree.ResumeLayout(false);
			this.GroupBox4.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this._dsEDARunTime).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.DataTable1).EndInit();
			this.MenuStrip1.ResumeLayout(false);
			this.MenuStrip1.PerformLayout();
			this.SplitContainer1.Panel1.ResumeLayout(false);
			this.SplitContainer1.Panel2.ResumeLayout(false);
			this.SplitContainer1.ResumeLayout(false);
			this.SplitContainer2.Panel1.ResumeLayout(false);
			this.SplitContainer2.Panel2.ResumeLayout(false);
			this.SplitContainer2.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x040000AC RID: 172
		private global::System.ComponentModel.IContainer components;
	}
}
