using System;

namespace System.Xml
{
	internal enum BinXmlToken
	{
		Error,
		NotImpl = -2,
		EOF,
		XmlDecl = 254,
		Encoding = 253,
		DocType = 252,
		System = 251,
		Public = 250,
		Subset = 249,
		Element = 248,
		EndElem = 247,
		Attr = 246,
		EndAttrs = 245,
		PI = 244,
		Comment = 243,
		CData = 242,
		EndCData = 241,
		Name = 240,
		QName = 239,
		XmlText = 237,
		Nest = 236,
		EndNest = 235,
		Extn = 234,
		NmFlush = 233,
		SQL_BIT = 6,
		SQL_TINYINT,
		SQL_SMALLINT = 1,
		SQL_INT,
		SQL_BIGINT = 8,
		SQL_REAL = 3,
		SQL_FLOAT,
		SQL_MONEY,
		SQL_SMALLMONEY = 20,
		SQL_DATETIME = 18,
		SQL_SMALLDATETIME,
		SQL_DECIMAL = 10,
		SQL_NUMERIC,
		SQL_UUID = 9,
		SQL_VARBINARY = 15,
		SQL_BINARY = 12,
		SQL_IMAGE = 23,
		SQL_CHAR = 13,
		SQL_VARCHAR = 16,
		SQL_TEXT = 22,
		SQL_NVARCHAR = 17,
		SQL_NCHAR = 14,
		SQL_NTEXT = 24,
		SQL_UDT = 27,
		XSD_KATMAI_DATE = 127,
		XSD_KATMAI_DATETIME = 126,
		XSD_KATMAI_TIME = 125,
		XSD_KATMAI_DATEOFFSET = 124,
		XSD_KATMAI_DATETIMEOFFSET = 123,
		XSD_KATMAI_TIMEOFFSET = 122,
		XSD_BOOLEAN = 134,
		XSD_TIME = 129,
		XSD_DATETIME,
		XSD_DATE,
		XSD_BINHEX,
		XSD_BASE64,
		XSD_DECIMAL = 135,
		XSD_BYTE,
		XSD_UNSIGNEDSHORT,
		XSD_UNSIGNEDINT,
		XSD_UNSIGNEDLONG,
		XSD_QNAME
	}
}
