using System;
using System.Collections;
using System.ComponentModel;

namespace System.Windows.Forms.Design
{
	// Token: 0x020002C1 RID: 705
	internal class ToolStripDropDownItemDesigner : ToolStripItemDesigner
	{
		// Token: 0x06001ABE RID: 6846 RVA: 0x00092137 File Offset: 0x00091137
		public override void Initialize(IComponent component)
		{
			base.Initialize(component);
		}

		// Token: 0x1700049B RID: 1179
		// (get) Token: 0x06001ABF RID: 6847 RVA: 0x00092140 File Offset: 0x00091140
		public override ICollection AssociatedComponents
		{
			get
			{
				ToolStripDropDownItem toolStripDropDownItem = base.Component as ToolStripDropDownItem;
				if (toolStripDropDownItem != null && toolStripDropDownItem.DropDown.IsAutoGenerated)
				{
					return toolStripDropDownItem.DropDownItems;
				}
				return base.AssociatedComponents;
			}
		}
	}
}
