using System;
using System.Collections;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.ComponentModel.Design.Serialization;
using System.Design;
using System.Drawing;
using System.Windows.Forms.Design.Behavior;

namespace System.Windows.Forms.Design
{
	// Token: 0x020002CD RID: 717
	internal class ToolStripMenuItemDesigner : ToolStripDropDownItemDesigner
	{
		// Token: 0x170004B5 RID: 1205
		// (get) Token: 0x06001B3A RID: 6970 RVA: 0x00096BC4 File Offset: 0x00095BC4
		public override ICollection AssociatedComponents
		{
			get
			{
				ArrayList arrayList = new ArrayList();
				if (this.MenuItem.DropDown.IsAutoGenerated)
				{
					foreach (object obj in this.MenuItem.DropDownItems)
					{
						ToolStripItem toolStripItem = (ToolStripItem)obj;
						if (!(toolStripItem is DesignerToolStripControlHost))
						{
							arrayList.Add(toolStripItem);
						}
					}
				}
				return arrayList;
			}
		}

		// Token: 0x170004B6 RID: 1206
		// (get) Token: 0x06001B3B RID: 6971 RVA: 0x00096C4C File Offset: 0x00095C4C
		// (set) Token: 0x06001B3C RID: 6972 RVA: 0x00096C63 File Offset: 0x00095C63
		private bool CheckOnClick
		{
			get
			{
				return (bool)base.ShadowProperties["CheckOnClick"];
			}
			set
			{
				base.ShadowProperties["CheckOnClick"] = value;
			}
		}

		// Token: 0x170004B7 RID: 1207
		// (get) Token: 0x06001B3D RID: 6973 RVA: 0x00096C7B File Offset: 0x00095C7B
		// (set) Token: 0x06001B3E RID: 6974 RVA: 0x00096C92 File Offset: 0x00095C92
		private bool DoubleClickEnabled
		{
			get
			{
				return (bool)base.ShadowProperties["DoubleClickEnabled"];
			}
			set
			{
				base.ShadowProperties["DoubleClickEnabled"] = value;
			}
		}

		// Token: 0x170004B8 RID: 1208
		// (get) Token: 0x06001B3F RID: 6975 RVA: 0x00096CAA File Offset: 0x00095CAA
		// (set) Token: 0x06001B40 RID: 6976 RVA: 0x00096CB4 File Offset: 0x00095CB4
		private ToolStripDropDown DropDown
		{
			get
			{
				return this.customDropDown;
			}
			set
			{
				this.dropDownSetFailed = false;
				if (this.IsParentDropDown(value))
				{
					this.dropDownSetFailed = true;
					throw new ArgumentException(SR.GetString("InvalidArgument", new object[]
					{
						"DropDown",
						value.ToString()
					}));
				}
				if (this.MenuItem.DropDown != null)
				{
					this.RemoveTypeHereNode(this.MenuItem);
					if (this.MenuItem.DropDown.IsAutoGenerated && this.MenuItem.DropDownItems.Count > 0)
					{
						ComponentSerializationService componentSerializationService = this.GetService(typeof(ComponentSerializationService)) as ComponentSerializationService;
						if (componentSerializationService != null)
						{
							this.serializedDataForDropDownItems = componentSerializationService.CreateStore();
							foreach (object obj in this.MenuItem.DropDownItems)
							{
								ToolStripItem toolStripItem = (ToolStripItem)obj;
								if (!(toolStripItem is DesignerToolStripControlHost))
								{
									componentSerializationService.Serialize(this.serializedDataForDropDownItems, toolStripItem);
								}
							}
							this.serializedDataForDropDownItems.Close();
						}
						ToolStripItem[] array = new ToolStripItem[this.MenuItem.DropDownItems.Count];
						this.MenuItem.DropDownItems.CopyTo(array, 0);
						foreach (ToolStripItem toolStripItem2 in array)
						{
							this.MenuItem.DropDownItems.Remove(toolStripItem2);
							this.designerHost.DestroyComponent(toolStripItem2);
						}
					}
					this.MenuItem.HideDropDown();
				}
				this.MenuItem.DropDown = value;
				this.customDropDown = value;
				if (value == null && !this.dropDownSet && this.serializedDataForDropDownItems != null)
				{
					try
					{
						ToolStripDesigner._autoAddNewItems = false;
						this.CreatetypeHereNode();
						ComponentSerializationService componentSerializationService2 = this.GetService(typeof(ComponentSerializationService)) as ComponentSerializationService;
						if (componentSerializationService2 != null)
						{
							componentSerializationService2.Deserialize(this.serializedDataForDropDownItems);
							this.serializedDataForDropDownItems = null;
						}
					}
					finally
					{
						ToolStripDesigner._autoAddNewItems = true;
					}
				}
				this.MenuItem.DropDown.OwnerItem = this.MenuItem;
				this.MenuItem.DropDown.Disposed += this.OnDropDownDisposed;
				if (this.MenuItem.Equals(this.selSvc.PrimarySelection))
				{
					this.InitializeDropDown();
				}
			}
		}

		// Token: 0x170004B9 RID: 1209
		// (get) Token: 0x06001B41 RID: 6977 RVA: 0x00096F18 File Offset: 0x00095F18
		// (set) Token: 0x06001B42 RID: 6978 RVA: 0x00096F3E File Offset: 0x00095F3E
		internal override ToolStripTemplateNode Editor
		{
			get
			{
				if (base.Editor != null)
				{
					return base.Editor;
				}
				if (this.commitedTemplateNode != null)
				{
					return this.commitedTemplateNode;
				}
				return this.typeHereTemplateNode;
			}
			set
			{
				this.commitedTemplateNode = value;
			}
		}

		// Token: 0x170004BA RID: 1210
		// (get) Token: 0x06001B43 RID: 6979 RVA: 0x00096F48 File Offset: 0x00095F48
		private bool IsOnContextMenu
		{
			get
			{
				ToolStrip mainToolStrip = this.GetMainToolStrip();
				return mainToolStrip == null || mainToolStrip.Site == null || mainToolStrip is ContextMenuStrip;
			}
		}

		// Token: 0x170004BB RID: 1211
		// (get) Token: 0x06001B44 RID: 6980 RVA: 0x00096F72 File Offset: 0x00095F72
		private ToolStripDropDownItem MenuItem
		{
			get
			{
				return base.ToolStripItem as ToolStripDropDownItem;
			}
		}

		// Token: 0x170004BC RID: 1212
		// (get) Token: 0x06001B45 RID: 6981 RVA: 0x00096F80 File Offset: 0x00095F80
		private bool MenuItemSelected
		{
			get
			{
				if (this.selSvc != null)
				{
					object obj = this.selSvc.PrimarySelection;
					ToolStripItem toolStripItem;
					if (obj == null)
					{
						if (this.KeyboardHandlingService != null)
						{
							obj = this.KeyboardHandlingService.SelectedDesignerControl;
						}
						toolStripItem = obj as ToolStripItem;
					}
					else
					{
						toolStripItem = obj as ToolStripItem;
					}
					if (toolStripItem != null)
					{
						if (this.designerHost != null)
						{
							ToolStripItemDesigner toolStripItemDesigner = this.designerHost.GetDesigner(toolStripItem) as ToolStripItemDesigner;
							if (toolStripItemDesigner != null && toolStripItemDesigner.dummyItemAdded)
							{
								return toolStripItem == this.MenuItem;
							}
						}
						if (toolStripItem.IsOnDropDown && toolStripItem.Owner is ToolStripDropDown)
						{
							ToolStripDropDownItem toolStripDropDownItem = ((ToolStripDropDown)toolStripItem.Owner).OwnerItem as ToolStripDropDownItem;
							return toolStripDropDownItem == this.MenuItem;
						}
						return toolStripItem == this.MenuItem;
					}
					else if (obj is ContextMenuStrip && this.MenuItem.DropDown == obj)
					{
						return true;
					}
				}
				return false;
			}
		}

		// Token: 0x170004BD RID: 1213
		// (get) Token: 0x06001B46 RID: 6982 RVA: 0x00097057 File Offset: 0x00096057
		private ToolStripKeyboardHandlingService KeyboardHandlingService
		{
			get
			{
				if (this.keyboardHandlingService == null)
				{
					this.keyboardHandlingService = this.GetService(typeof(ToolStripKeyboardHandlingService)) as ToolStripKeyboardHandlingService;
				}
				return this.keyboardHandlingService;
			}
		}

		// Token: 0x170004BE RID: 1214
		// (get) Token: 0x06001B47 RID: 6983 RVA: 0x00097084 File Offset: 0x00096084
		protected override IComponent ParentComponent
		{
			get
			{
				if (base.ToolStripItem != null)
				{
					if (!base.ToolStripItem.IsOnOverflow && base.ToolStripItem.IsOnDropDown)
					{
						ToolStripDropDown toolStripDropDown = this.MenuItem.Owner as ToolStripDropDown;
						if (toolStripDropDown != null)
						{
							if (toolStripDropDown.IsAutoGenerated)
							{
								return toolStripDropDown.OwnerItem;
							}
							return toolStripDropDown;
						}
					}
					return base.ParentComponent;
				}
				return null;
			}
		}

		// Token: 0x06001B48 RID: 6984 RVA: 0x000970E0 File Offset: 0x000960E0
		internal void AddNewTemplateNode(ToolStripDropDown dropDown)
		{
			foreach (object obj in dropDown.Items)
			{
				ToolStripItem toolStripItem = (ToolStripItem)obj;
				if (toolStripItem is DesignerToolStripControlHost)
				{
					this.typeHereNode = (DesignerToolStripControlHost)toolStripItem;
				}
			}
			if (this.typeHereNode != null)
			{
				dropDown.Items.Remove(this.typeHereNode);
			}
			this.typeHereTemplateNode = new ToolStripTemplateNode(base.Component, SR.GetString("ToolStripDesignerTemplateNodeEnterText"), null);
			int width = this.typeHereTemplateNode.EditorToolStrip.Width;
			this.typeHereNode = new DesignerToolStripControlHost(this.typeHereTemplateNode.EditorToolStrip);
			this.typeHereTemplateNode.ControlHost = this.typeHereNode;
			this.typeHereNode.AutoSize = false;
			this.typeHereNode.Width = width;
			dropDown.Items.Add(this.typeHereNode);
		}

		// Token: 0x06001B49 RID: 6985 RVA: 0x000971E0 File Offset: 0x000961E0
		internal void AddItemBodyGlyph(ToolStripItem item)
		{
			if (item != null)
			{
				ToolStripItemDesigner toolStripItemDesigner = (ToolStripItemDesigner)this.designerHost.GetDesigner(item);
				if (toolStripItemDesigner != null)
				{
					Rectangle glyphBounds = toolStripItemDesigner.GetGlyphBounds();
					Behavior behavior = new ToolStripItemBehavior();
					ToolStripItemGlyph toolStripItemGlyph = new ToolStripItemGlyph(item, toolStripItemDesigner, glyphBounds, behavior);
					toolStripItemDesigner.bodyGlyph = toolStripItemGlyph;
					if (this.toolStripAdornerWindowService != null)
					{
						this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Insert(0, toolStripItemGlyph);
					}
				}
			}
		}

		// Token: 0x06001B4A RID: 6986 RVA: 0x00097244 File Offset: 0x00096244
		private void AddBodyGlyphs(ToolStripDropDownItem item)
		{
			if (item != null)
			{
				ToolStripMenuItemDesigner toolStripMenuItemDesigner = (ToolStripMenuItemDesigner)this.designerHost.GetDesigner(item);
				if (toolStripMenuItemDesigner != null)
				{
					foreach (object obj in item.DropDownItems)
					{
						ToolStripItem toolStripItem = (ToolStripItem)obj;
						this.AddItemBodyGlyph(toolStripItem);
					}
				}
			}
		}

		// Token: 0x06001B4B RID: 6987 RVA: 0x000972B8 File Offset: 0x000962B8
		internal override void CommitEdit(Type type, string text, bool commit, bool enterKeyPressed, bool tabKeyPressed)
		{
			base.IsEditorActive = false;
			if (!(this.MenuItem.Owner is ToolStripDropDown) && base.Editor != null)
			{
				base.CommitEdit(type, text, commit, enterKeyPressed, tabKeyPressed);
				return;
			}
			if (commit)
			{
				int num = -1;
				bool dummyItemAdded = this.dummyItemAdded;
				this.dummyItemAdded = false;
				this.MenuItem.DropDown.SuspendLayout();
				if (this.commitedEditorNode != null)
				{
					num = this.MenuItem.DropDownItems.IndexOf(this.commitedEditorNode);
					ToolStripItem toolStripItem = this.MenuItem.DropDownItems[num + 1];
					this.MenuItem.DropDown.Items.Remove(this.commitedEditorNode);
					if (this.commitedTemplateNode != null)
					{
						this.commitedTemplateNode.CloseEditor();
						this.commitedTemplateNode = null;
					}
					if (this.commitedEditorNode != null)
					{
						this.commitedEditorNode.Dispose();
						this.commitedEditorNode = null;
					}
					if (text == "-")
					{
						ToolStripItemDesigner toolStripItemDesigner = this.designerHost.GetDesigner(toolStripItem) as ToolStripItemDesigner;
						if (toolStripItemDesigner == null)
						{
							goto IL_028C;
						}
						try
						{
							try
							{
								toolStripItem = toolStripItemDesigner.MorphCurrentItem(typeof(ToolStripSeparator));
								this.RemoveItemBodyGlyph(toolStripItem);
							}
							catch
							{
								if (this.newMenuItemTransaction != null)
								{
									try
									{
										this.newMenuItemTransaction.Cancel();
									}
									catch
									{
									}
									this.newMenuItemTransaction = null;
								}
							}
							goto IL_028C;
						}
						finally
						{
							if (this.newMenuItemTransaction != null)
							{
								this.newMenuItemTransaction.Commit();
								this.newMenuItemTransaction = null;
							}
						}
					}
					if (dummyItemAdded)
					{
						try
						{
							try
							{
								this.dummyItemAdded = true;
								this.CreateNewItem(type, num, text);
								this.designerHost.DestroyComponent(toolStripItem);
								if (enterKeyPressed)
								{
									this.typeHereNode.SelectControl();
								}
							}
							catch
							{
								if (this.newMenuItemTransaction != null)
								{
									try
									{
										this.newMenuItemTransaction.Cancel();
									}
									catch
									{
									}
									this.newMenuItemTransaction = null;
								}
							}
							goto IL_028C;
						}
						finally
						{
							if (this.newMenuItemTransaction != null)
							{
								this.newMenuItemTransaction.Commit();
								this.newMenuItemTransaction = null;
							}
							this.dummyItemAdded = false;
						}
					}
					toolStripItem.Visible = true;
					DesignerTransaction designerTransaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripItemPropertyChangeTransaction"));
					try
					{
						try
						{
							PropertyDescriptor propertyDescriptor = TypeDescriptor.GetProperties(toolStripItem)["Text"];
							string text2 = (string)propertyDescriptor.GetValue(toolStripItem);
							if (propertyDescriptor != null && text != text2)
							{
								propertyDescriptor.SetValue(toolStripItem, text);
							}
						}
						catch
						{
							if (designerTransaction != null)
							{
								designerTransaction.Cancel();
								designerTransaction = null;
							}
						}
						goto IL_028C;
					}
					finally
					{
						if (designerTransaction != null)
						{
							designerTransaction.Commit();
							designerTransaction = null;
						}
					}
				}
				num = this.MenuItem.DropDownItems.IndexOf(this.typeHereNode);
				try
				{
					this.dummyItemAdded = true;
					this.CreateNewItem(type, num, text);
				}
				finally
				{
					this.dummyItemAdded = false;
				}
				this.typeHereNode.SelectControl();
				IL_028C:
				this.MenuItem.DropDown.ResumeLayout(true);
				this.MenuItem.DropDown.PerformLayout();
				this.ResetGlyphs(this.MenuItem);
				if (this.selSvc != null)
				{
					if (enterKeyPressed)
					{
						ToolStripItem toolStripItem2;
						if ((this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveLeft || this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveRight) && num >= 1)
						{
							toolStripItem2 = this.MenuItem.DropDownItems[num - 1];
						}
						else
						{
							toolStripItem2 = this.MenuItem.DropDownItems[num + 1];
						}
						if (this.KeyboardHandlingService != null)
						{
							if (toolStripItem2 != null)
							{
								ToolStripDropDownItem toolStripDropDownItem = this.MenuItem.DropDownItems[num] as ToolStripDropDownItem;
								if (toolStripDropDownItem != null)
								{
									toolStripDropDownItem.HideDropDown();
								}
							}
							if (toolStripItem2 == this.typeHereNode)
							{
								this.KeyboardHandlingService.SelectedDesignerControl = toolStripItem2;
								this.selSvc.SetSelectedComponents(null, SelectionTypes.Replace);
								return;
							}
							this.KeyboardHandlingService.SelectedDesignerControl = null;
							this.selSvc.SetSelectedComponents(new object[] { toolStripItem2 });
							return;
						}
					}
					else if (tabKeyPressed)
					{
						this.selSvc.SetSelectedComponents(new object[] { this.MenuItem.DropDownItems[num] }, SelectionTypes.Replace);
						return;
					}
				}
			}
			else if (this.commitedEditorNode != null)
			{
				this.MenuItem.DropDown.SuspendLayout();
				bool flag = this.dummyItemAdded;
				this.dummyItemAdded = false;
				int num2 = this.MenuItem.DropDownItems.IndexOf(this.commitedEditorNode);
				ToolStripItem toolStripItem3 = this.MenuItem.DropDownItems[num2 + 1];
				this.MenuItem.DropDown.Items.Remove(this.commitedEditorNode);
				toolStripItem3.Visible = true;
				if (this.commitedTemplateNode != null)
				{
					this.commitedTemplateNode.CloseEditor();
					this.commitedTemplateNode = null;
				}
				if (this.commitedEditorNode != null)
				{
					this.commitedEditorNode.Dispose();
					this.commitedEditorNode = null;
				}
				if (flag)
				{
					this.MenuItem.DropDownItems.Remove(toolStripItem3);
					try
					{
						this.designerHost.DestroyComponent(toolStripItem3);
					}
					catch
					{
						if (this.newMenuItemTransaction != null)
						{
							try
							{
								this.newMenuItemTransaction.Cancel();
							}
							catch
							{
							}
							this.newMenuItemTransaction = null;
						}
					}
					toolStripItem3 = null;
				}
				this.MenuItem.DropDown.ResumeLayout();
				if (toolStripItem3 != null)
				{
					this.AddItemBodyGlyph(toolStripItem3);
				}
				if (flag)
				{
					SelectionManager selectionManager = (SelectionManager)this.GetService(typeof(SelectionManager));
					selectionManager.NeedRefresh = false;
					if (this.newMenuItemTransaction != null)
					{
						try
						{
							this.dummyItemAdded = true;
							this.newMenuItemTransaction.Cancel();
							this.newMenuItemTransaction = null;
							if (this.MenuItem.DropDownItems.Count == 0)
							{
								this.CreatetypeHereNode();
							}
						}
						finally
						{
							this.dummyItemAdded = false;
						}
					}
					flag = false;
				}
				this.MenuItem.DropDown.PerformLayout();
			}
		}

		// Token: 0x06001B4C RID: 6988 RVA: 0x000978B4 File Offset: 0x000968B4
		private void CreatetypeHereNode()
		{
			if (this.typeHereNode == null)
			{
				this.AddNewTemplateNode(this.MenuItem.DropDown);
				if (this.MenuItem.DropDown.Site == null)
				{
					this.MenuItem.DropDown.Text = this.MenuItem.Name + ".DropDown";
				}
			}
			else if (this.typeHereNode != null && this.MenuItem.DropDownItems.IndexOf(this.typeHereNode) == -1)
			{
				this.MenuItem.DropDown.Items.Add(this.typeHereNode);
				this.typeHereNode.Visible = true;
			}
			this.MenuItem.DropDown.PerformLayout();
		}

		// Token: 0x06001B4D RID: 6989 RVA: 0x0009796C File Offset: 0x0009696C
		private void CreateDummyMenuItem(ToolStripItem item, string text, Image image)
		{
			this.commitedTemplateNode = new ToolStripTemplateNode(base.Component, text, image);
			this.commitedTemplateNode.ActiveItem = item;
			int width = this.commitedTemplateNode.EditorToolStrip.Width;
			this.commitedEditorNode = new DesignerToolStripControlHost(this.commitedTemplateNode.EditorToolStrip);
			this.commitedEditorNode.AutoSize = false;
			this.commitedEditorNode.Width = width;
		}

		// Token: 0x06001B4E RID: 6990 RVA: 0x000979D8 File Offset: 0x000969D8
		private ToolStripItem CreateDummyItem(Type t, int dummyIndex)
		{
			if (this.designerHost == null)
			{
				return null;
			}
			ToolStripItem toolStripItem = null;
			if (this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveLeft || this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveRight)
			{
				dummyIndex++;
			}
			try
			{
				ToolStripDesigner._autoAddNewItems = false;
				this.indexToInsertNewItem = dummyIndex;
				try
				{
					if (this.newMenuItemTransaction == null)
					{
						this.newMenuItemTransaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripCreatingNewItemTransaction"));
					}
					this.fireComponentChanged = true;
					toolStripItem = (ToolStripItem)this.designerHost.CreateComponent(t);
				}
				finally
				{
					this.fireComponentChanged = false;
				}
				ToolStripItemDesigner toolStripItemDesigner = this.designerHost.GetDesigner(toolStripItem) as ToolStripItemDesigner;
				try
				{
					toolStripItemDesigner.InternalCreate = true;
					if (toolStripItemDesigner != null)
					{
						toolStripItemDesigner.InitializeNewComponent(null);
					}
				}
				finally
				{
					toolStripItemDesigner.InternalCreate = false;
				}
			}
			catch (InvalidOperationException ex)
			{
				this.CommitInsertTransaction(false);
				if (this.newMenuItemTransaction != null)
				{
					this.newMenuItemTransaction.Cancel();
					this.newMenuItemTransaction = null;
				}
				IUIService iuiservice = (IUIService)this.GetService(typeof(IUIService));
				iuiservice.ShowError(ex.Message);
			}
			finally
			{
				ToolStripDesigner._autoAddNewItems = true;
				this.indexToInsertNewItem = -1;
			}
			return toolStripItem;
		}

		// Token: 0x06001B4F RID: 6991 RVA: 0x00097B20 File Offset: 0x00096B20
		private ToolStripItem CreateNewItem(Type t, int dummyIndex, string newText)
		{
			if (this.designerHost == null)
			{
				return null;
			}
			ToolStripItem toolStripItem = null;
			if (this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveLeft || this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveRight)
			{
				dummyIndex++;
			}
			DesignerTransaction designerTransaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripCreatingNewItemTransaction"));
			try
			{
				ToolStripDesigner._autoAddNewItems = false;
				this.indexToInsertNewItem = dummyIndex;
				try
				{
					this.fireComponentChanged = true;
					toolStripItem = (ToolStripItem)this.designerHost.CreateComponent(t, ToolStripDesigner.NameFromText(newText, t, this.MenuItem.Site));
				}
				finally
				{
					this.fireComponentChanged = false;
				}
				ToolStripItemDesigner toolStripItemDesigner = this.designerHost.GetDesigner(toolStripItem) as ToolStripItemDesigner;
				try
				{
					if (!string.IsNullOrEmpty(newText) || this.addingDummyItem)
					{
						toolStripItemDesigner.InternalCreate = true;
					}
					if (toolStripItemDesigner != null)
					{
						toolStripItemDesigner.InitializeNewComponent(null);
					}
				}
				finally
				{
					toolStripItemDesigner.InternalCreate = false;
				}
				if (toolStripItem != null)
				{
					PropertyDescriptor propertyDescriptor = TypeDescriptor.GetProperties(toolStripItem)["Text"];
					if (propertyDescriptor != null && !string.IsNullOrEmpty(newText))
					{
						propertyDescriptor.SetValue(toolStripItem, newText);
					}
				}
			}
			catch
			{
				this.CommitInsertTransaction(false);
				if (designerTransaction != null)
				{
					designerTransaction.Cancel();
					designerTransaction = null;
				}
			}
			finally
			{
				if (designerTransaction != null)
				{
					designerTransaction.Commit();
					designerTransaction = null;
				}
				ToolStripDesigner._autoAddNewItems = true;
				this.indexToInsertNewItem = -1;
			}
			return toolStripItem;
		}

		// Token: 0x06001B50 RID: 6992 RVA: 0x00097C7C File Offset: 0x00096C7C
		private bool CheckSameOwner(ToolStripDropDownItem lastSelected, ToolStripDropDownItem currentSelected)
		{
			if (lastSelected != null && currentSelected != null && lastSelected.Owner is ToolStripDropDown && currentSelected.Owner is ToolStripDropDown)
			{
				ToolStripItem ownerItem = ((ToolStripDropDown)lastSelected.Owner).OwnerItem;
				ToolStripItem ownerItem2 = ((ToolStripDropDown)currentSelected.Owner).OwnerItem;
				return ownerItem == ownerItem2;
			}
			return false;
		}

		// Token: 0x06001B51 RID: 6993 RVA: 0x00097CD4 File Offset: 0x00096CD4
		internal void Commit()
		{
			if (this.commitedTemplateNode != null && this.commitedTemplateNode.Active)
			{
				int num = this.MenuItem.DropDownItems.IndexOf(this.commitedEditorNode);
				this.commitedTemplateNode.Commit(false, false);
				if (num != -1 && this.MenuItem.DropDownItems.Count > num)
				{
					ToolStripDropDownItem toolStripDropDownItem = this.MenuItem.DropDownItems[num] as ToolStripDropDownItem;
					if (toolStripDropDownItem != null)
					{
						toolStripDropDownItem.HideDropDown();
					}
				}
			}
			else if (this.typeHereTemplateNode != null && this.typeHereTemplateNode.Active)
			{
				this.typeHereTemplateNode.Commit(false, false);
			}
			ToolStripDropDownItem toolStripDropDownItem2 = this.MenuItem;
			while (toolStripDropDownItem2 != null && toolStripDropDownItem2.Owner is ToolStripDropDown)
			{
				toolStripDropDownItem2 = (ToolStripDropDownItem)((ToolStripDropDown)toolStripDropDownItem2.Owner).OwnerItem;
				if (toolStripDropDownItem2 != null)
				{
					ToolStripMenuItemDesigner toolStripMenuItemDesigner = (ToolStripMenuItemDesigner)this.designerHost.GetDesigner(toolStripDropDownItem2);
					if (toolStripMenuItemDesigner != null)
					{
						toolStripMenuItemDesigner.Commit();
					}
				}
			}
		}

		// Token: 0x06001B52 RID: 6994 RVA: 0x00097DC4 File Offset: 0x00096DC4
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				if (this.selSvc != null)
				{
					this.selSvc.SelectionChanged -= this.OnSelectionChanged;
				}
				if (this.undoEngine != null)
				{
					this.undoEngine.Undoing -= this.OnUndoing;
					this.undoEngine.Undone -= this.OnUndone;
				}
				if (this.MenuItem != null)
				{
					this.MenuItem.DropDown.Hide();
					this.UnHookEvents();
				}
				if (this.toolStripAdornerWindowService != null)
				{
					this.toolStripAdornerWindowService = null;
				}
				IComponentChangeService componentChangeService = (IComponentChangeService)this.GetService(typeof(IComponentChangeService));
				if (componentChangeService != null)
				{
					componentChangeService.ComponentRemoved -= this.ComponentChangeSvc_ComponentRemoved;
					componentChangeService.ComponentRemoving -= this.ComponentChangeSvc_ComponentRemoving;
					componentChangeService.ComponentAdding -= this.ComponentChangeSvc_ComponentAdding;
					componentChangeService.ComponentAdded -= this.ComponentChangeSvc_ComponentAdded;
				}
				if (this.typeHereTemplateNode != null)
				{
					this.typeHereTemplateNode.RollBack();
					this.typeHereTemplateNode.CloseEditor();
					this.typeHereTemplateNode = null;
				}
				if (this.typeHereNode != null)
				{
					this.typeHereNode.Dispose();
					this.typeHereNode = null;
				}
				if (this.commitedTemplateNode != null)
				{
					this.commitedTemplateNode.RollBack();
					this.commitedTemplateNode.CloseEditor();
					this.commitedTemplateNode = null;
				}
				if (this.commitedEditorNode != null)
				{
					this.commitedEditorNode.Dispose();
					this.commitedEditorNode = null;
				}
				if (this.parentItem != null)
				{
					this.parentItem = null;
				}
			}
			base.Dispose(disposing);
		}

		// Token: 0x06001B53 RID: 6995 RVA: 0x00097F4E File Offset: 0x00096F4E
		private void DropDownClick(object sender, EventArgs e)
		{
			if (this.KeyboardHandlingService != null && this.KeyboardHandlingService.TemplateNodeActive)
			{
				this.KeyboardHandlingService.ActiveTemplateNode.CommitAndSelect();
			}
		}

		// Token: 0x06001B54 RID: 6996 RVA: 0x00097F78 File Offset: 0x00096F78
		private void DropDownPaint(object sender, PaintEventArgs e)
		{
			if (this.selSvc != null && this.MenuItem != null)
			{
				foreach (object obj in this.MenuItem.DropDownItems)
				{
					ToolStripItem toolStripItem = (ToolStripItem)obj;
					if (toolStripItem.Visible && this.selSvc.GetComponentSelected(toolStripItem))
					{
						ToolStripItemDesigner toolStripItemDesigner = this.designerHost.GetDesigner(toolStripItem) as ToolStripItemDesigner;
						if (toolStripItemDesigner != null)
						{
							Rectangle glyphBounds = toolStripItemDesigner.GetGlyphBounds();
							ToolStripDesignerUtils.GetAdjustedBounds(toolStripItem, ref glyphBounds);
							glyphBounds.Inflate(2, 2);
							BehaviorService behaviorService = (BehaviorService)this.GetService(typeof(BehaviorService));
							if (behaviorService != null)
							{
								behaviorService.ProcessPaintMessage(glyphBounds);
							}
						}
					}
					DesignerToolStripControlHost designerToolStripControlHost = toolStripItem as DesignerToolStripControlHost;
					if (designerToolStripControlHost != null)
					{
						designerToolStripControlHost.Control.Refresh();
					}
				}
			}
		}

		// Token: 0x06001B55 RID: 6997 RVA: 0x00098070 File Offset: 0x00097070
		private void DropDownLocationChanged(object sender, EventArgs e)
		{
			ToolStripDropDown toolStripDropDown = sender as ToolStripDropDown;
			if (toolStripDropDown.Visible)
			{
				BehaviorService behaviorService = (BehaviorService)this.GetService(typeof(BehaviorService));
				if (behaviorService != null)
				{
					behaviorService.Invalidate();
				}
			}
		}

		// Token: 0x06001B56 RID: 6998 RVA: 0x000980AC File Offset: 0x000970AC
		private void DropDownItem_DropDownOpening(object sender, EventArgs e)
		{
			ToolStripDropDownItem toolStripDropDownItem = sender as ToolStripDropDownItem;
			if (this.toolStripAdornerWindowService != null)
			{
				toolStripDropDownItem.DropDown.TopLevel = false;
				toolStripDropDownItem.DropDown.Parent = this.toolStripAdornerWindowService.ToolStripAdornerWindowControl;
			}
		}

		// Token: 0x06001B57 RID: 6999 RVA: 0x000980EC File Offset: 0x000970EC
		private void DropDownItem_DropDownOpened(object sender, EventArgs e)
		{
			ToolStripDropDownItem toolStripDropDownItem = sender as ToolStripDropDownItem;
			if (toolStripDropDownItem != null)
			{
				this.ResetGlyphs(toolStripDropDownItem);
			}
			Control dropDown = toolStripDropDownItem.DropDown;
			if (dropDown != null)
			{
				ControlDesigner controlDesigner = this.designerHost.GetDesigner(this.designerHost.RootComponent) as ControlDesigner;
				if (controlDesigner != null)
				{
					this.rootControlGlyph = new ToolStripMenuItemDesigner.ToolStripDropDownGlyph(dropDown.Bounds, new ToolStripMenuItemDesigner.DropDownBehavior(controlDesigner, this));
				}
				if (this.toolStripAdornerWindowService != null)
				{
					this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Add(this.rootControlGlyph);
				}
			}
		}

		// Token: 0x06001B58 RID: 7000 RVA: 0x00098170 File Offset: 0x00097170
		private void DropDownItem_DropDownClosed(object sender, EventArgs e)
		{
			ToolStripDropDownItem toolStripDropDownItem = sender as ToolStripDropDownItem;
			if (toolStripDropDownItem != null)
			{
				if (this.toolStripAdornerWindowService != null && this.rootControlGlyph != null && this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Contains(this.rootControlGlyph))
				{
					this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Remove(this.rootControlGlyph);
				}
				this.InitializeBodyGlyphsForItems(false, toolStripDropDownItem);
				this.initialized = false;
				this.UnHookEvents();
				if (toolStripDropDownItem.DropDown.Site != null || toolStripDropDownItem.DropDownItems.Count == 1)
				{
					this.RemoveTypeHereNode(toolStripDropDownItem);
					return;
				}
				if (this.toolStripAdornerWindowService != null)
				{
					this.toolStripAdornerWindowService.Invalidate(toolStripDropDownItem.DropDown.Bounds);
				}
			}
		}

		// Token: 0x06001B59 RID: 7001 RVA: 0x00098228 File Offset: 0x00097228
		private void DropDownResize(object sender, EventArgs e)
		{
			ToolStripDropDown toolStripDropDown = sender as ToolStripDropDown;
			if (!this.dummyItemAdded)
			{
				if (toolStripDropDown != null && toolStripDropDown.Visible && this.toolStripAdornerWindowService != null && (toolStripDropDown.Width < this.dropDownSizeToInvalidate.Width || toolStripDropDown.Size.Height < this.dropDownSizeToInvalidate.Height))
				{
					using (Region region = new Region(this.dropDownSizeToInvalidate))
					{
						region.Exclude(toolStripDropDown.Bounds);
						this.toolStripAdornerWindowService.Invalidate(region);
						BehaviorService behaviorService = (BehaviorService)this.GetService(typeof(BehaviorService));
						if (behaviorService != null)
						{
							behaviorService.Invalidate(region);
						}
					}
				}
				if (this.toolStripAdornerWindowService != null)
				{
					if (this.rootControlGlyph != null && this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Contains(this.rootControlGlyph))
					{
						this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Remove(this.rootControlGlyph);
					}
					ControlDesigner controlDesigner = this.designerHost.GetDesigner(this.designerHost.RootComponent) as ControlDesigner;
					if (controlDesigner != null)
					{
						this.rootControlGlyph = new ToolStripMenuItemDesigner.ToolStripDropDownGlyph(toolStripDropDown.Bounds, new ToolStripMenuItemDesigner.DropDownBehavior(controlDesigner, this));
					}
					this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Add(this.rootControlGlyph);
				}
			}
			this.dropDownSizeToInvalidate = toolStripDropDown.Bounds;
		}

		// Token: 0x06001B5A RID: 7002 RVA: 0x0009839C File Offset: 0x0009739C
		internal void EditTemplateNode(bool clicked)
		{
			this.typeHereNode.RefreshSelectionGlyph();
			if (this.KeyboardHandlingService != null && this.KeyboardHandlingService.TemplateNodeActive)
			{
				this.KeyboardHandlingService.ActiveTemplateNode.CommitAndSelect();
			}
			if (clicked && this.MenuItem == null)
			{
				return;
			}
			try
			{
				ToolStripDesigner.editTemplateNode = true;
				this.selSvc.SetSelectedComponents(new object[] { this.MenuItem }, SelectionTypes.Replace);
			}
			finally
			{
				ToolStripDesigner.editTemplateNode = false;
			}
			ToolStripDropDownItem toolStripDropDownItem = null;
			if (this.selSvc.PrimarySelection == null && this.KeyboardHandlingService != null)
			{
				ToolStripItem toolStripItem = this.KeyboardHandlingService.SelectedDesignerControl as ToolStripItem;
				if (toolStripItem != null)
				{
					toolStripDropDownItem = ((ToolStripDropDown)toolStripItem.Owner).OwnerItem as ToolStripDropDownItem;
				}
			}
			else
			{
				toolStripDropDownItem = this.selSvc.PrimarySelection as ToolStripDropDownItem;
			}
			if (toolStripDropDownItem != null && toolStripDropDownItem != this.MenuItem)
			{
				this.HideSiblingDropDowns(toolStripDropDownItem);
			}
			this.MenuItem.DropDown.SuspendLayout();
			this.dummyItemAdded = true;
			int num = this.MenuItem.DropDownItems.IndexOf(this.typeHereNode);
			ToolStripItem toolStripItem2 = null;
			try
			{
				this.addingDummyItem = true;
				toolStripItem2 = this.CreateDummyItem(typeof(ToolStripMenuItem), num);
			}
			catch (CheckoutException ex)
			{
				if (!ex.Equals(CheckoutException.Canceled))
				{
					throw;
				}
				this.CommitInsertTransaction(false);
				if (this.newMenuItemTransaction != null)
				{
					this.newMenuItemTransaction.Cancel();
					this.newMenuItemTransaction = null;
				}
			}
			finally
			{
				this.dummyItemAdded = toolStripItem2 != null;
				this.addingDummyItem = false;
			}
			this.MenuItem.DropDown.ResumeLayout();
			if (toolStripItem2 != null)
			{
				ToolStripMenuItemDesigner toolStripMenuItemDesigner = this.designerHost.GetDesigner(toolStripItem2) as ToolStripMenuItemDesigner;
				if (toolStripMenuItemDesigner != null)
				{
					toolStripMenuItemDesigner.InitializeDropDown();
					toolStripMenuItemDesigner.ShowEditNode(clicked);
				}
			}
		}

		// Token: 0x06001B5B RID: 7003 RVA: 0x00098578 File Offset: 0x00097578
		private void EnterInSituMode()
		{
			if (this.MenuItem.Owner is ToolStripDropDown)
			{
				ToolStripItem ownerItem = ((ToolStripDropDown)this.MenuItem.Owner).OwnerItem;
				if (this.designerHost != null)
				{
					IDesigner designer = this.designerHost.GetDesigner(ownerItem);
					if (designer is ToolStripMenuItemDesigner)
					{
						this.MenuItem.HideDropDown();
						((ToolStripMenuItemDesigner)designer).EnterInSituEdit(this.MenuItem);
					}
				}
			}
		}

		// Token: 0x06001B5C RID: 7004 RVA: 0x000985E8 File Offset: 0x000975E8
		internal void EnterInSituEdit(ToolStripItem toolItem)
		{
			this.MenuItem.DropDown.SuspendLayout();
			this.RemoveItemBodyGlyph(toolItem);
			if (toolItem == null)
			{
				return;
			}
			if (base.IsEditorActive)
			{
				return;
			}
			this.CreateDummyMenuItem(toolItem, toolItem.Text, toolItem.Image);
			int num = this.MenuItem.DropDownItems.IndexOf(toolItem);
			this.MenuItem.DropDownItems.Insert(num, this.commitedEditorNode);
			if (toolItem is ToolStripControlHost)
			{
				((ToolStripControlHost)toolItem).Control.Visible = false;
			}
			toolItem.Visible = false;
			this.MenuItem.DropDown.ResumeLayout();
			if (this.commitedTemplateNode != null)
			{
				this.commitedTemplateNode.FocusEditor(toolItem);
			}
			ToolStripDropDownItem toolStripDropDownItem = toolItem as ToolStripDropDownItem;
			if (!(toolStripDropDownItem.Owner is ToolStripDropDownMenu) && toolStripDropDownItem != null && toolStripDropDownItem.Bounds.Width < this.commitedEditorNode.Bounds.Width)
			{
				toolStripDropDownItem.Width = this.commitedEditorNode.Width;
				toolStripDropDownItem.DropDown.Location = new Point(toolStripDropDownItem.DropDown.Location.X + this.commitedEditorNode.Bounds.Width - toolStripDropDownItem.Bounds.Width, toolStripDropDownItem.DropDown.Location.Y);
			}
			base.IsEditorActive = true;
		}

		// Token: 0x06001B5D RID: 7005 RVA: 0x00098750 File Offset: 0x00097750
		private int GetItemInsertionIndex(ToolStripDropDown wb, Point ownerClientAreaRelativeDropPoint)
		{
			for (int i = 0; i < wb.Items.Count; i++)
			{
				Rectangle bounds = wb.Items[i].Bounds;
				bounds.Inflate(wb.Items[i].Margin.Size);
				if (bounds.Contains(ownerClientAreaRelativeDropPoint))
				{
					return wb.Items.IndexOf(wb.Items[i]);
				}
			}
			return -1;
		}

		// Token: 0x06001B5E RID: 7006 RVA: 0x000987C8 File Offset: 0x000977C8
		protected override Component GetOwnerForActionList()
		{
			return this.MenuItem;
		}

		// Token: 0x06001B5F RID: 7007 RVA: 0x000987D0 File Offset: 0x000977D0
		internal override ToolStrip GetMainToolStrip()
		{
			ToolStripDropDown firstDropDown = base.GetFirstDropDown(this.MenuItem);
			ToolStripItem toolStripItem = ((firstDropDown == null) ? null : firstDropDown.OwnerItem);
			if (toolStripItem != null)
			{
				return toolStripItem.Owner;
			}
			return this.MenuItem.Owner;
		}

		// Token: 0x06001B60 RID: 7008 RVA: 0x0009880C File Offset: 0x0009780C
		private void HideAllDropDowns(ToolStripDropDownItem item)
		{
			try
			{
				if (this.MenuItem.Owner is ToolStripDropDown)
				{
					ToolStripItem ownerItem = ((ToolStripDropDown)this.MenuItem.Owner).OwnerItem;
					while (item != ownerItem)
					{
						if (item.DropDown.Visible)
						{
							item.HideDropDown();
						}
						if (!(item.Owner is ToolStripDropDown))
						{
							break;
						}
						item = (ToolStripDropDownItem)((ToolStripDropDown)item.Owner).OwnerItem;
					}
				}
			}
			catch (Exception ex)
			{
				if (ClientUtils.IsCriticalException(ex))
				{
					throw;
				}
			}
		}

		// Token: 0x06001B61 RID: 7009 RVA: 0x000988A4 File Offset: 0x000978A4
		private void HideSiblingDropDowns(ToolStripDropDownItem item)
		{
			try
			{
				ToolStripItem menuItem = this.MenuItem;
				while (item != menuItem)
				{
					item.HideDropDown();
					if (!(item.Owner is ToolStripDropDown))
					{
						break;
					}
					item = (ToolStripDropDownItem)((ToolStripDropDown)item.Owner).OwnerItem;
				}
			}
			catch (Exception ex)
			{
				if (ClientUtils.IsCriticalException(ex))
				{
					throw;
				}
			}
		}

		// Token: 0x06001B62 RID: 7010 RVA: 0x0009890C File Offset: 0x0009790C
		internal void HookEvents()
		{
			if (this.MenuItem != null)
			{
				this.MenuItem.DropDown.Closing += this.OnDropDownClosing;
				this.MenuItem.DropDownOpening += this.DropDownItem_DropDownOpening;
				this.MenuItem.DropDownOpened += this.DropDownItem_DropDownOpened;
				this.MenuItem.DropDownClosed += this.DropDownItem_DropDownClosed;
				this.MenuItem.DropDown.Resize += this.DropDownResize;
				this.MenuItem.DropDown.ItemAdded += this.OnItemAdded;
				this.MenuItem.DropDown.Paint += this.DropDownPaint;
				this.MenuItem.DropDown.Click += this.DropDownClick;
				this.MenuItem.DropDown.LocationChanged += this.DropDownLocationChanged;
			}
		}

		// Token: 0x06001B63 RID: 7011 RVA: 0x00098A14 File Offset: 0x00097A14
		public override void Initialize(IComponent component)
		{
			base.Initialize(component);
			base.Visible = true;
			this.DoubleClickEnabled = this.MenuItem.DoubleClickEnabled;
			this.selSvc = (ISelectionService)this.GetService(typeof(ISelectionService));
			if (this.selSvc != null)
			{
				this.selSvc.SelectionChanged += this.OnSelectionChanged;
			}
			this.toolStripAdornerWindowService = (ToolStripAdornerWindowService)this.GetService(typeof(ToolStripAdornerWindowService));
			this.designerHost = (IDesignerHost)this.GetService(typeof(IDesignerHost));
			this.MenuItem.DoubleClickEnabled = true;
			IComponentChangeService componentChangeService = (IComponentChangeService)this.GetService(typeof(IComponentChangeService));
			if (componentChangeService != null)
			{
				componentChangeService.ComponentRemoved += this.ComponentChangeSvc_ComponentRemoved;
				componentChangeService.ComponentRemoving += this.ComponentChangeSvc_ComponentRemoving;
				componentChangeService.ComponentAdding += this.ComponentChangeSvc_ComponentAdding;
				componentChangeService.ComponentAdded += this.ComponentChangeSvc_ComponentAdded;
			}
			if (this.undoEngine == null)
			{
				this.undoEngine = this.GetService(typeof(UndoEngine)) as UndoEngine;
				if (this.undoEngine != null)
				{
					this.undoEngine.Undoing += this.OnUndoing;
					this.undoEngine.Undone += this.OnUndone;
				}
			}
		}

		// Token: 0x06001B64 RID: 7012 RVA: 0x00098B76 File Offset: 0x00097B76
		internal void InitializeBodyGlyphsForItems(bool addGlyphs, ToolStripDropDownItem item)
		{
			if (addGlyphs)
			{
				this.AddBodyGlyphs(item);
				return;
			}
			this.RemoveBodyGlyphs(item);
		}

		// Token: 0x06001B65 RID: 7013 RVA: 0x00098B8C File Offset: 0x00097B8C
		internal void InitializeDropDown()
		{
			ToolStrip mainToolStrip = this.GetMainToolStrip();
			ToolStripDropDown firstDropDown = base.GetFirstDropDown(this.MenuItem);
			if (firstDropDown != null)
			{
				ToolStripItem ownerItem = firstDropDown.OwnerItem;
				if (ownerItem != null && ownerItem.GetCurrentParent() is ToolStripOverflow && !mainToolStrip.CanOverflow)
				{
					return;
				}
			}
			if (!this.initialized)
			{
				this.initialized = true;
				ToolStripDropDownItem toolStripDropDownItem = this.MenuItem.DropDown.OwnerItem as ToolStripDropDownItem;
				if (toolStripDropDownItem != null && toolStripDropDownItem != this.MenuItem)
				{
					ToolStripMenuItemDesigner toolStripMenuItemDesigner = this.designerHost.GetDesigner(toolStripDropDownItem) as ToolStripMenuItemDesigner;
					if (toolStripMenuItemDesigner != null)
					{
						toolStripMenuItemDesigner.RemoveTypeHereNode(toolStripDropDownItem);
					}
					toolStripDropDownItem.HideDropDown();
				}
				if (this.MenuItem.DropDown.Site != null)
				{
					ToolStripDropDownDesigner toolStripDropDownDesigner = this.designerHost.GetDesigner(this.MenuItem.DropDown) as ToolStripDropDownDesigner;
					if (toolStripDropDownDesigner != null)
					{
						toolStripDropDownDesigner.currentParent = this.MenuItem as ToolStripMenuItem;
					}
				}
				this.CreatetypeHereNode();
				this.MenuItem.DropDown.TopLevel = false;
				this.MenuItem.DropDown.AllowDrop = true;
				this.HookEvents();
				this.MenuItem.DropDown.AutoClose = false;
				this.MenuItem.ShowDropDown();
				this.ShowOwnerDropDown(this.MenuItem);
				this.ResetGlyphs(this.MenuItem);
				if (!this.IsOnContextMenu && !this.dummyItemAdded)
				{
					SelectionManager selectionManager = (SelectionManager)this.GetService(typeof(SelectionManager));
					if (selectionManager != null)
					{
						selectionManager.Refresh();
					}
				}
			}
		}

		// Token: 0x06001B66 RID: 7014 RVA: 0x00098D04 File Offset: 0x00097D04
		private bool IsParentDropDown(ToolStripDropDown currentDropDown)
		{
			if (currentDropDown != null)
			{
				ToolStripDropDown toolStripDropDown = this.MenuItem.Owner as ToolStripDropDown;
				while (toolStripDropDown != null && toolStripDropDown != currentDropDown)
				{
					ToolStripDropDownItem toolStripDropDownItem = toolStripDropDown.OwnerItem as ToolStripDropDownItem;
					if (toolStripDropDownItem != null)
					{
						toolStripDropDown = toolStripDropDownItem.Owner as ToolStripDropDown;
					}
					else
					{
						toolStripDropDown = null;
					}
				}
				return toolStripDropDown != null;
			}
			return false;
		}

		// Token: 0x06001B67 RID: 7015 RVA: 0x00098D58 File Offset: 0x00097D58
		internal override ToolStripItem MorphCurrentItem(Type t)
		{
			Rectangle bounds = this.MenuItem.GetCurrentParent().Bounds;
			Rectangle bounds2 = this.MenuItem.DropDown.Bounds;
			this.InitializeBodyGlyphsForItems(false, this.MenuItem);
			Rectangle rectangle = Rectangle.Union(bounds, bounds2);
			ToolStripAdornerWindowService toolStripAdornerWindowService = this.toolStripAdornerWindowService;
			ToolStripItem toolStripItem = base.MorphCurrentItem(t);
			if (toolStripAdornerWindowService != null)
			{
				toolStripAdornerWindowService.Invalidate(rectangle);
			}
			return toolStripItem;
		}

		// Token: 0x06001B68 RID: 7016 RVA: 0x00098DBC File Offset: 0x00097DBC
		private void ComponentChangeSvc_ComponentAdded(object sender, ComponentEventArgs e)
		{
			ToolStripItem toolStripItem = e.Component as ToolStripItem;
			IComponentChangeService componentChangeService = (IComponentChangeService)this.GetService(typeof(IComponentChangeService));
			if (toolStripItem != null && this.componentAddingFired && (this.MenuItemSelected || this.fireComponentChanged))
			{
				this.componentAddingFired = false;
				try
				{
					if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
					{
						if (componentChangeService != null)
						{
							MemberDescriptor memberDescriptor = TypeDescriptor.GetProperties(this.MenuItem.DropDown)["Items"];
							componentChangeService.OnComponentChanging(this.MenuItem.DropDown, memberDescriptor);
						}
					}
					else
					{
						base.RaiseComponentChanging(TypeDescriptor.GetProperties(this.MenuItem)["DropDownItems"]);
					}
					int count = this.MenuItem.DropDownItems.Count;
					if (this.indexToInsertNewItem != -1)
					{
						if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
						{
							this.MenuItem.DropDown.Items.Insert(this.indexToInsertNewItem, toolStripItem);
						}
						else
						{
							this.MenuItem.DropDownItems.Insert(this.indexToInsertNewItem, toolStripItem);
						}
					}
					else
					{
						ToolStripItem toolStripItem2 = this.selSvc.PrimarySelection as ToolStripItem;
						if (toolStripItem2 != null && toolStripItem2 != this.MenuItem)
						{
							int num = this.MenuItem.DropDownItems.IndexOf(toolStripItem2);
							if (this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveLeft || this.MenuItem.DropDownDirection == ToolStripDropDownDirection.AboveRight)
							{
								if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
								{
									this.MenuItem.DropDown.Items.Insert(num + 1, toolStripItem);
								}
								else
								{
									this.MenuItem.DropDownItems.Insert(num + 1, toolStripItem);
								}
							}
							else if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
							{
								this.MenuItem.DropDown.Items.Insert(num, toolStripItem);
							}
							else
							{
								this.MenuItem.DropDownItems.Insert(num, toolStripItem);
							}
						}
						else if (count > 0)
						{
							if (this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveLeft && this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveRight)
							{
								if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
								{
									this.MenuItem.DropDown.Items.Insert(count - 1, toolStripItem);
								}
								else
								{
									this.MenuItem.DropDownItems.Insert(count - 1, toolStripItem);
								}
							}
						}
						else if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
						{
							this.MenuItem.DropDown.Items.Add(toolStripItem);
						}
						else
						{
							this.MenuItem.DropDownItems.Add(toolStripItem);
						}
					}
					if (this.undoingCalled && this.selSvc != null)
					{
						this.selSvc.SetSelectedComponents(new IComponent[] { toolStripItem }, SelectionTypes.Replace);
					}
					this.ResetGlyphs(this.MenuItem);
				}
				catch
				{
					this.CommitInsertTransaction(false);
				}
				finally
				{
					if (this.IsOnContextMenu && this.MenuItem.DropDown.Site != null)
					{
						if (componentChangeService != null)
						{
							MemberDescriptor memberDescriptor2 = TypeDescriptor.GetProperties(this.MenuItem.DropDown)["Items"];
							componentChangeService.OnComponentChanged(this.MenuItem.DropDown, memberDescriptor2, null, null);
						}
					}
					else
					{
						base.RaiseComponentChanged(TypeDescriptor.GetProperties(this.MenuItem)["DropDownItems"], null, null);
					}
					this.CommitInsertTransaction(true);
				}
			}
		}

		// Token: 0x06001B69 RID: 7017 RVA: 0x00099188 File Offset: 0x00098188
		private void CommitInsertTransaction(bool commit)
		{
			if (!this.IsOnContextMenu)
			{
				ToolStrip mainToolStrip = this.GetMainToolStrip();
				ToolStripDesigner toolStripDesigner = this.designerHost.GetDesigner(mainToolStrip) as ToolStripDesigner;
				if (toolStripDesigner != null && toolStripDesigner.InsertTansaction != null)
				{
					if (commit)
					{
						toolStripDesigner.InsertTansaction.Commit();
					}
					else
					{
						toolStripDesigner.InsertTansaction.Cancel();
					}
					toolStripDesigner.InsertTansaction = null;
					return;
				}
			}
			else if (this.insertMenuItemTransaction != null)
			{
				if (commit)
				{
					this.insertMenuItemTransaction.Commit();
				}
				else
				{
					this.insertMenuItemTransaction.Cancel();
				}
				this.insertMenuItemTransaction = null;
			}
		}

		// Token: 0x06001B6A RID: 7018 RVA: 0x00099210 File Offset: 0x00098210
		private void ComponentChangeSvc_ComponentAdding(object sender, ComponentEventArgs e)
		{
			if (this.KeyboardHandlingService != null && this.KeyboardHandlingService.CopyInProgress)
			{
				return;
			}
			if (e.Component is ToolStripItem && (this.MenuItemSelected || this.fireComponentChanged))
			{
				if (!this.IsOnContextMenu)
				{
					ToolStrip mainToolStrip = this.GetMainToolStrip();
					ToolStripDesigner toolStripDesigner = this.designerHost.GetDesigner(mainToolStrip) as ToolStripDesigner;
					if (toolStripDesigner != null && !toolStripDesigner.EditingCollection && toolStripDesigner.InsertTansaction == null)
					{
						this.componentAddingFired = true;
						toolStripDesigner.InsertTansaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripInsertingIntoDropDownTransaction"));
						return;
					}
				}
				else
				{
					ToolStripItem toolStripItem = e.Component as ToolStripItem;
					if (toolStripItem != null && toolStripItem.Owner == null)
					{
						this.componentAddingFired = true;
						this.insertMenuItemTransaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripInsertingIntoDropDownTransaction"));
					}
				}
			}
		}

		// Token: 0x06001B6B RID: 7019 RVA: 0x000992E8 File Offset: 0x000982E8
		private void ComponentChangeSvc_ComponentRemoved(object sender, ComponentEventArgs e)
		{
			ToolStripItem toolStripItem = e.Component as ToolStripItem;
			if (toolStripItem != null && toolStripItem.IsOnDropDown)
			{
				ToolStripDropDownItem toolStripDropDownItem = (ToolStripDropDownItem)((ToolStripDropDown)toolStripItem.Owner).OwnerItem;
				if (toolStripDropDownItem != null && toolStripDropDownItem == this.MenuItem)
				{
					int num = toolStripDropDownItem.DropDownItems.IndexOf(toolStripItem);
					try
					{
						if (num != -1)
						{
							toolStripDropDownItem.DropDownItems.Remove(toolStripItem);
							base.RaiseComponentChanged(TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"], null, null);
						}
					}
					finally
					{
						if (this._pendingTransaction != null)
						{
							this._pendingTransaction.Commit();
							this._pendingTransaction = null;
						}
					}
					this.ResetGlyphs(toolStripDropDownItem);
					if (toolStripDropDownItem.DropDownItems.Count > 1)
					{
						num = Math.Min(toolStripDropDownItem.DropDownItems.Count - 1, num);
						num = Math.Max(0, num);
					}
					else
					{
						num = -1;
					}
					if (this.toolStripAdornerWindowService != null && this.boundsToInvalidateOnRemove != Rectangle.Empty)
					{
						using (Region region = new Region(this.boundsToInvalidateOnRemove))
						{
							region.Exclude(this.MenuItem.DropDown.Bounds);
							this.toolStripAdornerWindowService.Invalidate(region);
							this.boundsToInvalidateOnRemove = Rectangle.Empty;
						}
					}
					if (this.KeyboardHandlingService != null && this.KeyboardHandlingService.CutOrDeleteInProgress && this.selSvc != null && !this.dummyItemAdded)
					{
						IComponent component2;
						if (num != -1)
						{
							IComponent component = toolStripDropDownItem.DropDownItems[num];
							component2 = component;
						}
						else
						{
							component2 = toolStripDropDownItem;
						}
						IComponent component3 = component2;
						if (component3 is DesignerToolStripControlHost)
						{
							this.KeyboardHandlingService.SelectedDesignerControl = component3;
							this.KeyboardHandlingService.OwnerItemAfterCut = this.MenuItem;
							this.selSvc.SetSelectedComponents(null, SelectionTypes.Replace);
							return;
						}
						this.selSvc.SetSelectedComponents(new IComponent[] { component3 }, SelectionTypes.Replace);
					}
				}
			}
		}

		// Token: 0x06001B6C RID: 7020 RVA: 0x000994D0 File Offset: 0x000984D0
		private void ComponentChangeSvc_ComponentRemoving(object sender, ComponentEventArgs e)
		{
			if (this.dummyItemAdded)
			{
				return;
			}
			ToolStripItem toolStripItem = e.Component as ToolStripItem;
			if (toolStripItem != null && toolStripItem.IsOnDropDown && toolStripItem.Placement == ToolStripItemPlacement.Main)
			{
				ToolStripDropDownItem toolStripDropDownItem = (ToolStripDropDownItem)((ToolStripDropDown)toolStripItem.Owner).OwnerItem;
				if (toolStripDropDownItem != null && toolStripDropDownItem == this.MenuItem)
				{
					this.RemoveItemBodyGlyph(toolStripItem);
					this.InitializeBodyGlyphsForItems(false, toolStripDropDownItem);
					this.boundsToInvalidateOnRemove = toolStripDropDownItem.DropDown.Bounds;
					ToolStripDropDownItem toolStripDropDownItem2 = toolStripItem as ToolStripDropDownItem;
					if (toolStripDropDownItem2 != null)
					{
						this.boundsToInvalidateOnRemove = Rectangle.Union(this.boundsToInvalidateOnRemove, toolStripDropDownItem2.DropDown.Bounds);
					}
					try
					{
						this._pendingTransaction = this.designerHost.CreateTransaction(SR.GetString("ToolStripDesignerTransactionRemovingItem"));
						base.RaiseComponentChanging(TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"]);
					}
					catch
					{
						if (this._pendingTransaction != null)
						{
							this._pendingTransaction.Cancel();
							this._pendingTransaction = null;
						}
					}
				}
			}
		}

		// Token: 0x06001B6D RID: 7021 RVA: 0x000995DC File Offset: 0x000985DC
		private void OnDropDownClosing(object sender, ToolStripDropDownClosingEventArgs e)
		{
			e.Cancel = e.CloseReason == ToolStripDropDownCloseReason.ItemClicked;
		}

		// Token: 0x06001B6E RID: 7022 RVA: 0x000995ED File Offset: 0x000985ED
		private void OnDropDownDisposed(object sender, EventArgs e)
		{
			if (this.MenuItem != null)
			{
				if (this.MenuItem.DropDown != null)
				{
					this.MenuItem.DropDown.Disposed -= this.OnDropDownDisposed;
				}
				this.MenuItem.DropDown = null;
			}
		}

		// Token: 0x06001B6F RID: 7023 RVA: 0x0009962C File Offset: 0x0009862C
		private void OnItemAdded(object sender, ToolStripItemEventArgs e)
		{
			if (this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveLeft && this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveRight && this.typeHereNode != null && e.Item != this.typeHereNode)
			{
				int num = this.MenuItem.DropDown.Items.IndexOf(this.typeHereNode);
				if (num >= 0 && num < this.MenuItem.DropDown.Items.Count - 1)
				{
					this.MenuItem.DropDown.ItemAdded -= this.OnItemAdded;
					this.MenuItem.DropDown.SuspendLayout();
					this.MenuItem.DropDown.Items.Remove(this.typeHereNode);
					this.MenuItem.DropDown.Items.Add(this.typeHereNode);
					this.MenuItem.DropDown.ResumeLayout();
					this.MenuItem.DropDown.ItemAdded += this.OnItemAdded;
					return;
				}
				this.CreatetypeHereNode();
			}
		}

		// Token: 0x06001B70 RID: 7024 RVA: 0x0009974C File Offset: 0x0009874C
		private void OnUndone(object source, EventArgs e)
		{
			if (this.undoingCalled)
			{
				if (this.dropDownSet && this.MenuItem.DropDown.IsAutoGenerated)
				{
					ToolStrip mainToolStrip = this.GetMainToolStrip();
					ToolStripDesigner toolStripDesigner = this.designerHost.GetDesigner(mainToolStrip) as ToolStripDesigner;
					if (toolStripDesigner != null && toolStripDesigner.CacheItems)
					{
						foreach (object obj in toolStripDesigner.Items)
						{
							ToolStripItem toolStripItem = (ToolStripItem)obj;
							this.MenuItem.DropDownItems.Insert(0, toolStripItem);
						}
						toolStripDesigner.CacheItems = false;
					}
					this.ResetGlyphs(this.MenuItem);
				}
				if (this.MenuItem != null && this.selSvc.GetComponentSelected(this.MenuItem))
				{
					this.InitializeDropDown();
					this.MenuItem.DropDown.PerformLayout();
				}
				this.undoingCalled = false;
				this.dropDownSet = false;
			}
			if (this.selSvc.GetComponentSelected(this.MenuItem) && !this.dropDownSetFailed)
			{
				this.InitializeDropDown();
			}
		}

		// Token: 0x06001B71 RID: 7025 RVA: 0x00099878 File Offset: 0x00098878
		private void OnUndoing(object source, EventArgs e)
		{
			if (this.dummyItemAdded)
			{
				return;
			}
			if (!this.IsOnContextMenu && this.MenuItem.DropDown.Visible)
			{
				this.MenuItem.HideDropDown();
				if (!this.MenuItem.DropDown.IsAutoGenerated)
				{
					this.dropDownSet = true;
					ToolStrip mainToolStrip = this.GetMainToolStrip();
					ToolStripDesigner toolStripDesigner = this.designerHost.GetDesigner(mainToolStrip) as ToolStripDesigner;
					if (toolStripDesigner != null)
					{
						toolStripDesigner.CacheItems = true;
						toolStripDesigner.Items.Clear();
					}
				}
				this.undoingCalled = true;
			}
		}

		// Token: 0x06001B72 RID: 7026 RVA: 0x00099904 File Offset: 0x00098904
		private void OnSelectionChanged(object sender, EventArgs e)
		{
			if (this.MenuItem == null)
			{
				return;
			}
			ISelectionService selectionService = sender as ISelectionService;
			if (selectionService == null)
			{
				return;
			}
			if (this.commitedTemplateNode != null && this.commitedTemplateNode.Active)
			{
				this.commitedTemplateNode.Commit(false, false);
			}
			else if (this.typeHereTemplateNode != null && this.typeHereTemplateNode.Active)
			{
				this.typeHereTemplateNode.Commit(false, false);
			}
			if (this.MenuItem.Equals(selectionService.PrimarySelection))
			{
				ArrayList arrayList = ToolStripDesignerUtils.originalSelComps;
				if (arrayList != null)
				{
					ToolStripDesignerUtils.InvalidateSelection(arrayList, this.MenuItem, this.MenuItem.Site, false);
				}
				if (this.IsOnContextMenu && !this.MenuItem.Owner.Visible)
				{
					ToolStripDropDown firstDropDown = base.GetFirstDropDown(this.MenuItem);
					ToolStripDropDownDesigner toolStripDropDownDesigner = this.designerHost.GetDesigner(firstDropDown) as ToolStripDropDownDesigner;
					if (toolStripDropDownDesigner != null)
					{
						this.InitializeDropDown();
						toolStripDropDownDesigner.ShowMenu();
						toolStripDropDownDesigner.AddSelectionGlyphs();
					}
				}
				else
				{
					this.InitializeDropDown();
				}
				ICollection collection = null;
				if (this.selSvc != null)
				{
					collection = selectionService.GetSelectedComponents();
				}
				arrayList = new ArrayList(collection);
				if (arrayList.Count == 0 && this.KeyboardHandlingService != null && this.KeyboardHandlingService.SelectedDesignerControl != null)
				{
					arrayList.Add(this.KeyboardHandlingService.SelectedDesignerControl);
				}
				if (arrayList.Count > 0)
				{
					ToolStripDesignerUtils.originalSelComps = arrayList;
					return;
				}
			}
			else
			{
				object obj = ((ISelectionService)sender).PrimarySelection;
				if (obj == null && this.KeyboardHandlingService != null)
				{
					obj = this.KeyboardHandlingService.SelectedDesignerControl;
				}
				ToolStripItem toolStripItem = obj as ToolStripItem;
				if (toolStripItem != null)
				{
					for (ToolStripDropDown toolStripDropDown = toolStripItem.Owner as ToolStripDropDown; toolStripDropDown != null; toolStripDropDown = toolStripDropDown.OwnerItem.Owner as ToolStripDropDown)
					{
						if (toolStripDropDown.OwnerItem == this.MenuItem || toolStripDropDown.OwnerItem == null)
						{
							return;
						}
					}
				}
				if (this.MenuItem.DropDown.Visible)
				{
					ToolStripDropDown toolStripDropDown2 = obj as ToolStripDropDown;
					if (toolStripDropDown2 != null && this.MenuItem.DropDown == toolStripDropDown2)
					{
						return;
					}
					ToolStripItem toolStripItem2 = obj as ToolStripItem;
					if (toolStripItem2 != null)
					{
						for (ToolStripDropDown toolStripDropDown3 = toolStripItem2.Owner as ToolStripDropDown; toolStripDropDown3 != null; toolStripDropDown3 = toolStripDropDown3.OwnerItem.Owner as ToolStripDropDown)
						{
							if (toolStripDropDown3 == this.MenuItem.DropDown)
							{
								return;
							}
						}
					}
					if (this.MenuItem.DropDown.OwnerItem == this.MenuItem)
					{
						this.MenuItem.HideDropDown();
					}
				}
			}
		}

		// Token: 0x06001B73 RID: 7027 RVA: 0x00099B64 File Offset: 0x00098B64
		protected override void PreFilterProperties(IDictionary properties)
		{
			base.PreFilterProperties(properties);
			string[] array = new string[] { "Visible", "DoubleClickEnabled", "CheckOnClick", "DropDown" };
			Attribute[] array2 = new Attribute[0];
			for (int i = 0; i < array.Length; i++)
			{
				PropertyDescriptor propertyDescriptor = (PropertyDescriptor)properties[array[i]];
				if (propertyDescriptor != null)
				{
					properties[array[i]] = TypeDescriptor.CreateProperty(typeof(ToolStripMenuItemDesigner), propertyDescriptor, array2);
				}
			}
		}

		// Token: 0x06001B74 RID: 7028 RVA: 0x00099BE8 File Offset: 0x00098BE8
		private void ResetDoubleClickEnabled()
		{
			this.DoubleClickEnabled = false;
		}

		// Token: 0x06001B75 RID: 7029 RVA: 0x00099BF1 File Offset: 0x00098BF1
		private void ResetCheckOnClick()
		{
			this.CheckOnClick = false;
		}

		// Token: 0x06001B76 RID: 7030 RVA: 0x00099BFA File Offset: 0x00098BFA
		private void ResetDropDown()
		{
			this.DropDown = null;
		}

		// Token: 0x06001B77 RID: 7031 RVA: 0x00099C03 File Offset: 0x00098C03
		private void ResetVisible()
		{
			base.Visible = true;
		}

		// Token: 0x06001B78 RID: 7032 RVA: 0x00099C0C File Offset: 0x00098C0C
		private void RestoreVisible()
		{
			this.MenuItem.Visible = base.Visible;
		}

		// Token: 0x06001B79 RID: 7033 RVA: 0x00099C20 File Offset: 0x00098C20
		internal void RemoveTypeHereNode(ToolStripDropDownItem ownerItem)
		{
			Rectangle bounds = ownerItem.DropDown.Bounds;
			if (ownerItem.DropDownItems.Count > 0 && ownerItem.DropDownItems[0] is DesignerToolStripControlHost)
			{
				ownerItem.DropDownItems.RemoveAt(0);
			}
			if (this.typeHereTemplateNode != null && this.typeHereTemplateNode.Active)
			{
				this.typeHereTemplateNode.RollBack();
				this.typeHereTemplateNode.CloseEditor();
				this.typeHereTemplateNode = null;
			}
			if (this.typeHereNode != null)
			{
				this.typeHereNode.Dispose();
				this.typeHereNode = null;
			}
			if (this.toolStripAdornerWindowService != null)
			{
				this.toolStripAdornerWindowService.Invalidate(bounds);
			}
		}

		// Token: 0x06001B7A RID: 7034 RVA: 0x00099CC8 File Offset: 0x00098CC8
		private void RollBack()
		{
			if (this.commitedEditorNode != null)
			{
				int num = this.MenuItem.DropDownItems.IndexOf(this.commitedEditorNode);
				ToolStripDropDownItem toolStripDropDownItem = (ToolStripDropDownItem)this.MenuItem.DropDownItems[num + 1];
				if (toolStripDropDownItem != null)
				{
					toolStripDropDownItem.Visible = true;
				}
				this.MenuItem.DropDown.Items.Remove(this.commitedEditorNode);
				if (this.commitedTemplateNode != null)
				{
					this.commitedTemplateNode.RollBack();
					this.commitedTemplateNode.CloseEditor();
					this.commitedTemplateNode = null;
				}
				if (this.commitedEditorNode != null)
				{
					this.commitedEditorNode.Dispose();
					this.commitedEditorNode = null;
				}
			}
		}

		// Token: 0x06001B7B RID: 7035 RVA: 0x00099D74 File Offset: 0x00098D74
		private void RemoveBodyGlyphs(ToolStripDropDownItem item)
		{
			if (item != null)
			{
				foreach (object obj in item.DropDownItems)
				{
					ToolStripItem toolStripItem = (ToolStripItem)obj;
					ToolStripItemDesigner toolStripItemDesigner = (ToolStripItemDesigner)this.designerHost.GetDesigner(toolStripItem);
					if (toolStripItemDesigner != null)
					{
						ControlBodyGlyph bodyGlyph = toolStripItemDesigner.bodyGlyph;
						if (bodyGlyph != null && this.toolStripAdornerWindowService != null && this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Contains(bodyGlyph))
						{
							this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Remove(bodyGlyph);
							toolStripItemDesigner.bodyGlyph = null;
						}
					}
				}
			}
		}

		// Token: 0x06001B7C RID: 7036 RVA: 0x00099E2C File Offset: 0x00098E2C
		internal void RemoveItemBodyGlyph(ToolStripItem item)
		{
			if (item != null)
			{
				ToolStripItemDesigner toolStripItemDesigner = (ToolStripItemDesigner)this.designerHost.GetDesigner(item);
				if (toolStripItemDesigner != null)
				{
					ControlBodyGlyph bodyGlyph = toolStripItemDesigner.bodyGlyph;
					if (bodyGlyph != null && this.toolStripAdornerWindowService != null && this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Contains(bodyGlyph))
					{
						this.toolStripAdornerWindowService.DropDownAdorner.Glyphs.Remove(bodyGlyph);
						toolStripItemDesigner.bodyGlyph = null;
					}
				}
			}
		}

		// Token: 0x06001B7D RID: 7037 RVA: 0x00099E98 File Offset: 0x00098E98
		internal void ResetGlyphs(ToolStripDropDownItem item)
		{
			if (item.DropDown.Visible)
			{
				this.InitializeBodyGlyphsForItems(false, item);
				this.InitializeBodyGlyphsForItems(true, item);
			}
		}

		// Token: 0x06001B7E RID: 7038 RVA: 0x00099EB8 File Offset: 0x00098EB8
		internal override bool SetSelection(bool enterKeyPressed)
		{
			if (enterKeyPressed)
			{
				if (!this.initialized)
				{
					this.InitializeDropDown();
				}
				if (this.selSvc != null && this.KeyboardHandlingService != null)
				{
					int num = 0;
					if (this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveLeft && this.MenuItem.DropDownDirection != ToolStripDropDownDirection.AboveRight)
					{
						num = this.MenuItem.DropDownItems.Count;
						num--;
					}
					this.selSvc.SetSelectedComponents(new object[] { this.MenuItem }, SelectionTypes.Replace);
					if (num >= 0)
					{
						this.KeyboardHandlingService.SelectedDesignerControl = this.MenuItem.DropDownItems[num];
						this.selSvc.SetSelectedComponents(null, SelectionTypes.Replace);
					}
				}
				return true;
			}
			return false;
		}

		// Token: 0x06001B7F RID: 7039 RVA: 0x00099F6B File Offset: 0x00098F6B
		private bool ShouldSerializeDoubleClickEnabled()
		{
			return (bool)base.ShadowProperties["DoubleClickEnabled"];
		}

		// Token: 0x06001B80 RID: 7040 RVA: 0x00099F82 File Offset: 0x00098F82
		private bool ShouldSerializeCheckOnClick()
		{
			return (bool)base.ShadowProperties["CheckOnClick"];
		}

		// Token: 0x06001B81 RID: 7041 RVA: 0x00099F99 File Offset: 0x00098F99
		private bool ShouldSerializeDropDown()
		{
			return this.customDropDown != null;
		}

		// Token: 0x06001B82 RID: 7042 RVA: 0x00099FA7 File Offset: 0x00098FA7
		private bool ShouldSerializeVisible()
		{
			return !base.Visible;
		}

		// Token: 0x06001B83 RID: 7043 RVA: 0x00099FB4 File Offset: 0x00098FB4
		internal override void ShowEditNode(bool clicked)
		{
			if (this.MenuItem == null)
			{
				return;
			}
			try
			{
				if (this.MenuItem.Owner is ToolStripDropDown)
				{
					this.parentItem = ((ToolStripDropDown)this.MenuItem.Owner).OwnerItem;
					if (this.designerHost != null)
					{
						IDesigner designer = this.designerHost.GetDesigner(this.parentItem);
						if (designer is ToolStripMenuItemDesigner)
						{
							((ToolStripMenuItemDesigner)designer).EnterInSituEdit(this.MenuItem);
						}
					}
				}
				else
				{
					base.ShowEditNode(clicked);
				}
			}
			catch (CheckoutException ex)
			{
				if (!ex.Equals(CheckoutException.Canceled))
				{
					throw;
				}
			}
		}

		// Token: 0x06001B84 RID: 7044 RVA: 0x0009A058 File Offset: 0x00099058
		private void SelectItems(ToolStripDropDownItem oldSelection, ISelectionService selSvc)
		{
			ToolStripDropDown toolStripDropDown = (ToolStripDropDown)this.MenuItem.Owner;
			int num = Math.Max(toolStripDropDown.Items.IndexOf(oldSelection), toolStripDropDown.Items.IndexOf(this.MenuItem));
			int i = Math.Min(toolStripDropDown.Items.IndexOf(oldSelection), toolStripDropDown.Items.IndexOf(this.MenuItem));
			ToolStripItem[] array = new ToolStripItem[num - i + 1];
			int num2 = 0;
			while (i <= num)
			{
				array[num2] = toolStripDropDown.Items[i];
				num2++;
				i++;
			}
			selSvc.SetSelectedComponents(array);
		}

		// Token: 0x06001B85 RID: 7045 RVA: 0x0009A0F4 File Offset: 0x000990F4
		internal void ShowOwnerDropDown(ToolStripDropDownItem currentSelection)
		{
			while (currentSelection != null && currentSelection.Owner is ToolStripDropDown)
			{
				currentSelection = (ToolStripDropDownItem)((ToolStripDropDown)currentSelection.Owner).OwnerItem;
				if (currentSelection != null && !currentSelection.DropDown.Visible)
				{
					ToolStripMenuItemDesigner toolStripMenuItemDesigner = this.designerHost.GetDesigner(currentSelection) as ToolStripMenuItemDesigner;
					if (toolStripMenuItemDesigner != null)
					{
						toolStripMenuItemDesigner.InitializeDropDown();
					}
				}
			}
		}

		// Token: 0x06001B86 RID: 7046 RVA: 0x0009A158 File Offset: 0x00099158
		internal void UnHookEvents()
		{
			if (this.MenuItem != null)
			{
				this.MenuItem.DropDown.Closing -= this.OnDropDownClosing;
				this.MenuItem.DropDownOpening -= this.DropDownItem_DropDownOpening;
				this.MenuItem.DropDownOpened -= this.DropDownItem_DropDownOpened;
				this.MenuItem.DropDownClosed -= this.DropDownItem_DropDownClosed;
				this.MenuItem.DropDown.Resize -= this.DropDownResize;
				this.MenuItem.DropDown.ItemAdded -= this.OnItemAdded;
				this.MenuItem.DropDown.Paint -= this.DropDownPaint;
				this.MenuItem.DropDown.LocationChanged -= this.DropDownLocationChanged;
				this.MenuItem.DropDown.Click -= this.DropDownClick;
			}
		}

		// Token: 0x0400156D RID: 5485
		private const int GLYPHINSET = 2;

		// Token: 0x0400156E RID: 5486
		private DesignerToolStripControlHost typeHereNode;

		// Token: 0x0400156F RID: 5487
		private ToolStripTemplateNode typeHereTemplateNode;

		// Token: 0x04001570 RID: 5488
		private DesignerToolStripControlHost commitedEditorNode;

		// Token: 0x04001571 RID: 5489
		private ToolStripTemplateNode commitedTemplateNode;

		// Token: 0x04001572 RID: 5490
		private IDesignerHost designerHost;

		// Token: 0x04001573 RID: 5491
		private ToolStripItem parentItem;

		// Token: 0x04001574 RID: 5492
		private ToolStripAdornerWindowService toolStripAdornerWindowService;

		// Token: 0x04001575 RID: 5493
		private ToolStripKeyboardHandlingService keyboardHandlingService;

		// Token: 0x04001576 RID: 5494
		private ISelectionService selSvc;

		// Token: 0x04001577 RID: 5495
		private DesignerTransaction _pendingTransaction;

		// Token: 0x04001578 RID: 5496
		private bool fireComponentChanged;

		// Token: 0x04001579 RID: 5497
		private bool componentAddingFired;

		// Token: 0x0400157A RID: 5498
		private int indexToInsertNewItem = -1;

		// Token: 0x0400157B RID: 5499
		private DesignerTransaction insertMenuItemTransaction;

		// Token: 0x0400157C RID: 5500
		private DesignerTransaction newMenuItemTransaction;

		// Token: 0x0400157D RID: 5501
		private Rectangle dropDownSizeToInvalidate = Rectangle.Empty;

		// Token: 0x0400157E RID: 5502
		private Rectangle boundsToInvalidateOnRemove = Rectangle.Empty;

		// Token: 0x0400157F RID: 5503
		private ToolStripMenuItemDesigner.ToolStripDropDownGlyph rootControlGlyph;

		// Token: 0x04001580 RID: 5504
		private bool initialized;

		// Token: 0x04001581 RID: 5505
		private UndoEngine undoEngine;

		// Token: 0x04001582 RID: 5506
		private bool undoingCalled;

		// Token: 0x04001583 RID: 5507
		private bool addingDummyItem;

		// Token: 0x04001584 RID: 5508
		private ToolStripDropDown customDropDown;

		// Token: 0x04001585 RID: 5509
		private bool dropDownSet;

		// Token: 0x04001586 RID: 5510
		private SerializationStore serializedDataForDropDownItems;

		// Token: 0x04001587 RID: 5511
		private bool dropDownSetFailed;

		// Token: 0x020002CE RID: 718
		internal class ToolStripDropDownGlyph : Glyph
		{
			// Token: 0x06001B88 RID: 7048 RVA: 0x0009A282 File Offset: 0x00099282
			internal ToolStripDropDownGlyph(Rectangle bounds, Behavior b)
				: base(b)
			{
				this._bounds = bounds;
			}

			// Token: 0x06001B89 RID: 7049 RVA: 0x0009A292 File Offset: 0x00099292
			public override Cursor GetHitTest(Point p)
			{
				if (this._bounds.Contains(p))
				{
					return Cursors.Default;
				}
				return null;
			}

			// Token: 0x06001B8A RID: 7050 RVA: 0x0009A2A9 File Offset: 0x000992A9
			public override void Paint(PaintEventArgs pe)
			{
			}

			// Token: 0x04001588 RID: 5512
			private Rectangle _bounds;
		}

		// Token: 0x020002CF RID: 719
		internal class DropDownBehavior : ControlDesigner.TransparentBehavior
		{
			// Token: 0x06001B8B RID: 7051 RVA: 0x0009A2AB File Offset: 0x000992AB
			internal DropDownBehavior(ControlDesigner designer, ToolStripMenuItemDesigner menuItemDesigner)
				: base(designer)
			{
				this.menuItemDesigner = menuItemDesigner;
			}

			// Token: 0x06001B8C RID: 7052 RVA: 0x0009A2BC File Offset: 0x000992BC
			public override void OnDragEnter(Glyph g, DragEventArgs e)
			{
				ToolStripItemDataObject toolStripItemDataObject = e.Data as ToolStripItemDataObject;
				if (toolStripItemDataObject != null)
				{
					e.Effect = ((Control.ModifierKeys == Keys.Control) ? DragDropEffects.Copy : DragDropEffects.Move);
					return;
				}
				base.OnDragEnter(g, e);
			}

			// Token: 0x06001B8D RID: 7053 RVA: 0x0009A2F8 File Offset: 0x000992F8
			public override void OnDragOver(Glyph g, DragEventArgs e)
			{
				ToolStripItemDataObject toolStripItemDataObject = e.Data as ToolStripItemDataObject;
				if (toolStripItemDataObject != null)
				{
					e.Effect = ((Control.ModifierKeys == Keys.Control) ? DragDropEffects.Copy : DragDropEffects.Move);
					return;
				}
				base.OnDragOver(g, e);
			}

			// Token: 0x06001B8E RID: 7054 RVA: 0x0009A334 File Offset: 0x00099334
			public override void OnDragDrop(Glyph g, DragEventArgs e)
			{
				ToolStripItemDataObject toolStripItemDataObject = e.Data as ToolStripItemDataObject;
				if (toolStripItemDataObject != null)
				{
					ToolStripItem toolStripItem = toolStripItemDataObject.PrimarySelection;
					IDesignerHost designerHost = (IDesignerHost)toolStripItem.Site.GetService(typeof(IDesignerHost));
					ToolStripDropDown toolStripDropDown = toolStripItem.GetCurrentParent() as ToolStripDropDown;
					ToolStripDropDownItem toolStripDropDownItem = null;
					if (toolStripDropDown != null)
					{
						toolStripDropDownItem = toolStripDropDown.OwnerItem as ToolStripDropDownItem;
					}
					if (toolStripDropDownItem != null && designerHost != null)
					{
						ArrayList arrayList = toolStripItemDataObject.DragComponents;
						int num = -1;
						bool flag = e.Effect == DragDropEffects.Copy;
						string text2;
						if (arrayList.Count == 1)
						{
							string text = TypeDescriptor.GetComponentName(arrayList[0]);
							if (text == null || text.Length == 0)
							{
								text = arrayList[0].GetType().Name;
							}
							text2 = SR.GetString(flag ? "BehaviorServiceCopyControl" : "BehaviorServiceMoveControl", new object[] { text });
						}
						else
						{
							text2 = SR.GetString(flag ? "BehaviorServiceCopyControls" : "BehaviorServiceMoveControls", new object[] { arrayList.Count });
						}
						DesignerTransaction designerTransaction = designerHost.CreateTransaction(text2);
						try
						{
							IComponentChangeService componentChangeService = (IComponentChangeService)toolStripItem.Site.GetService(typeof(IComponentChangeService));
							if (componentChangeService != null)
							{
								componentChangeService.OnComponentChanging(toolStripDropDownItem, TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"]);
							}
							if (flag)
							{
								if (toolStripItem != null)
								{
									num = arrayList.IndexOf(toolStripItem);
								}
								ToolStripKeyboardHandlingService toolStripKeyboardHandlingService = (ToolStripKeyboardHandlingService)toolStripItem.Site.GetService(typeof(ToolStripKeyboardHandlingService));
								if (toolStripKeyboardHandlingService != null)
								{
									toolStripKeyboardHandlingService.CopyInProgress = true;
								}
								arrayList = DesignerUtils.CopyDragObjects(arrayList, toolStripItem.Site) as ArrayList;
								if (toolStripKeyboardHandlingService != null)
								{
									toolStripKeyboardHandlingService.CopyInProgress = false;
								}
								if (num != -1)
								{
									toolStripItem = arrayList[num] as ToolStripItem;
								}
							}
							if (e.Effect == DragDropEffects.Move || flag)
							{
								foreach (object obj in arrayList)
								{
									ToolStripItem toolStripItem2 = (ToolStripItem)obj;
									toolStripDropDown.Items.Add(toolStripItem2);
								}
								ToolStripDropDownItem toolStripDropDownItem2 = toolStripItem as ToolStripDropDownItem;
								if (toolStripDropDownItem2 != null)
								{
									ToolStripMenuItemDesigner toolStripMenuItemDesigner = designerHost.GetDesigner(toolStripDropDownItem2) as ToolStripMenuItemDesigner;
									if (toolStripMenuItemDesigner != null)
									{
										toolStripMenuItemDesigner.InitializeDropDown();
									}
								}
								this.menuItemDesigner.selSvc.SetSelectedComponents(new IComponent[] { toolStripItem }, SelectionTypes.Replace | SelectionTypes.Click);
							}
							if (componentChangeService != null)
							{
								componentChangeService.OnComponentChanged(toolStripDropDownItem, TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"], null, null);
							}
							if (flag && componentChangeService != null)
							{
								componentChangeService.OnComponentChanging(toolStripDropDownItem, TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"]);
								componentChangeService.OnComponentChanged(toolStripDropDownItem, TypeDescriptor.GetProperties(toolStripDropDownItem)["DropDownItems"], null, null);
							}
							if (toolStripDropDownItem != null)
							{
								ToolStripMenuItemDesigner toolStripMenuItemDesigner2 = designerHost.GetDesigner(toolStripDropDownItem) as ToolStripMenuItemDesigner;
								if (toolStripMenuItemDesigner2 != null)
								{
									toolStripMenuItemDesigner2.InitializeBodyGlyphsForItems(false, toolStripDropDownItem);
									toolStripMenuItemDesigner2.InitializeBodyGlyphsForItems(true, toolStripDropDownItem);
								}
							}
							BehaviorService behaviorService = (BehaviorService)toolStripItem.Site.GetService(typeof(BehaviorService));
							if (behaviorService != null)
							{
								behaviorService.SyncSelection();
							}
						}
						catch
						{
							if (designerTransaction != null)
							{
								designerTransaction.Cancel();
								designerTransaction = null;
							}
						}
						finally
						{
							if (designerTransaction != null)
							{
								designerTransaction.Commit();
							}
							designerTransaction = null;
						}
					}
				}
			}

			// Token: 0x04001589 RID: 5513
			private ToolStripMenuItemDesigner menuItemDesigner;
		}
	}
}
