using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x020001F4 RID: 500
	internal enum IIDENTITYAUTHORITY_DOES_DEFINITION_MATCH_REFERENCE_FLAGS
	{
		// Token: 0x04000829 RID: 2089
		IIDENTITYAUTHORITY_DOES_DEFINITION_MATCH_REFERENCE_FLAG_EXACT_MATCH_REQUIRED = 1
	}
}
