using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x020001F2 RID: 498
	internal enum IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x04000825 RID: 2085
		IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
