using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x020001F3 RID: 499
	internal enum IIDENTITYAUTHORITY_REFERENCE_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x04000827 RID: 2087
		IIDENTITYAUTHORITY_REFERENCE_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
