using System;

namespace Aladdin.HASP
{
	[Serializable]
	public enum HaspStatus
	{
		StatusOk,
		InvalidAddress,
		InvalidFeature,
		NotEnoughMemory,
		TooManyOpenFeatures,
		AccessDenied,
		IncompatibleFeature,
		ContainerNotFound,
		HaspNotFound = 7,
		BufferTooShort,
		InvalidHandle,
		InvalidFile,
		DriverTooOld,
		NoTime,
		SystemError,
		DriverNotFound,
		InvalidFormat,
		RequestNotSupported,
		InvalidUpdateObject,
		KeyIdNotFound,
		InvalidUpdateData,
		UpdateNotSupported,
		InvalidUpdateCounter,
		InvalidVendorCode,
		EncryptionNotSupported,
		InvalidTime,
		NoBatteryPower,
		UpdateNoAckSpace,
		TerminalServiceDetected,
		FeatureNotImplemented,
		UnknownAlgorithm,
		InvalidSignature,
		FeatureNotFound,
		NoLog,
		LocalCommErr,
		UnknownVcode,
		InvalidXmlSpec,
		InvalidXmlScope,
		TooManyKeys,
		TooManyUsers,
		BrokenSession,
		RemoteCommErr,
		FeatureExpired,
		TooOldLM,
		DeviceError,
		UpdateBlocked,
		TimeError,
		SecureChannelError,
		CorruptStorage,
		VendorLibNotFound,
		InvalidVendorLib,
		EmptyScopeResults,
		VMDetected,
		HardwareModified,
		UserDenied,
		UpdateTooOld,
		UpdateTooNew,
		VendorlibOld,
		UploadError,
		InvalidRecipient,
		InvalidDetachAction,
		TooManyProducts,
		InvalidProduct,
		UnknownRecipient,
		InvalidDuration,
		CloneDetected,
		UpdateAlreadyAdded,
		HaspInactive,
		NoDetachableFeature,
		TooManyHosts,
		RehostNotAllowed,
		LicenseRehosted,
		RehostAlreadyApplied,
		CannotReadFile,
		ExtensionNotAllowed,
		DetachDisabled,
		RehostDisabled,
		DetachedLicenseFound,
		RecipientOldLm,
		SecureStoreIdMismatch,
		DuplicateHostname,
		MissingLM,
		NoApiDylib = 400,
		InvApiDylib,
		InvalidObject = 500,
		InvalidParameter,
		AlreadyLoggedIn,
		AlreadyLoggedOut,
		OperationFailed = 525,
		NoExtensionBlock = 600,
		InvalidPortType = 650,
		InvalidPort,
		NotImplemented = 698,
		InternalError,
		HaspDotNetDllBroken = 652
	}
}
