using System;
using System.Collections;
using System.ComponentModel;

namespace System.Windows.Forms.Design
{
	internal class ToolStripDropDownItemDesigner : ToolStripItemDesigner
	{
		public override void Initialize(IComponent component)
		{
			base.Initialize(component);
		}

		public override ICollection AssociatedComponents
		{
			get
			{
				ToolStripDropDownItem toolStripDropDownItem = base.Component as ToolStripDropDownItem;
				if (toolStripDropDownItem != null && toolStripDropDownItem.DropDown.IsAutoGenerated)
				{
					return toolStripDropDownItem.DropDownItems;
				}
				return base.AssociatedComponents;
			}
		}
	}
}
