using System;

namespace Microsoft.VisualBasic.CompilerServices
{
	internal enum vbErrors
	{
		None,
		ReturnWOGoSub = 3,
		IllegalFuncCall = 5,
		Overflow,
		OutOfMemory,
		OutOfBounds = 9,
		ArrayLocked,
		DivByZero,
		TypeMismatch = 13,
		OutOfStrSpace,
		ExprTooComplex = 16,
		CantContinue,
		UserInterrupt,
		ResumeWOErr = 20,
		OutOfStack = 28,
		UNDONE,
		UndefinedProc = 35,
		TooManyClients = 47,
		DLLLoadErr,
		DLLBadCallingConv,
		InternalError = 51,
		BadFileNameOrNumber,
		FileNotFound,
		BadFileMode,
		FileAlreadyOpen,
		IOError = 57,
		FileAlreadyExists,
		BadRecordLen,
		DiskFull = 61,
		EndOfFile,
		BadRecordNum,
		TooManyFiles = 67,
		DevUnavailable,
		PermissionDenied = 70,
		DiskNotReady,
		DifferentDrive = 74,
		PathFileAccess,
		PathNotFound,
		ObjNotSet = 91,
		IllegalFor,
		BadPatStr,
		CantUseNull,
		UserDefined,
		AdviseLimit,
		BadCallToFriendFunction,
		CantPassPrivateObject,
		DLLCallException,
		DoesntImplementICollection,
		Abort = 287,
		InvalidFileFormat = 321,
		CantCreateTmpFile,
		InvalidResourceFormat = 325,
		InvalidPropertyValue = 380,
		InvalidPropertyArrayIndex,
		SetNotSupportedAtRuntime,
		SetNotSupported,
		NeedPropertyArrayIndex = 385,
		SetNotPermitted = 387,
		GetNotSupportedAtRuntime = 393,
		GetNotSupported,
		PropertyNotFound = 422,
		NoSuchControlOrProperty,
		NotObject,
		CantCreateObject = 429,
		OLENotSupported,
		OLEFileNotFound = 432,
		OLENoPropOrMethod = 438,
		OLEAutomationError = 440,
		LostTLB = 442,
		OLENoDefault,
		ActionNotSupported = 445,
		NamedArgsNotSupported,
		LocaleSettingNotSupported,
		NamedParamNotFound,
		ParameterNotOptional,
		FuncArityMismatch,
		NotEnum,
		InvalidOrdinal,
		InvalidDllFunctionName,
		CodeResourceNotFound,
		CodeResourceLockError,
		DuplicateKey = 457,
		InvalidTypeLibVariable,
		ObjDoesNotSupportEvents,
		InvalidClipboardFormat,
		IdentNotMember,
		ServerNotFound,
		ObjNotRegistered,
		InvalidPicture = 481,
		PrinterError,
		CantSaveFileToTemp = 735,
		SearchTextNotFound = 744,
		ReplacementsTooLong = 746,
		NotYetImplemented = 32768,
		FileNotFoundWithName = 40243,
		CantFindDllEntryPoint = 59201,
		SeekErr = 32771,
		ReadFault,
		WriteFault,
		BadFunctionId,
		FileLockViolation,
		ShareRequired = 32789,
		BufferTooSmall,
		InvDataRead = 32792,
		UnsupFormat,
		RegistryAccess = 32796,
		LibNotRegistered,
		Usage = 32799,
		UndefinedType = 32807,
		QualifiedNameDisallowed,
		InvalidState,
		WrongTypeKind,
		ElementNotFound,
		AmbiguousName,
		ModNameConflict,
		UnknownLcid,
		BadModuleKind = 35005,
		NoContainingLib = 35009,
		BadTypeId,
		BadLibId,
		Eof,
		SizeTooBig,
		ExpectedFuncNotModule = 35015,
		ExpectedFuncNotRecord,
		ExpectedFuncNotProject,
		ExpectedFuncNotVar,
		ExpectedTypeNotProj,
		UnsuitableFuncPropMatch,
		BrokenLibRef,
		UnsupportedTypeLibFeature,
		ModuleAsType = 35024,
		InvalidTypeInfoKind,
		InvalidTypeLibFunction,
		OperationNotAllowedInDll = 40035,
		CompileError,
		CantEvalWatch,
		MissingVbaTypeLib,
		UserReset = 40040,
		MissingEndBrack,
		IncorrectTypeChar,
		InvalidNumLit,
		IllegalChar,
		IdTooLong,
		StatementTooComplex,
		ExpectedTokens,
		InconsistentPropFuncs = 40067,
		CircularType,
		AccessViolation = -2147467261,
		LastTrappable = 746
	}
}
