using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x020000EF RID: 239
	internal enum IIDENTITYAUTHORITY_DOES_DEFINITION_MATCH_REFERENCE_FLAGS
	{
		// Token: 0x04000D9D RID: 3485
		IIDENTITYAUTHORITY_DOES_DEFINITION_MATCH_REFERENCE_FLAG_EXACT_MATCH_REQUIRED = 1
	}
}
