using System;

namespace System.Deployment.Internal.Isolation
{
	// Token: 0x020000ED RID: 237
	internal enum IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAGS
	{
		// Token: 0x04000D99 RID: 3481
		IIDENTITYAUTHORITY_DEFINITION_IDENTITY_TO_TEXT_FLAG_CANONICAL = 1
	}
}
