using System;
using System.Collections;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Design;
using System.Drawing;
using System.Web.UI.Design.Util;
using System.Web.UI.WebControls;
using System.Windows.Forms;
using System.Windows.Forms.Design;

namespace System.Web.UI.Design.WebControls
{
	internal partial class TreeViewBindingsEditorForm : DesignerForm
	{
		public TreeViewBindingsEditorForm(IServiceProvider serviceProvider, global::System.Web.UI.WebControls.TreeView treeView, TreeViewDesigner treeViewDesigner)
			: base(serviceProvider)
		{
			this._treeView = treeView;
			this._autoBindInitialized = false;
			this.InitializeComponent();
			this.InitializeUI();
			foreach (object obj in this._treeView.DataBindings)
			{
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)obj;
				TreeNodeBinding treeNodeBinding2 = (TreeNodeBinding)((ICloneable)treeNodeBinding).Clone();
				treeViewDesigner.RegisterClone(treeNodeBinding, treeNodeBinding2);
				this._bindingsListView.Items.Add(treeNodeBinding2);
			}
		}

		private IDataSourceSchema Schema
		{
			get
			{
				if (this._schema == null)
				{
					IDesignerHost designerHost = (IDesignerHost)base.ServiceProvider.GetService(typeof(IDesignerHost));
					if (designerHost != null)
					{
						HierarchicalDataBoundControlDesigner hierarchicalDataBoundControlDesigner = designerHost.GetDesigner(this._treeView) as HierarchicalDataBoundControlDesigner;
						if (hierarchicalDataBoundControlDesigner != null)
						{
							DesignerHierarchicalDataSourceView designerView = hierarchicalDataBoundControlDesigner.DesignerView;
							if (designerView != null)
							{
								try
								{
									this._schema = designerView.Schema;
								}
								catch (Exception ex)
								{
									IComponentDesignerDebugService componentDesignerDebugService = (IComponentDesignerDebugService)base.ServiceProvider.GetService(typeof(IComponentDesignerDebugService));
									if (componentDesignerDebugService != null)
									{
										componentDesignerDebugService.Fail(SR.GetString("DataSource_DebugService_FailedCall", new object[] { "DesignerHierarchicalDataSourceView.Schema", ex.Message }));
									}
								}
							}
						}
					}
				}
				return this._schema;
			}
		}

		private void AddBinding()
		{
			global::System.Windows.Forms.TreeNode selectedNode = this._schemaTreeView.SelectedNode;
			if (selectedNode != null)
			{
				TreeNodeBinding treeNodeBinding = new TreeNodeBinding();
				if (selectedNode.Text != this._schemaTreeView.Nodes[0].Text)
				{
					treeNodeBinding.DataMember = selectedNode.Text;
					if (((TreeViewBindingsEditorForm.SchemaTreeNode)selectedNode).Duplicate)
					{
						treeNodeBinding.Depth = selectedNode.FullPath.Split(new char[] { this._schemaTreeView.PathSeparator[0] }).Length - 1;
					}
					((IDataSourceViewSchemaAccessor)treeNodeBinding).DataSourceViewSchema = ((TreeViewBindingsEditorForm.SchemaTreeNode)selectedNode).Schema;
					int num = this._bindingsListView.Items.IndexOf(treeNodeBinding);
					if (num == -1)
					{
						this._bindingsListView.Items.Add(treeNodeBinding);
						this._bindingsListView.SetSelected(this._bindingsListView.Items.Count - 1, true);
					}
					else
					{
						treeNodeBinding = (TreeNodeBinding)this._bindingsListView.Items[num];
						this._bindingsListView.SetSelected(num, true);
					}
				}
				else
				{
					this._bindingsListView.Items.Add(treeNodeBinding);
					this._bindingsListView.SetSelected(this._bindingsListView.Items.Count - 1, true);
				}
				this._propertyGrid.SelectedObject = treeNodeBinding;
				this._propertyGrid.Refresh();
				this.UpdateEnabledStates();
			}
			this._bindingsListView.Focus();
		}

		private void ApplyBindings()
		{
			ControlDesigner.InvokeTransactedChange(this._treeView, new TransactedChangeCallback(this.ApplyBindingsChangeCallback), null, SR.GetString("TreeViewDesigner_EditBindingsTransactionDescription"));
		}

		private bool ApplyBindingsChangeCallback(object context)
		{
			this._treeView.DataBindings.Clear();
			foreach (object obj in this._bindingsListView.Items)
			{
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)obj;
				this._treeView.DataBindings.Add(treeNodeBinding);
			}
			PropertyDescriptor propertyDescriptor = TypeDescriptor.GetProperties(this._treeView)["AutoGenerateDataBindings"];
			propertyDescriptor.SetValue(this._treeView, this._autogenerateBindingsCheckBox.Checked);
			return true;
		}

		private IDataSourceViewSchema FindViewSchema(string viewName, int level)
		{
			return TreeViewBindingsEditorForm.FindViewSchemaRecursive(this.Schema, 0, viewName, level, null);
		}

		internal static IDataSourceViewSchema FindViewSchemaRecursive(object schema, int depth, string viewName, int level, IDataSourceViewSchema bestBet)
		{
			if (schema is IDataSourceSchema || schema is IDataSourceViewSchema)
			{
				IDataSourceViewSchema dataSourceViewSchema = schema as IDataSourceViewSchema;
				IDataSourceViewSchema[] array = ((dataSourceViewSchema != null) ? dataSourceViewSchema.GetChildren() : ((IDataSourceSchema)schema).GetViews());
				if (array != null)
				{
					if (depth == level)
					{
						foreach (IDataSourceViewSchema dataSourceViewSchema2 in array)
						{
							if (string.Equals(dataSourceViewSchema2.Name, viewName, StringComparison.OrdinalIgnoreCase))
							{
								return dataSourceViewSchema2;
							}
							if (string.IsNullOrEmpty(dataSourceViewSchema2.Name) && bestBet == null)
							{
								bestBet = dataSourceViewSchema2;
							}
							bestBet = TreeViewBindingsEditorForm.FindViewSchemaRecursive(dataSourceViewSchema2, depth + 1, viewName, level, bestBet);
						}
						return bestBet;
					}
					foreach (IDataSourceViewSchema dataSourceViewSchema3 in array)
					{
						if (level == -1 && string.Equals(dataSourceViewSchema3.Name, viewName, StringComparison.OrdinalIgnoreCase) && bestBet == null)
						{
							return dataSourceViewSchema3;
						}
						bestBet = TreeViewBindingsEditorForm.FindViewSchemaRecursive(dataSourceViewSchema3, depth + 1, viewName, level, bestBet);
					}
					return bestBet;
				}
				return bestBet;
			}
			return null;
		}

		protected override string HelpTopic
		{
			get
			{
				return "net.Asp.TreeView.BindingsEditorForm";
			}
		}

		private void InitializeUI()
		{
			this._bindingsLabel.Text = SR.GetString("TreeViewBindingsEditor_Bindings");
			this._schemaLabel.Text = SR.GetString("TreeViewBindingsEditor_Schema");
			this._okButton.Text = SR.GetString("TreeViewBindingsEditor_OK");
			this._applyButton.Text = SR.GetString("TreeViewBindingsEditor_Apply");
			this._cancelButton.Text = SR.GetString("TreeViewBindingsEditor_Cancel");
			this._propertiesLabel.Text = SR.GetString("TreeViewBindingsEditor_BindingProperties");
			this._autogenerateBindingsCheckBox.Text = SR.GetString("TreeViewBindingsEditor_AutoGenerateBindings");
			this._addBindingButton.Text = SR.GetString("TreeViewBindingsEditor_AddBinding");
			this.Text = SR.GetString("TreeViewBindingsEditor_Title");
			Bitmap bitmap = new Icon(typeof(TreeViewBindingsEditor), "SortUp.ico").ToBitmap();
			bitmap.MakeTransparent();
			this._moveBindingUpButton.Image = bitmap;
			this._moveBindingUpButton.AccessibleName = SR.GetString("TreeViewBindingsEditor_MoveBindingUpName");
			this._moveBindingUpButton.AccessibleDescription = SR.GetString("TreeViewBindingsEditor_MoveBindingUpDescription");
			Bitmap bitmap2 = new Icon(typeof(TreeViewBindingsEditor), "SortDown.ico").ToBitmap();
			bitmap2.MakeTransparent();
			this._moveBindingDownButton.Image = bitmap2;
			this._moveBindingDownButton.AccessibleName = SR.GetString("TreeViewBindingsEditor_MoveBindingDownName");
			this._moveBindingDownButton.AccessibleDescription = SR.GetString("TreeViewBindingsEditor_MoveBindingDownDescription");
			Bitmap bitmap3 = new Icon(typeof(TreeViewBindingsEditor), "Delete.ico").ToBitmap();
			bitmap3.MakeTransparent();
			this._deleteBindingButton.Image = bitmap3;
			this._deleteBindingButton.AccessibleName = SR.GetString("TreeViewBindingsEditor_DeleteBindingName");
			this._deleteBindingButton.AccessibleDescription = SR.GetString("TreeViewBindingsEditor_DeleteBindingDescription");
			base.Icon = null;
		}

		private void OnApplyButtonClick(object sender, EventArgs e)
		{
			this.ApplyBindings();
			this._applyButton.Enabled = false;
		}

		private void OnAddBindingButtonClick(object sender, EventArgs e)
		{
			this._applyButton.Enabled = true;
			this.AddBinding();
		}

		private void OnAutoGenerateChanged(object sender, EventArgs e)
		{
			if (this._autoBindInitialized)
			{
				this._applyButton.Enabled = true;
			}
		}

		private void OnBindingsListViewGotFocus(object sender, EventArgs e)
		{
			this.UpdateSelectedBinding();
		}

		private void OnBindingsListViewSelectedIndexChanged(object sender, EventArgs e)
		{
			this.UpdateSelectedBinding();
		}

		private void OnCancelButtonClick(object sender, EventArgs e)
		{
			base.DialogResult = DialogResult.Cancel;
			base.Close();
		}

		private void OnDeleteBindingButtonClick(object sender, EventArgs e)
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				this._applyButton.Enabled = true;
				int num = this._bindingsListView.SelectedIndices[0];
				this._bindingsListView.Items.RemoveAt(num);
				if (num >= this._bindingsListView.Items.Count)
				{
					num--;
				}
				if (num >= 0 && this._bindingsListView.Items.Count > 0)
				{
					this._bindingsListView.SetSelected(num, true);
				}
			}
		}

		protected override void OnInitialActivated(EventArgs e)
		{
			base.OnInitialActivated(e);
			global::System.Windows.Forms.TreeNode treeNode = this._schemaTreeView.Nodes.Add(SR.GetString("TreeViewBindingsEditor_EmptyBindingText"));
			if (this.Schema != null)
			{
				this.PopulateSchema(this.Schema);
				this._schemaTreeView.ExpandAll();
			}
			this._schemaTreeView.SelectedNode = treeNode;
			this._autoBindInitialized = false;
			this._autogenerateBindingsCheckBox.Checked = this._treeView.AutoGenerateDataBindings;
			this._autoBindInitialized = true;
			this.UpdateEnabledStates();
		}

		private void OnMoveBindingUpButtonClick(object sender, EventArgs e)
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				this._applyButton.Enabled = true;
				int num = this._bindingsListView.SelectedIndices[0];
				if (num > 0)
				{
					TreeNodeBinding treeNodeBinding = (TreeNodeBinding)this._bindingsListView.Items[num];
					this._bindingsListView.Items.RemoveAt(num);
					this._bindingsListView.Items.Insert(num - 1, treeNodeBinding);
					this._bindingsListView.SetSelected(num - 1, true);
				}
			}
		}

		private void OnMoveBindingDownButtonClick(object sender, EventArgs e)
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				this._applyButton.Enabled = true;
				int num = this._bindingsListView.SelectedIndices[0];
				if (num + 1 < this._bindingsListView.Items.Count)
				{
					TreeNodeBinding treeNodeBinding = (TreeNodeBinding)this._bindingsListView.Items[num];
					this._bindingsListView.Items.RemoveAt(num);
					this._bindingsListView.Items.Insert(num + 1, treeNodeBinding);
					this._bindingsListView.SetSelected(num + 1, true);
				}
			}
		}

		private void OnOKButtonClick(object sender, EventArgs e)
		{
			this.ApplyBindings();
			base.DialogResult = DialogResult.OK;
			base.Close();
		}

		private void OnPropertyGridPropertyValueChanged(object s, PropertyValueChangedEventArgs e)
		{
			this._applyButton.Enabled = true;
			if (e.ChangedItem.PropertyDescriptor.Name == "DataMember")
			{
				string text = (string)e.ChangedItem.Value;
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)this._bindingsListView.Items[this._bindingsListView.SelectedIndex];
				this._bindingsListView.Items[this._bindingsListView.SelectedIndex] = treeNodeBinding;
				this._bindingsListView.Refresh();
				IDataSourceViewSchema dataSourceViewSchema = this.FindViewSchema(text, treeNodeBinding.Depth);
				if (dataSourceViewSchema != null)
				{
					((IDataSourceViewSchemaAccessor)treeNodeBinding).DataSourceViewSchema = dataSourceViewSchema;
				}
				this._propertyGrid.SelectedObject = treeNodeBinding;
				this._propertyGrid.Refresh();
				return;
			}
			if (e.ChangedItem.PropertyDescriptor.Name == "Depth")
			{
				int num = (int)e.ChangedItem.Value;
				TreeNodeBinding treeNodeBinding2 = (TreeNodeBinding)this._bindingsListView.Items[this._bindingsListView.SelectedIndex];
				IDataSourceViewSchema dataSourceViewSchema2 = this.FindViewSchema(treeNodeBinding2.DataMember, num);
				if (dataSourceViewSchema2 != null)
				{
					((IDataSourceViewSchemaAccessor)treeNodeBinding2).DataSourceViewSchema = dataSourceViewSchema2;
				}
				this._propertyGrid.SelectedObject = treeNodeBinding2;
				this._propertyGrid.Refresh();
			}
		}

		private void OnSchemaTreeViewAfterSelect(object sender, TreeViewEventArgs e)
		{
			this.UpdateEnabledStates();
		}

		private void OnSchemaTreeViewGotFocus(object sender, EventArgs e)
		{
			this._propertyGrid.SelectedObject = null;
		}

		private void PopulateSchema(IDataSourceSchema schema)
		{
			if (schema == null)
			{
				return;
			}
			IDictionary dictionary = new Hashtable();
			IDataSourceViewSchema[] views = schema.GetViews();
			if (views != null)
			{
				for (int i = 0; i < views.Length; i++)
				{
					this.PopulateSchemaRecursive(this._schemaTreeView.Nodes, views[i], 0, dictionary);
				}
			}
		}

		private void PopulateSchemaRecursive(global::System.Windows.Forms.TreeNodeCollection nodes, IDataSourceViewSchema viewSchema, int depth, IDictionary duplicates)
		{
			if (viewSchema == null)
			{
				return;
			}
			TreeViewBindingsEditorForm.SchemaTreeNode schemaTreeNode = new TreeViewBindingsEditorForm.SchemaTreeNode(viewSchema);
			nodes.Add(schemaTreeNode);
			TreeViewBindingsEditorForm.SchemaTreeNode schemaTreeNode2 = (TreeViewBindingsEditorForm.SchemaTreeNode)duplicates[viewSchema.Name];
			if (schemaTreeNode2 != null)
			{
				schemaTreeNode2.Duplicate = true;
				schemaTreeNode.Duplicate = true;
			}
			foreach (object obj in this._bindingsListView.Items)
			{
				TreeNodeBinding treeNodeBinding = (TreeNodeBinding)obj;
				if (string.Compare(treeNodeBinding.DataMember, viewSchema.Name, StringComparison.OrdinalIgnoreCase) == 0)
				{
					IDataSourceViewSchemaAccessor dataSourceViewSchemaAccessor = treeNodeBinding;
					if (depth == treeNodeBinding.Depth || dataSourceViewSchemaAccessor.DataSourceViewSchema == null)
					{
						dataSourceViewSchemaAccessor.DataSourceViewSchema = viewSchema;
					}
				}
			}
			IDataSourceViewSchema[] children = viewSchema.GetChildren();
			if (children != null)
			{
				for (int i = 0; i < children.Length; i++)
				{
					this.PopulateSchemaRecursive(schemaTreeNode.Nodes, children[i], depth + 1, duplicates);
				}
			}
		}

		private void UpdateEnabledStates()
		{
			if (this._bindingsListView.SelectedIndices.Count > 0)
			{
				int num = this._bindingsListView.SelectedIndices[0];
				this._moveBindingDownButton.Enabled = num + 1 < this._bindingsListView.Items.Count;
				this._moveBindingUpButton.Enabled = num > 0;
				this._deleteBindingButton.Enabled = true;
			}
			else
			{
				this._moveBindingDownButton.Enabled = false;
				this._moveBindingUpButton.Enabled = false;
				this._deleteBindingButton.Enabled = false;
			}
			this._addBindingButton.Enabled = this._schemaTreeView.SelectedNode != null;
		}

		private void UpdateSelectedBinding()
		{
			TreeNodeBinding treeNodeBinding = null;
			if (this._bindingsListView.SelectedItems.Count > 0)
			{
				TreeNodeBinding treeNodeBinding2 = (TreeNodeBinding)this._bindingsListView.SelectedItems[0];
				treeNodeBinding = treeNodeBinding2;
			}
			this._propertyGrid.SelectedObject = treeNodeBinding;
			this._propertyGrid.Refresh();
			this.UpdateEnabledStates();
		}

		private IDataSourceSchema _schema;

		private class SchemaTreeNode : global::System.Windows.Forms.TreeNode
		{
			public SchemaTreeNode(IDataSourceViewSchema schema)
				: base(schema.Name)
			{
				this._schema = schema;
			}

			public bool Duplicate
			{
				get
				{
					return this._duplicate;
				}
				set
				{
					this._duplicate = value;
				}
			}

			public object Schema
			{
				get
				{
					return this._schema;
				}
			}

			private IDataSourceViewSchema _schema;

			private bool _duplicate;
		}
	}
}
